### ISSUE TITLE
Scratchpad-open button overrides scrollbar in firefox

### ISSUE THREAD

**Issue by b-trav** [ipython-contrib/jupyter_contrib_nbextensions#1004]
I can not use my mouse to grab the scrollbar button at the bottom of a notebook because the scratchpad-open button overrides the scrollbar.

This can be fixed by altering;

```diff
.scratchpad-btn {
  float: right;
-  padding-right: 24px;
+  margin-right: 24px;
  opacity: 0.2;
  font-size: 24px;
  z-index: 106;
}
```

in

`/src/jupyter_contrib_nbextensions/nbextensions/scratchpad/scratchpad.css`

**Comment by jcb91** [comment]
Seems like a neat, simple fix, would you care to make a PR, @b-trav?

**Comment by jcb91** [comment]
Oh, also, it might make sense to submit this to the upstream repo, at https://github.com/minrk/nbextension-scratchpad

**Comment by b-trav** [comment]
I have made a PR at https://github.com/minrk/nbextension-scratchpad.
