### ISSUE TITLE
[collapsible_headings] - feature request : "Collapse-All"

### ISSUE THREAD

**Issue by b-trav** [ipython-contrib/jupyter_contrib_nbextensions#1005]
I would find it useful to have a menu button or a keyboard short-cut which allowed "Collapse All Headings" and "Un-collapse All Headings".

**Comment by jcb91** [comment]
Sounds fairly straightforward, I'll take a stab at it when I get a chance

**Comment by jcb91** [comment]
I've made an attempt at this in #1025 - let me know if you get a chance to try it :)
