### ISSUE TITLE
[Freeze] read-only cells appear with no color when (re)loading notebook

### ISSUE THREAD

**Issue by SteliosStefanatos** [ipython-contrib/jupyter_contrib_nbextensions#1008]
As the title says, when I reload (refresh) a notebook page on my browser (firefox) the "read-only" cells appear with no color (as normal ones), however, they still behave as read-only. Same issue when opening saved notebooks that had cells marked as "read-only". This concerns only "read-only" cells as "freeze" cells operate as normal.

Working on linux, anaconda python 3.6 (`conda update --all`), nbextensions 0.2.8.

**Comment by jcb91** [comment]
thanks for the report. So you're saying that frozen cells have the correct (altered) colour on reload, but that the read-only ones don't have their colour altered as should happen?

**Comment by SteliosStefanatos** [comment]
Thank you for the reply (sorry for my late response). Yes, read-only cells appear as normal ones on reload. You cannot say they are indeed read-only unless you attempt to edit and run them, which is annoying. Can you reproduce this?

**Comment by jcb91** [comment]
Right, reproducible, it's the result of a typo whereby `get_state` returns `readonly`, but `set_state` would only recognise `read_only`. I'll alter set to use either variant...

**Comment by jcb91** [comment]
This should now be fixed in current master
