### ISSUE TITLE
varInspector keeps variables persistent after using %reset magic

### ISSUE THREAD

**Issue by edridgedsouza** [ipython-contrib/jupyter_contrib_nbextensions#1014]
If you reset the kernel with the `%reset` magic command, all of the previous variables are still present with their old values in the variable explorer. This doesn't appear to happen when the variables are individually deleted with `del`

**Comment by jfbercher** [comment]
Reproducible and Interesting. 
Even new variables are not listed. I will look at what does `%reset`; but perhaps that it creates a new namespace and that the last one is still accessible. This would mean that perhaps `varInspector` needs to catch the %reset magic and restarts itself in that case;

**Comment by jfbercher** [comment]
The hypothesis in my previous comment (that %reset may create a new namespace) was wrong. 

What happened was simply that some hidden variables and functions used by `varInspector` (to list all variables used by the current kernel) were cleared by the %reset, and therefore `varInspector` failed. In #1016 , the state of the refresh operation is checked, and in case of error (which occurs if the variables/functions used by `varInspector` are cleared), the extension is reinitialized.

**Comment by jfbercher** [comment]
Should be fixed by #1019
