### ISSUE TITLE
python2 kernel and variable inspector

### ISSUE THREAD

**Issue by xcix** [ipython-contrib/jupyter_contrib_nbextensions#1015]
When using python2 kernel and variable inspector is enabled, print operator in jupyter does not work with SyntaxError exception. Output of %whos magic contains print_function from __future__, possibly because of import in the beggining of this file https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/varInspector/var_list.py

**Comment by jfbercher** [comment]
Should be fixed by #1016
