### ISSUE TITLE
Sidebar file navigation

### ISSUE THREAD

**Issue by danpf** [ipython-contrib/jupyter_contrib_nbextensions#1020]
I was wondering if it would be possible to introduce a file explorer navigation sidebar similar to the one i screenshotted below. I've been looking for an extension that's very similar to the current toc2, but serves as a file explorer to quickly open other notebooks. it looks like jupyterlab will have something similar, but that's probably a ways off, and it doesn't display the hierarchy which i think is useful for project/subproject organization. 

![screenshot_20170712_110108](https://user-images.githubusercontent.com/16297104/28132374-8a9f5472-66f1-11e7-92db-842eaab6c816.png)

**Comment by jcb91** [comment]
Certainly possible, not sure how convenient it will/would prove to be, but I'll try to give it a go when I get a chance. Out of interest/for inspiration, where did your screenshot come from?

**Comment by danpf** [comment]
That would be awesome!
it's the KDE Dolphin file browser 16.04.3.
https://www.kde.org/applications/system/dolphin/
![screenshot_20170712_110108](https://user-images.githubusercontent.com/16297104/28249042-9c281be2-6a03-11e7-8cf7-ac8ace5b9e7a.png)
