### ISSUE TITLE
toc2  feature request: Allow each section levels to be collapsed in the floating toc panel

### ISSUE THREAD

**Issue by chiwhalee** [ipython-contrib/jupyter_contrib_nbextensions#1024]
Hi  there, 

   For a large notebook whose toc may be also very long, it is desirable that each nested sections in the toc can be collapsed individually (Currently they are all fully expanded).  Just see similar features of the navigation panel in MS word or Adobe pdf.   Thanks!

**Comment by jfbercher** [comment]
Yep. It would be very nice. 

Not impossible to do but there is some work and I don't know when I'll have a chance to look at it. Any help is welcome. 
In addition, this could be an opportunity to add an interaction with @jcb91 's `collapsible headings` (collapse in the toc collapse in notebook and reciprocally).

**Comment by jcb91** [comment]
> collapse in the toc collapse in notebook and reciprocally

oh hey, I hadn't thought of that, but it's a neat idea!
