### ISSUE TITLE
So many extensions fail due to 'possibly incompatible'

### ISSUE THREAD

**Issue by BruceChen2017** [ipython-contrib/jupyter_contrib_nbextensions#1037]
I am using the latest version of jupyter notebook.How can I fix this?

**Comment by jcb91** [comment]
Duplicate of #942. Essentially most should still work fine, and are just marked *possibly* incompatible because they haven't been tested. The configurator check box will allow you to enable them anyway.

**Comment by BruceChen2017** [comment]
I got it.Because I check the option `disable configuration for nbextensions without explicit compatibility`,I can't try other extensions. @jcb91

**Comment by queirozfcom** [comment]
> I got it.Because I checked the option `disable configuration for nbextensions without explicit compatibility` before,I couldn't try other extensions. @jcb91

Yes!!!!!!
