### ISSUE TITLE
ls .ipython/nbextensions/ returns blank. Can't Install

### ISSUE THREAD

**Issue by jackalack** [ipython-contrib/jupyter_contrib_nbextensions#1038]
Hey all,

I followed https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator and successfully install nbextensions.  Now I am trying to install annotations and am not having any luck. 
 For step 2, you are supposed to move annotations to .ipython/nbextensions/IPython-notebook-extensions-3.x; however, my ~/.ipython/nbextensions/ is empty.  I tried moving annotations to  ~/.ipython/nbextensions/, but received the following error.  Any tips would be greatly appreciated.

![screen shot 2017-08-07 at 9 09 49 am](https://user-images.githubusercontent.com/7672771/29035371-33338dca-7b50-11e7-9d5e-097738288223.png)

**Comment by juhasch** [comment]
Not sure what then annotations extension is. It looks like it is quite old, or you have a very old installation. It has been a long time since extensions were located in the `.ipython` directory.

Can you provide more details about this extension ?

**Comment by jackalack** [comment]
yea, it is from 2015.  https://github.com/sashabaranov/ipython-annotate.  If you know of any more modern annotation extensions that would also be great!

**Comment by juhasch** [comment]
You have two separate issues:
a) You installed the extension to a place the notebook does not find it. You can try `jupyter --path` and see where the `data` directories are. This is where nbextensions will be found.
b) The extension does not work with recent Jupyter notebook versions anymore. It would need to be updated. 

Sorry, I can't think of an alternative extension right now.

**Comment by jcb91** [comment]
Closing this as the headline issue is fixed. Please reopen a new one if you want to find an annotate replacement :smile:
