### ISSUE TITLE
Add new snippets for the snippets extension

### ISSUE THREAD

**Issue by shichuzhu** [ipython-contrib/jupyter_contrib_nbextensions#1040]
I'm trying to follow the guide [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/snippets#adding-new-snippets) to create my custom code snippets. However, I'm not sure where is the config file `nbextensions/snippets/snippets.json` mentioned in the doc? I'm using Anaconda 3.6 on a Windows machine and I was able to find the same file under 

    C:\Anaconda3\pkgs\jupyter_contrib_nbextensions-0.2.8-py36_1\Lib\site-packages\jupyter_contrib_nbextensions\nbextensions\snippets

My question is

1. After changing the snippets.json in the above directory, the new snippet is not showing up in the jupyter notebook. My guess is that I'm using a different kernel than the original root conda environment. So which file shall I modify to add my own snippet?
2. Instead of directly changing the source file in the conda library, is there a better/safer way to add custom snippet (like watching a .jupyter/nbextensions/snippets/snippets.json) under a user home directory?

**Comment by shichuzhu** [comment]
I just figured out the first question. Typing
`jupyter --paths`
indicates that jupyter is also checking
C:\Anaconda3\share\jupyter for data.
Modifying the C:\Anaconda3\share\jupyter\nbextensions\snippets\snippets.json does work with the jupyter notebook.

I'm still wondering the seconds question though. Would be great if I can solve the problem without changing anything under 'C:\Anaconda3', but things under my home directory 'C:\User\foo' instead. Any idea is appreciated.

**Comment by jcb91** [comment]
The first path you mention, `C:\Anaconda3\pkgs\jupyter_contrib_nbextensions-0.2.8-py36_1\Lib\site-packages\jupyter_contrib_nbextensions\nbextensions\snippets`, is the anaconda python package. For use, (as opposed to installation of python package) the nbextension files are copied to one of the jupyter data directories, as found in the output of `jupyter --paths`. The default for the conda package is to install them in the sys-prefix directory, which is different for each conda environment (and the output of `jupyter --paths` will vary correspondingly depending on which environment is active). I think on Windows, the per-user data directory (which can be used for things independent of active environment) is by default somewhere under the user's appdata directory. Look for the directory in the data section of the output of `jupyter --paths` which begins with `C:/Users/foo` or similar. Does (any of) that make sense?

**Comment by jcb91** [comment]
Also, I think the `C:\Anaconda3\share\jupyter` is probably the sys-prefix data directory of the root conda environment...

**Comment by shichuzhu** [comment]
@jcb91 Thanks for the explanations and suggestion!
Here's the output of
`jupyter --paths`
`(C:\Anaconda3) C:\Users\foo>jupyter --path
config:
    C:\Users\foo\.jupyter
    C:\Anaconda3\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\foo\AppData\Roaming\jupyter
    C:\Anaconda3\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\foo\AppData\Roaming\jupyter\runtime`

The `C:\Users\foo\AppData\Roaming\jupyter` should be the holy grail you mentioned. The folder did not have a `nbextensions` folder. I created `nbextensions\snippets` folders and made another `snippets.json` file inside. Restarting the jupyter notebook and it works! Plus the `C:\Users\foo\AppData\Roaming\jupyter` seems to have surppressed the snippets config in the `C:\Anaconda3\share\jupyter` (for snippet only, other extension not affected).

Problem solved :)

**Comment by jcb91** [comment]
Great, glad you've got it working as desired @shichuzhu. Perhaps it might be worth updating/expanding the documentation?

> Plus the `C:\Users\foo\AppData\Roaming\jupyter` seems to have surppressed the snippets config in the `C:\Anaconda3\share\jupyter` (for snippet only, other extension not affected).

A summary of how nbextensions files are located by the server is probably useful here, and possibly for future reference. The server looks for nbextension files (anything under server path `/nbextensions/`) in locations in its `nbextensions_path` property in order, stopping as soon as it finds one (so order is important, the first items in the path will override later ones, as you've discovered).

The `nbextensions_path` is made up of:

 1. Anything in the server config attribute `extra_nbextensions_path`, which by default is empty
 2. `jupyter_path('nbextensions')`, which is essentially the `nbextensions` subdirectory of each of the jupyter data directories.

The jupyter data directories are OS-dependent, but are essentially:

 1. The directory in environment variable `JUPYTER_PATH`, if set
 2. The __per-user data directory__, which is
    1. the value of environment variable `JUPYTER_DATA_DIR`, if set
    2. on OSX, `~/Library/Jupyter`
    3. on Windows, `%APPDATA%/jupyter` if the env var `APPDATA` is set, usually this ends up as something like `C:\Users\username\AppData\Roaming\jupyter`
    4. on other systems, like Linux, if env variable `XDG_DATA_HOME` is set, `$XDG_DATA_HOME/.jupyter`, otherwise `~/.local/share/jupyter`
 3. the __sys-prefix data directory__, which is specific to the *server's* python environment. E.g. in the anaconda root environment, this is something like `C:\Anaconda3\share\jupyter`. Note however, that it's the environment from which you run the notebook server that's important (as opposed to the root, environment, or the environment used by kernels)
 4. The __system-wide data directory/directories__, which are
    1. On Windows, `%PROGRAMDATA%\jupyter` (usually `C:\ProgramData`), if PROGRAMDATA env variable is set. If `%PROGRAMDATA%` is not set, the `share/jupyter` subdirectory of the python environment
    2. On other systems, `/usr/local/share/jupyter`, followed by `/usr/share/jupyter`

**Comment by shichuzhu** [comment]
@jcb91 Putting these into the documentation would be very helpful. I browsed the existing related [entry](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html#jupyter-config-path) and then realized this related to the question I had.

Perhaps using the consistent name/term in the doc would help, too. For this case, I started with [snippets doc](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/snippets#adding-new-snippets) but failed to find what `nbextensions/` directory refers to. It would help if the doc mentioned `nbextensions` folder under 'Jupyter config path' or just put a link directing to the [link](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html#jupyter-config-path)

**Comment by jcb91** [comment]
Right, the config directories are related, and follow a similar structure, but are distinct from the data directories, so it probably makes sense to add more docs about them, the uses for each, and then maybe link to those from the snippets docs. Any PR you care to make gratefully accepted, otherwise I'll try to get to this sometime soon :)

**Comment by chuaxr** [comment]
I had the same problem, and agree that adding more detail in the docs would be very helpful. It took me a while to realize that I should create a new snippets folder in nbextensions rather than change the one in site-packages, and that I needed to restart the notebook.

**Comment by jcb91** [comment]
Whoops, apologies, that was meant to be :) (phone keyboard!)

**Comment by chuaxr** [comment]
@jcb91 I've made a couple of minor changes which should help. This is my first time submitting a PR, so please let me know if there's something I've missed.
