### ISSUE TITLE
Question: Will these work with custom kernels?

### ISSUE THREAD

**Issue by zbeekman** [ipython-contrib/jupyter_contrib_nbextensions#1042]
I'm wondering if some of these extensions will work with custom kernels. I anticipate that, in general, magics and magic extensions probably won't work, but will the ToC extension work with any kernel? Others?

Thanks!

**Comment by jcb91** [comment]
Most are kernel-agnostic, so should be fine. Off the top of my head, the variable inspector needs an ipython kernel, code_prettify can be made to work with a custom kernel but requires extra setup for anything beyond ipython/JavaScript/r, toc2 is fine with the exception that it's "download with TOC embedded" only works with ipython kernel. There may be other exceptions, but that's what springs to mind right now...

**Comment by zbeekman** [comment]
great thanks for the info!
