### ISSUE TITLE
Cannot install pip install jupyter_contrib_nbextensions in cygwin

### ISSUE THREAD

**Issue by reedv** [ipython-contrib/jupyter_contrib_nbextensions#1043]
In Cygwin64, running 
`pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master`
outputs

```
pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master

Collecting https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
  Downloading https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master (20.3MB)
    100% |████████████████████████████████| 20.3MB 67kB/s
Requirement already satisfied: ipython_genutils in ./lib/python2.7/site-packages (from jupyter-contrib-nbextensions==0.2.8)
Collecting jupyter_contrib_core>=0.3 (from jupyter-contrib-nbextensions==0.2.8)
  Downloading jupyter_contrib_core-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: jupyter_core in ./lib/python2.7/site-packages (from jupyter-contrib-nbextensions==0.2.8)
Collecting jupyter_highlight_selected_word>=0.0.10 (from jupyter-contrib-nbextensions==0.2.8)
  Using cached jupyter_highlight_selected_word-0.0.11-py2.py3-none-any.whl
Collecting jupyter_latex_envs>=1.3.8 (from jupyter-contrib-nbextensions==0.2.8)
  Using cached jupyter_latex_envs-1.3.8.4.tar.gz
Collecting jupyter_nbextensions_configurator>=0.2.4 (from jupyter-contrib-nbextensions==0.2.8)
  Using cached jupyter_nbextensions_configurator-0.2.5-py2.py3-none-any.whl
Requirement already satisfied: nbconvert>=4.2 in ./lib/python2.7/site-packages (from jupyter-contrib-nbextensions==0.2.8)
Requirement already satisfied: notebook>=4.0 in ./lib/python2.7/site-packages (from jupyter-contrib-nbextensions==0.2.8)
Collecting psutil>=2.2.1 (from jupyter-contrib-nbextensions==0.2.8)
  Using cached psutil-5.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    platform cygwin is not supported
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mVu_o7/psutil/
```

Similar results when running 
` pip install jupyter_contrib_nbextensions`.

**Comment by jcb91** [comment]
This seems to be a failure to install he dependency psutils, could you post output of 

    pip install "psutils>=2.2.1"

Please?

**Comment by reedv** [comment]
Running `pip install "psutils>=2.2.1"` returns the same message as at the end of the originally posted error message:
```
Collecting psutil>=2.2.1 (from jupyter-contrib-nbextensions==0.2.8)
  Using cached psutil-5.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    platform cygwin is not supported
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mVu_o7/psutil/
```

Where the problem seems to be that psutil is not supported on cygwin (looking [here](https://github.com/giampaolo/psutil/issues/82) and [here](https://github.com/nvbn/thefuck/issues/470)). Is there be a way to simply bypass this package for Windows users using cygwin?

**Comment by jcb91** [comment]
> the problem seems to be that psutil is not supported on cygwin

Exactly. I don't really hunk we need psutils at all, given that all it's currently used for is a half-hearted check to see if a notebook server is already running, for which we should probably now use the jupyter server list app instead. But for now, it's a requirement for the install (not at runtime).

> Is there be a way to simply bypass this package for Windows users using cygwin?

It is possible, though I don't think it's exactly simple. Essentially, install with the `--no-deps` flag, after manually installing the available dependencies. So, something like

    pip install 'ipython_genutils' 'jupyter_contrib_core >=0.3' 'jupyter_core' 'jupyter_highlight_selected_word >=0.0.10' 'jupyter_latex_envs >=1.3.8' 'jupyter_nbextensions_configurator >=0.2.4' 'nbconvert >=4.2' 'notebook >=4.0' 'pyyaml' 'tornado' 'traitlets >=4.1'
    pip install --no-deps https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master

**Comment by jcb91** [comment]
Then, since you won't have psutils, I'm afraid the

    jupyter contribute nbextensions install

Command, and even importing `jupyter_contrib_nbextensions.install`, won't work, and you'll have to install the nbextensions (as opposed to python package) manually with a little python...

**Comment by juhasch** [comment]
`psutils` is required to make sure the notebook server itself is not running during installation.

If you want to, you can install `jupyter-contrib-nbextensions` by hand using the instructions from http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html#installation-from-cloned-repo.
After cloning the repo, you then need to remove the `psutils` requirements in `setup.py` and change the `notebook_is_running()` function in `install.py` to always return `False`.

**Comment by jcb91** [comment]
Thanks @juhasch, that's a better idea than mine!
