### ISSUE TITLE
Codefolding extension does not restore folding with nested expression

### ISSUE THREAD

**Issue by lucainnocenti** [ipython-contrib/jupyter_contrib_nbextensions#1046]
Consider the following MWE:

```
# testsets
a = 2
def foo():
    pass
```
which appears, when the Codefolding extension is loaded, as:
![image 1](https://user-images.githubusercontent.com/10957113/29276253-e0bdddf0-8105-11e7-9e19-8293e8c404c6.png)

- If I fold the code at the line `def foo():`, save and reload, I get the folding back as expected.
- If I fold the code at the first line, save and reload, I still get the folding back as expected.
- However, if I fold at the third line and then at the first line, save and reload, the folding is *not* restored.

Executing `IPython.notebook.get_cells()[0].metadata.code_folding` from the console, I do get what to me looks like what I should get when the code is folded at both positions:
![image 2](https://user-images.githubusercontent.com/10957113/29276611-06a96894-8107-11e7-8fbe-91de102ae4d7.png)
I still get this when I reload the page and the code does not look folded, so I guess there is something wrong in the code that should restore the folding?

I see this on both Chrome and Opera under Windows 10, with the jupyter server run from bash on ubuntu on windows.

**Comment by jcb91** [comment]
> I still get this when I reload the page and the code does not look folded, so I guess there is something wrong in the code that should restore the folding?

That sounds like an accurate diagnosis to me. Investigating, it seems that processing the second fold clears the first fold, since they're at that point on the same (editor) line. This can be fixed by using `cell.metadata.code_folding.sort().reverse()` to ensure they get processed in the correct order

**Comment by lucainnocenti** [comment]
great, that should do it, thanks!
