### ISSUE TITLE
Making it work would with JupyterLab

### ISSUE THREAD

**Issue by samarthiith** [ipython-contrib/jupyter_contrib_nbextensions#1048]
Thanks for this, super useful!
It would be awesome if this also worked with JupyterLab. (https://github.com/jupyterlab/jupyterlab) Or does it already? If yes, how?

**Comment by juhasch** [comment]
The JupyterLab implementation is quite different from the notebook. As JupyterLab is an 'early preview' right now, it makes sense to wait for it to stabilize before looking at extensions. Thats how I see it at least.

**Comment by jfbercher** [comment]
@juhasch I agree!

**Comment by samarthiith** [comment]
Thanks for clarification...
