### ISSUE TITLE
Notebook Slideshow Extension , Toggle button not showing

### ISSUE THREAD

**Issue by Carreau** [ipython-contrib/jupyter_contrib_nbextensions#107]
Following up from ipython/ipython#6511 cc @fera0013 who opened original issue.

**Comment by AlbertPWilliams** [comment]
Green toggle isn't showing on 3.x
Though the toggle functionality does work.

**Comment by scollis** [comment]
Hey all.. I am running into this problem.. 4.0.4-py27_0  
I get the slide show button showing when I create a new notebook but not after I reload.
