### ISSUE TITLE
How to enable skip h1 header config?

### ISSUE THREAD

**Issue by xxf1995** [ipython-contrib/jupyter_contrib_nbextensions#1070]
I can't find this option in the parameters under nb extensions config.
![wx20170830-185414](https://user-images.githubusercontent.com/8936233/29902707-a4232628-8db4-11e7-9069-65643edc73f9.png)

**Comment by jcb91** [comment]
It looks as though you don't have a new enough version installed. This is probably (at a guess, given no further information) because you're using conda, and I haven't put together a new conda release yet 😅

**Comment by jcb91** [comment]
this should hopefully be fixed in the most-recent releases
