### ISSUE TITLE
Accidentally hidden this plugin, how can it let it appear again？

### ISSUE THREAD

**Issue by Lovephysics** [ipython-contrib/jupyter_contrib_nbextensions#1071]
I have install jupyter_contrib_nbextensions. And can see this plugin in jupyter notebook. 
Accidentally hidden this plugin, how can it let it appear again

**Comment by jcb91** [comment]
Which plugin  have you accidentally hidden? I'm guessing that you mean `jupyter_nbextensions_configurator`?

**Comment by Lovephysics** [comment]
thank you for your care, I have solve this problem!

**Comment by jcb91** [comment]
Glad to hear you got it sorted :smile:
