### ISSUE TITLE
nbextensions in the news

### ISSUE THREAD

**Issue by juhasch** [ipython-contrib/jupyter_contrib_nbextensions#1076]
A fun issue :smile:

@jcb91 's collapsible headings extensions praised at JupyterCon:
https://youtu.be/frc7FgheUj4?t=14m49s

And the [Pynq](http://www.pynq.io) FPGA board running Python uses Jupyter notebook and has nbextensions installed by default: [Screenshot](http://pynq.readthedocs.io/en/latest/_images/example_notebooks.jpg)

**Comment by jcb91** [comment]
Ah neat! Thanks for the heads-up :)
