### ISSUE TITLE
Cannot install the extensions

### ISSUE THREAD

**Issue by AlanStark** [ipython-contrib/jupyter_contrib_nbextensions#1093]
When I run this command "conda install -c conda-forge jupyter_contrib_nbextensions", it shows up lots of stuff in my terminal. It said "Cannot configure while the Jupyter notebook server is running", 
"ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::jupyter_contrib_nbextensions-0.3.1-py36_0'.
LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.3.1-py36_0". 

However I do not run the Jupyter notebook server.

**Comment by AlanStark** [comment]
I fix it with pip install.

**Comment by jcb91** [comment]
for future reference, see also #1090
