### ISSUE TITLE
EXT: TOC title customization

### ISSUE THREAD

**Issue by jankoslavic** [ipython-contrib/jupyter_contrib_nbextensions#1098]
I use this extension a lot and it is great! I am trying to replace the "Table of Contents" text with a text that would match the language of the text. Having an English title while the rest of the document is not English does not look nice:)

**Comment by jcb91** [comment]
sounds like a good plan :+1:

**Comment by jcb91** [comment]
However, currently the cell toc & sidebar toc use different titles, which is a slight complication. Should we

 1. use the same (configurable) title for both, set per-notebook
 2.  make the cell's title configurable per-notebook, and the sidebar configurable globally (assuming it to be part of the ui, rather than the document)
 3. make only the Cell's title configurable (per-notebook), and keep the existing sidebar title

Any thoughts?

**Comment by jankoslavic** [comment]
Thanks @jcb91 for the proposals. I guess this should be document setting (I have some documents in English, some in other languages)... The notebook metadata looks very good for this... adding a two new fields "toc_title" and "toc_sidebar_title" with the default "Table of Contents" and "Contents", respectively, would do the job.

**Comment by jfbercher** [comment]
Yes, these are good ideas which are not difficult to implement. 

Given the increasing number of parameters that can be changed per notebook, I am thinking to implement some king of "preferences or configuration window".

**Comment by jcb91** [comment]
> Given the increasing number of parameters that can be changed per notebook, I am thinking to implement some king of "preferences or configuration window".

Haha, I've just been thinking about the same thing!

Was considering using the dialog module, but I think that's unavailable in non-live notebooks...

**Comment by jfbercher** [comment]
Ok. so it means that we have to do it! :+1: 

I have implemented a configuration bar in `latex_envs` and `nbTranslate` but it is a bit complicated. Perhaps that just a floating window (like in `varInspector`) with a list of checkboxes and textfields and the relevant events would do the trick.

**Comment by jcb91** [comment]
see #1124 for proposed implementation
