### ISSUE TITLE
Jupyter 5.1 changes add_buttons_group

### ISSUE THREAD

**Issue by Sukneet** [ipython-contrib/jupyter_contrib_nbextensions#1102]
Juypter commit https://github.com/jupyter/notebook/commit/af244a63b82c03d01783d29d0f821d1dcade8709 adds an html span with the label value when calling add_buttons_group. This causes a long name in the toolbar for a lot of extensions. For example, the freeze extension:

![image](https://user-images.githubusercontent.com/359625/30615813-5890d810-9d4d-11e7-981e-0c0f5c77f3cd.png)

**Comment by jcb91** [comment]
D'oh!

**Comment by Sukneet** [comment]
The following seems to work
https://github.com/Sukneet/jupyter_contrib_nbextensions/commit/1547b3e9a5e38329dbbc2b06f07ac6b2f5a964e2

Is the style ok?

**Comment by jcb91** [comment]
Looks good to me, and the actions have the added bonus that they can be used in the command palette :)

**Comment by jcb91** [comment]
Opened a PR #1103. There are quite a few other nbextensions that will need similar updates, though. Thanks @Sukneet for reporting & fixing freeze 😄 🙇

**Comment by Sukneet** [comment]
I fixed the other ones last night. Just need to verify they are all working.

**Comment by juhasch** [comment]
Thanks for working on this. I am updating n the `runtools` extension and fixed it there already.

**Comment by Sukneet** [comment]
I think I got them all (except runtools)
https://github.com/Sukneet/jupyter_contrib_nbextensions/commit/b7aa1bd8160cd132c0e8ff877d5c0515b67a2df9

**Comment by takluyver** [comment]
Sorry for this - I thought I had been more careful in making the change than I actually was. Thanks for working on adapting jupyter_contrib_nbextensions to deal with this change.

Once PR #1103 has cleared up the problematically long labels, I hope that some nbextensions will be able to make judicious use of shorter labels on the buttons to make their purpose clearer. E.g. this code in cite2c:

https://github.com/takluyver/cite2c/blob/f310fb00af829664c756404c343d948ab556a2e0/cite2c/nbext/main.js#L296-L302

Produces buttons like this:

![screenshot from 2017-10-05 11-30-15](https://user-images.githubusercontent.com/327925/31222954-c13ebf60-a9c0-11e7-9a41-08cbaf4964f5.png)

**Comment by jcb91** [comment]
Ok,this should be fixed by #1103 & #1123. As @takluyver notes, though, it might be a good idea to add labels to some of our more ambiguous buttons. We _could_ even make the button labels configurable :rofl:

**Comment by kenptr** [comment]
![screen shot 2018-03-14 at 12 20 14 am](https://user-images.githubusercontent.com/37238242/37388396-8b653dee-271d-11e8-9804-75a518b675c7.png)

`2to3` and `code_prettify` still have long labels.
