### ISSUE TITLE
[ToC2] dose not work.

### ISSUE THREAD

**Issue by senkohei** [ipython-contrib/jupyter_contrib_nbextensions#1127]
Even if ToC 2 of Configurable NBextensions is checked and set to enable, no icon appears in notebook's toolbar.

Please let me know if you know the cause and the solution.

Environment:
Windows 10 (64bit)
Python3.6.1 Anaconda3 4.4.0 (64-bit)

**Comment by jcb91** [comment]
what notebook version are you running?
I have found an issue with notebook < 5.1.0, which prevents toolbar buttons being created if we're specifying id & action, related to #1123

**Comment by senkohei** [comment]
I put version information.

jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-contrib-core (0.3.3)
jupyter-contrib-nbextensions (0.3.2)
jupyter-core (4.3.0)
jupyter-highlight-selected-word (0.0.11)
jupyter-latex-envs (1.3.8.4)
jupyter-nbextensions-configurator (0.2.8)

**Comment by jcb91** [comment]
ok, I'm after the output of

    jupyter notebook --version

**Comment by jcb91** [comment]
anyway, see #1128 for a potential fix

**Comment by senkohei** [comment]
ok.

My output is "5.0.0" .

**Comment by jcb91** [comment]
thanks. I'm reasonably sure that you're seeing one of the bugs I managed to introduce in #1123 :disappointed:

**Comment by senkohei** [comment]
ok.

I will wait for # 1128 to be merged.
What should I do after merged ?

**Comment by jcb91** [comment]
Right, #1128 is merged, so you can now [reinstall from the repo master](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/db25dcc77d7744746033b9c709d1215aebb1a6f0/README.md#pip), apply the fix manually, or wait for a new pip/conda release...

**Comment by senkohei** [comment]
Thanks.
I tried to apply the fix manually.
It succeeded.

The toolbar icon of ToC2 came out.
I appreciate it!

**Comment by vikramsjn** [comment]
Hi,
I just installed nbextensions using this command bu toc2 is not working
how can I fix this?

**Comment by jcb91** [comment]
@vikramsjn, unfortunately I'm still waiting on Travis to build [the PR for the 0.3.3 conda-forge package](https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock/pull/23) so for now the conda-forge package is still the buggy one. My previous suggestion still stands, to [reinstall from the repo master](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/db25dcc77d7744746033b9c709d1215aebb1a6f0/README.md#pip), or now that 0.3.3 (which has the relevant fix) is on pypi, you can upgrade using pip

    pip install --upgrade jupyter_contrib_nbextensions

for now, until the conda package gets an upgraded release

**Comment by vikramsjn** [comment]
@jcb91 
I do not have much experience with pip and conda

So Is it ok to use this pip command when I installed nbextensions using conda ?
`pip install --upgrade jupyter_contrib_nbextensions`

when I installed nbextensions  using conda

**Comment by jcb91** [comment]
@vikramsjn yes, this is perfectly safe to do over the top of a conda install, but I forgot earlier that two steps are needed. To apply over the top of a conda install, use (with the relevant conda environment active)

    pip install --upgrade jupyter_contrib_nbextensions
    jupyter contrib nbextension install --sys-prefix

You may wish to add a `--symlink` flag to the second command (if you're not on Windows, which doesn't support symlinks). In the conda package, this second command is done automatically. Once the newer conda package becomes available, you should be able to go back to that (over the pip) just by doing

    conda upgrade jupyter_contrib_nbextensions

**Comment by vikramsjn** [comment]
@jcb91 
I did your prescribed steps - and now toc2 is working alright.
Thanks a lot, and for also the detailed steps

**Comment by jcb91** [comment]
@vikramsjn you're welcome, glad to hear you got it fixed ok :)
I've just merged the [pr to update the conda repo](https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock/pull/23), so builds for 0.3.3 should hopefully get uploaded to the conda-forge channel soon once the various CI systems build them. As mentioned previously, you should be able to go back to using the conda package (as opposed to the pypi/pip one) using

    conda upgrade jupyter_contrib_nbextensions

But there isn't really any great need to for the moment, since you've now got 0.3.3 installed anyway :)

**Comment by jcb91** [comment]
closing this as fixed by the latest (0.3.3) version
