### ISSUE TITLE
Solve Contrib Not Found Error (Jupyter contrib)

### ISSUE THREAD

**Issue by arbazkiraak** [ipython-contrib/jupyter_contrib_nbextensions#1152]
> JUPYTER CONTRIB :+1: 

for [contrib] Not found  Error

You can install it from here: (Directly)
pip install https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/tarball/master

**Comment by jcb91** [comment]
@arbazkiraak  I'm not really sure what you mean by any of this - do you mean you managed to somehow install the contrib repo *without* the configurator? Could you clarify a bit?

**Comment by jcb91** [comment]
ah, unless you mean that running

    jupyter contrib

gave you an error?

**Comment by jcb91** [comment]
closing this for want of more info. Feel free to reopen, but please add a little more explanation of what the problem is/was (what you did, what you expected to happen, what actually happened), along with versions of notebook & jupyter_contrib_nbextensions.
