### ISSUE TITLE
slidemode shows hidden cells when navigating backwards

### ISSUE THREAD

**Issue by akaihola** [ipython-contrib/jupyter_contrib_nbextensions#116]
When I run forward in a presentation using the "Next" button or the right arrow key, cells marked as "Notes" or "Skip" using the "Slide Type" cell toolbar are not shown.

But when I run backward using the left arrow key and cross a slide boundary, the whole previous slide is shown, _including_ notes and skipped cells.

**Comment by juhasch** [comment]
Slidemode extension has been removed. Check out https://github.com/damianavila/RISE
