### ISSUE TITLE
Splitting cells breaks collapsible headings

### ISSUE THREAD

**Issue by mrgutkun** [ipython-contrib/jupyter_contrib_nbextensions#1164]
Given two header cells, first collapsed (with section under it hidden), and second immediately following the hidden section, splitting the second with `Ctrl+Shift+Minus` hides it and its whole section.
Reloading the notebook or editing and executing any Markdown cell unhides them as is proper, but having a whole section disappear without a trace is unsettling.

**Comment by jcb91** [comment]
>  having a whole section disappear without a trace is unsettling

Absolutely, this isn't really acceptable behaviour. The reason it happens is that headings don't get reconsidered on calling `cell.set_text`, but on a bunch of other occurrences. I think this has caused similar problems before, so it probably makes sense to patch the `MarkdownCell.set_text` method directly...
