### ISSUE TITLE
Extension config saved to user config dir after --sys-prefix install

### ISSUE THREAD

**Issue by bhrutledge** [ipython-contrib/jupyter_contrib_nbextensions#1170]
I run `jupyter notebook` in a virtual environment, so I used `jupyter contrib nbextension install --sys-prefix`. However, when I enable/configure extensions, I see that reflected in `$HOME/.jupyter/nbconfig/notebook.json`, when I would expect/prefer it to be in `$VIRTUAL_ENV/etc/jupyter/nbconfig/notebook.json`. I think this behavior would cause an error if I ran Jupyter in a different virtual environment that didn't have this extension installed.

**Comment by juhasch** [comment]
Configuration files are handled by the notebook server itself. Try `jupyter --path` to see where your config data gets stored.

The [Documentation](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html) states `Config files are stored by default in the ~/.jupyter directory.`

**Comment by jcb91** [comment]
I see what you mean @bhrutledge, this does make sense as a use-case. Unfortunately, as @juhasch points out, the configurator (which has its own separate repo at [https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator)) currently relies on using the notebook's config API, which adopts a read-from-all write-to-user model. This makes sense if you think of the configs as hierarchical with the sys-prefix being subservient to the user config. This sort of made sense if using one python environment for several users, but many (most?!) users are (rightly, imo) now using virtual environments, for which the sys-prefix should be subservient to the user config. I think perhaps the best way to address this might be a PR to notebook, to do one or both of:

* allow requests to the config API to choose which config to write to
* add a notebook server configurable to allow setting the sys-prefix as the one for the config API to edit

**Comment by jcb91** [comment]
On second thoughts, simplest might be an environment variable you could set to make `jupyter_core.paths` place the sys-prefix before the user config directory. Not sure.

Anyway, in the mean time, you can use the following python snippet (from your notebook server's python env) to edit your sys-prefix notebook config file to ensure that your notebook server's config manager will write to the sys-prefix config rather than the user one:

```python
import os

from jupyter_core.paths import ENV_CONFIG_PATH, jupyter_config_dir
from traitlets.config.manager import BaseJSONConfigManager

cfg_name = 'jupyter_notebook_config'
usr_config_dir = jupyter_config_dir()
env_config_dir = ENV_CONFIG_PATH[0]

usr_cm = BaseJSONConfigManager(config_dir=env_config_dir)
# record existing user config content
usr_cfg = usr_cm.get(cfg_name)
# remove the user config to prevent it overriding env
if os.path.exists (user_cm.file_name(cfg_name)):
    os.remove(user_cm.file_name(cfg_name))
# now write env config
env_cm = BaseJSONConfigManager(config_dir=env_config_dir)
# first anything we read from user config:
env_cm.update(cfg_name, usr_cfg)
# now ensure notebook's config API writes to env config:
env_cm.update(cfg_name, {'ConfigManager': {'write_config_dir':
    os.path.join(env_config_dir, 'nbconfig')
}})
```

Note that this also removes your user config, having written its values into the env one, as otherwise the config API will still read from user config, and use its values _over_ those set in the env config :/

**Comment by jcb91** [comment]
(oops, python snippet edited)

**Comment by bhrutledge** [comment]
Thanks for the detailed responses! I'm getting the sense that Jupyter is really meant to be installed once per user/system, similar to other command line apps, regardless of whether that's directly into a Python distribution, or in a dedicated virtual environment. Hence, defaulting to the user config makes sense. I might see if I can get clarification on that point from the Jupyter project.

**Comment by jcb91** [comment]
> I'm getting the sense that Jupyter is really meant to be installed once per user/system, similar to other command line apps, regardless of whether that's directly into a Python distribution, or in a dedicated virtual environment

Yeah, that's kinda how the notebook environment is for the moment. I think the assumption is generally that you have a single (possibly virtual) env for the notebook _server_, with (potentially) other separate environments for _kernels_ (which may of course not even be python). For example, I find [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) handy for providing separate kernels for each conda environment.

**Comment by bhrutledge** [comment]
Yeah, I've seen that repo. FWIW, I've been maintaining my personal notebook server setup, along with general instructions for running Jupyter in a venv, at https://github.com/bhrutledge/jupyter-venv.
