### ISSUE TITLE
[ScrollDown] Not working, possible compatibility issue.

### ISSUE THREAD

**Issue by hermesribeiro** [ipython-contrib/jupyter_contrib_nbextensions#1171]
Dear all, ScrollDown and it is marked as incompatible (using 5.0.0). Tried using it without compatibility anyways and it is not working. I am using Jupyter on Anaconda for windows 10, chrome browser. Thanks for the attention.

**Comment by jcb91** [comment]
Thanks for the report @hermesribeiro. It appears the relevant event was renamed in
https://github.com/jupyter/notebook/commit/b4928d481abd9f7cd996fd4b24078a55880d21e6 to avoid it bubbling up the DOM. I've submitted a PR to fix this, along with a couple of other issues: #1181
