### ISSUE TITLE
Problem with creating table of content

### ISSUE THREAD

**Issue by anya2go** [ipython-contrib/jupyter_contrib_nbextensions#1173]
Hi,
I've installed and enabled the table of content(2) But when I try to create it, instead of being a floating table, it covers all the window. 
Tried to change the configuration, didn't help much. (checked both on chrome and explorer)

Python 3.6.3, Jupyter Notebook 5.0.0 

Thanks!

![toc2](https://user-images.githubusercontent.com/22053429/34052764-c1a5a622-e191-11e7-92b2-22a0fea8c5ed.png)

**Comment by jfbercher** [comment]
Don't really kwow what happens, but
a. Does this happens with a *new* notebook? 
b. if it is an existing notebook, open edit/Edit Notebook metadata and delete the toc2 section and everything related to toc, then save and reload the page
c. from the screenshot, it looks like you use an old version. please try to upgrade.

**Comment by jfbercher** [comment]
Any news on that?

**Comment by anya2go** [comment]
Worked after reinstalling anaconda. Thanks!
