### ISSUE TITLE
toc2 unable to save as HTML (with toc)

### ISSUE THREAD

**Issue by cqcn1991** [ipython-contrib/jupyter_contrib_nbextensions#1176]
When I click this link, nothing happens. I want to know, what went wrong?

![default](https://user-images.githubusercontent.com/2425141/34093771-19ba9992-e405-11e7-86b0-5c4c2acaed12.png)

**Comment by jfbercher** [comment]
You should have a log similar to 
`
[toc2] running: !jupyter nbconvert 'Visu_n.ipynb' --template toc2
`
in your console and find the converted file in the same directory as the notebook. 
Just checked and this still works. 

This "Save as HTML (with toc)" could/should be rewritten to take advantage of the new api entry which enable to call nbconvert with a template as an option of the "download as" menu (for Jupyter v. 5.1). I may have the time to do it shortly.

**Comment by cqcn1991** [comment]
Got it, so it seems I can also run `jupyter nbconvert 'Visu_n.ipynb' --template toc2` manually through cmd?

**Comment by jfbercher** [comment]
Yes indeed. 
Change the filename of course! (quotes only needed if there are spaces in the filename)

**Comment by jfbercher** [comment]
From the command line, you can also issue 
```
jupyter nbconvert --to html_toc FILE.ipynb
```

**Comment by jfbercher** [comment]
Explanations provided. 
Furthermore a new possibility "Download as HTML with toc" was added for Jupyter >= 5.1, cf #1182  Closing this issue.
