### ISSUE TITLE
@json_errors deprecated in notebook 5.2.0

### ISSUE THREAD

**Issue by jakirkham** [ipython-contrib/jupyter_contrib_nbextensions#1177]
Sorry in advance if this is duplicate and/or already resolved. Saw the following warning when using `jupyter_contrib_nbextensions` version `0.3.3`.

```python
/opt/conda/lib/python3.6/site-packages/jupyter_nbextensions_configurator/__init__.py:168: DeprecationWarning: @json_errors is deprecated in notebook 5.2.0. Subclass APIHandler instead.
```

**Comment by juhasch** [comment]
Thanks for the notice. Fortunately, @jcb91 already fixed this in master: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/52

Probably time to make a new release soon.

**Comment by jakirkham** [comment]
Ah ok. Thanks. Sorry for the noise. Somehow didn't find that when searching the tracker.

**Comment by juhasch** [comment]
No worries. It's another repository, so it is hard to find unless you know.

**Comment by jakirkham** [comment]
So is this repo being deprecated in favor of that one then?

**Comment by juhasch** [comment]
No, we just split the configuration part (a notebook server extension) into it's own package. The notebook frontend extensions will remain here.

**Comment by jakirkham** [comment]
Ok, got it. Thanks.
