### ISSUE TITLE
Building a notebook extension that allows to register other cells as its execution dependencies

### ISSUE THREAD

**Issue by benelot** [ipython-contrib/jupyter_contrib_nbextensions#1193]
Hello everyone,

I am thinking about writing an extension that allows for each cell to be annotated with cells on which its execution depends on. Working in a modular fashion could be simplified because it would allow to write short code segments that need to be run as initialization for others. For example, I can write a dataset download and extract section, which is then set as a dependency for a graph drawing cell. If I run the graph drawing cell, the dependent cells will be run before it to ensure its successful execution.

Can anybody give me some hints on where to start (what part of the doc I should read, not even sure if this is a front-end or back-end extension maybe both?) and how this could be done (as rough pseudocode like "you catch the event notification of the cell to be run and trigger all cells that are in its json tag called deps. The deps you can collect for each cell by inserting deps as special tags").

**Comment by juhasch** [comment]
From the technical side this should not be too difficult to implement. You can take look at the runtools extensions for example, where you can mark cells and execute them.

It is not difficult to programmatically execute a given cell, or modify the execution behavior. This can be done using a custom execution command (called from a hotkey, menu entry or button), or you can change to logic by catching events, or overwriting the default execution function, implementing your own logic. Unfortunately there is no "official" API. Best start by looking at existing extensions in this or other repositories.

I think the more difficult part is to create a user interface that allows doing what you want in an intuitive and comprehensible manner. You might want to look at cell tags. You can add self-defined tags to a cell. Executing cells with this tag is a simple for loop.

**Comment by benelot** [comment]
I think I would directly use the UI for the tags to represent the dependencies. Something like #A for the id and =>B for the dependency could be a simple representation of the dependency graph. Thanks for the hints, that is EXACTLY the kind of help I hoped for. I will keep you posted on the progress.

**Comment by jcb91** [comment]
> Something like #A for the id and =>B for the dependency could be a simple representation of the dependency graph.

Ah yes, good plan! Nice, neat idea, and simple to implement :)
