### ISSUE TITLE
[Python-Markdown] Float Precission?

### ISSUE THREAD

**Issue by waio1990** [ipython-contrib/jupyter_contrib_nbextensions#1209]
Hi, is there a way to configure decimal precission when using this extension? My float values output with several decimals and no thousand separator, and the whole point is to have more reader friendly output from python, right?

Thanks

**Comment by jcb91** [comment]
python-markdown will simply insert whatever string representation the enclosed code's return value has, so your formatting needs to be done on the kernel side of things.

For precision alone, you could use [the ipython `%precision` magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-precision).

For more general control, including thousands separators, you might consider the python [format specification mini-language](https://docs.python.org/3/library/string.html#format-specification-mini-language), e.g.

```python console
In [1]: '{:,.1f}'.format(3.141592653589793 * 1e8)
Out[1]: '314,159,265.4'
```

**Comment by waio1990** [comment]
awesome, thanks!
