### ISSUE TITLE
Porting some extensions from colab to this repository

### ISSUE THREAD

**Issue by benelot** [ipython-contrib/jupyter_contrib_nbextensions#1215]
There seem to be nicely separable extensions from colab that do not look like they could not work here too.
Maybe it could be a good idea to port them to this repository?

[Colab extensions folder](https://github.com/Calysto/notebook-extensions/tree/master/calysto)

**Comment by jcb91** [comment]
Not sure where you got the name "colab"? Unless it's an autocorrect of Calysto? Anyway.

I think for the spellchecker in this repo I used inspiration from Calysto's already (or perhaps from something which later became [Calysto](https://github.com/Calysto/notebook-extensions), I forget the details). Some things there are a little dated now ([checking for 2.x versions in some cases](https://github.com/Calysto/notebook-extensions/blob/2279a24266af2c17059a40b59ba3e442d412f313/calysto/document-tools/main.js#L18)!) so might need updating, and others are a bit specific to brynmawr's setup to be likely to be useful more widely (e.g. the [submit](https://github.com/Calysto/notebook-extensions/tree/5cbb49a097d96a82c6fb165858a37b766aa381c5/calysto/submit) one), but sure, anything you think might be appropriate to include, and that the folks at [Calysto](https://github.com/Calysto/notebook-extensions) are ok with having ported here (i.e. please ask them as well as asking here, don't want annoy anyone unnecessarily :smile:), I've no real objections :+1:

**Comment by juhasch** [comment]
I would like to add that it is important that the extension author agrees to moving the extensions here, and also agrees to be present here in case of upcoming issues.
Adding extensions is only of little benefit on it's own, and just adding extensions that are basically unmaintained will increase the workload of those who take care of this repo, like @jcb91 .

**Comment by benelot** [comment]
You are right, I somehow mistook the repository for the one that maintains the colab extensions. Never mind!
