### ISSUE TITLE
How to get login user name

### ISSUE THREAD

**Issue by hemantasingh** [ipython-contrib/jupyter_contrib_nbextensions#1216]
I'm trying to get user_name [login user] in my extension. Could you please guide me how to get it ?
One way i'm get it by execute below, but I don't think it is the right way.  
 
```javascript
kernel.execute("import getpass; username=getpass.getuser()");
```

Can someone please guide, what would be the best way and also please let me know if any api for nbextensions . Thanks

**Comment by jcb91** [comment]
I don't know of any API to do this. The process you outline will only work for a python kernel. At any rate, I guess it's even possible that the user running the notebook server might be different to the user running the kernel (it may even be on a different machine, depending on the spawner). What are you aiming to do with the username once you have it?

**Comment by hemantasingh** [comment]
I need to invoke a REST service, where I'm implementing a GIT connector REST service for our JupyterHub environment.

**Comment by jcb91** [comment]
> I need to invoke a REST service, where I'm implementing a GIT connector REST service for our JupyterHub environment.

:worried: not sure I quite follow. So you seem to be expecting the local username to be the correct username to be using as part of your call to some REST API? Given you're using jupyterhub, would you perhaps find it easier to parse the username out from the page URL?

**Comment by hemantasingh** [comment]
Yes, It could be local username, but the best for me is the login user_name. I 'm not sure how to get the user login information like from session.
Parsing the username from the page URL is also a good option, thanks let me check it how to get it.

**Comment by hemantasingh** [comment]
I'm closing this issue, thanks Josh.
Now I'm getting the user_id info from 
"Python.notebook.base_url"
