### ISSUE TITLE
Remove the wiki?

### ISSUE THREAD

**Issue by jcb91** [ipython-contrib/jupyter_contrib_nbextensions#1218]
The wiki isn't used very much (basically the only meaningful edits in the last year have @benelot's in the last couple of days), and largely refers to things which don't exist any more, outdated things, or has outdated information. As a result, it's confusing, and I think mainly serves as a distraction from actual helpful stuff in the main repo, or at readthedocs. Maybe it's time to just get rid of the remainder of it? @juhasch @jfbercher thoughts?

**Comment by juhasch** [comment]
I agree, I think we can remove the Wiki. It is from a time when we did not have any meaningful documentation with the extensions.

**Comment by jfbercher** [comment]
+1

**Comment by benelot** [comment]
I would recommend to add a contributing.md to the repository. I think this could make contributions a lot easier. If you want, you can take my contributions wiki page as some insights from how I could quickly turn my extension to a viable contribution.

**Comment by jcb91** [comment]
ok, contributing page added, wiki removed, closing this
