### ISSUE TITLE
[splitcell] Copy-Pasting cells, not rendered until refresh

### ISSUE THREAD

**Issue by consideRatio** [ipython-contrib/jupyter_contrib_nbextensions#1235]
It seems that if you copy and paste cells that are split, they pasted copies will not render as split cells until you refresh the page or remove/apply the metadata again using the button.

Is this fixable in an elegant way perhaps? I imagine it might not be though, then we could close this issue.

**Comment by jcb91** [comment]
This is a relatively common problem for copy/paste of cells, or from using un-delete cells. Both use `fromJSON` to construct the cell, but do it _after_ the cell is created, so after any handlers bound to the `create.cell` event. Imo it might be helpful to have a fromJSON event for such cases...

**Comment by consideRatio** [comment]
Closing due to my own inactivity to followup!
