### ISSUE TITLE
ES6 instead of requirejs

### ISSUE THREAD

**Issue by jog39** [ipython-contrib/jupyter_contrib_nbextensions#1260]
Hi,
I am currently trying to write an extension for the notebook, being a Vue.js app alongside the notebook providing me a full interface (with commands, widgets, etc.). 

I am struggling with the fact that the notebook loads extensions with an AMD loader but Vue.js doesn't work well with that. 

Is there any other way to declare and install a notebook extension? Something different than

`return {load_ipython_extension: load_ipython_extension}` 

and more like 

`export default function load_ipython_extension() {}`

I'm a bit confused (sorry if it's not really clear).

**Comment by jcb91** [comment]
So essentially the notebook uses requirejs to load its modules. For the main notebook, these are compiled and minified by the requirejs optimizer, while for nbextensions, they're loaded in the browser by requirejs. So, you're looking for some kind of adapt pattern. 

I'm assuming you're running some kind of build step (something like `babel` or webpack`?) to transpile your ES6 to browser-compatible javascript?. Using something like 

```javascript
function load_ipython_extension () { console.log('my fabulous nbextension'); }
export { load_ipython_extension };
```

will transpile to

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
function load_ipython_extension() {
  console.log("my fabulous nbextension");
}
exports.load_ipython_extension = load_ipython_extension;
```

the use of exports is more akin to the commonJS module format, for which require has [some notes](http://requirejs.org/docs/commonjs.html). Essentially, given the use of `exports`, the whole module can probably be manually wrapped in a requirejs `define` call as mentioned in http://requirejs.org/docs/commonjs.html#manualconversion:

```javascript
define(function(require, exports, module) {
  "use strict";

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  function load_ipython_extension() {
    console.log("my fabulous nbextension");
  }
  exports.load_ipython_extension = load_ipython_extension;        
});
```

Alternatively, you could maybe use something like https://babeljs.io/docs/plugins/transform-es2015-modules-amd/ to get babel to transpile directly to AMD format.

Does any of that make sense/help?

**Comment by jog39** [comment]
Thank you, it helped a bit. 
I have tried a lot of things, but it didn't work out, as .vue files aren't compliant with require.js. 
It seems my issue is more related with the choice of a JS framework that would indeed work with requirejs. 

If you have any thoughts on this I would gladly hear them, otherwise feel free to close, thank you.

**Comment by jcb91** [comment]
> as .vue files aren't compliant with require.js

Not directly, but through a transpiling step this should be possible, I would guess (thought don't have much exposure to vue, so don't know details). 

If you're looking for a framework to use, you might want to consider [preact](https://preactjs.com/) over react (same API, preact is smaller), since it's already [included in the notebook page template](https://github.com/jupyter/notebook/blob/4285574b96159d19fab83c96f0b7f43f95d893a3/notebook/templates/page.html#L19) since notebook 5.0.0.

**Comment by jog39** [comment]
I managed to make it work with React, Webpack and Babel in the end, thanks for the help @jcb91 !
