### ISSUE TITLE
Installing the extensions breaks the installation of conda

### ISSUE THREAD

**Issue by drorata** [ipython-contrib/jupyter_contrib_nbextensions#1267]
*Steps to reproduce:*

1. Install fresh Anaconda `Anaconda3-5.1.0-MacOSX-x86_64.sh`
2. After installation, run `conda update -n base conda` to update to `4.4.11`.
3. Install the extensions using: `conda install -c conda-forge jupyter_contrib_nbextensions`

At the end of step (3), the `conda` command is no longer available.

*Workaround:*

Swapping the order of steps (2) and (3) seems to solve the problem.

This is a very painful and broke my conda installation.

**Comment by jcb91** [comment]
> This is a very painful and broke my conda installation.

Wow, this sounds bad :worried:

However, my guess is that it's more likely an issue with either conda-forge's recipe building, or maybe the conda update itself (since the recipe shouldn't touch any conda command at all). I'm going to open this as an issue on this repo's conda-forge recipe repo, which is presumably where any fix (if possible) should be applied.

@drorata did you see any error/warning logs at any point in this? Could you check the contents of `$PREFIX/.messsages.txt`? (see the end of https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html for details)

**Comment by drorata** [comment]
I can add a little data. When installing the extensions AFTER the update of `conda` the plan was downgrading `conda` back. At the end of the installation, there was an error that `conda` was not found anymore.

@jcb91 Do you mean `~/Anaconda/.messages.txt`? I don't think I had this file. I will try to reproduce this in a docker container. I think it should be easy to reproduce.

**Comment by drorata** [comment]
Start a docker container with Ubuntu:

```bash
apt-get update
apt-get install wget bzip2
wget https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
bash Anaconda3-5.1.0-Linux-x86_64.sh
conda update -n base conda
```

At this point run `conda install -c conda-forge jupyter_contrib_nbextensions` and note the following line in the plan:

```
The following packages will be DOWNGRADED:

    conda:                             4.4.11-py36_0                     --> 4.3.34-py36_0         conda-forge
```

At the end of this process, there was no problem with `conda`. I guess it has to do with macOS in this case. Can someone confirm this?

**Comment by dougalsutherland** [comment]
For anyone else who finds this: this is a short-term issue with conda-forge and downgrades of `conda`, and has nothing to do with `jupyter_contrib_nbextensions` in particular. Luckily, it doesn't actually break anything about the installation, just the shell wrapper to use it: there's a workaround at the end of https://github.com/conda-forge/conda-feedstock/issues/43#comment-375152359 until we can get this fixed.

**Comment by jcb91** [comment]
Thanks @dougalsutherland, that's really useful to know!
