### ISSUE TITLE
collapsible headings spontaneously uncollapse

### ISSUE THREAD

**Issue by darthoctopus** [ipython-contrib/jupyter_contrib_nbextensions#1274]
When cells are collapsed, adding extra cells/converting existing code cells to markdown cells will spontaneously cause some cells to uncollapse

**Comment by jcb91** [comment]
Thanks for the report. Could you provide a set of steps to reproduce this? I'm thinking of details like which cell is selected when you take actions like adding new cells/converting to markdown, where they're added (above, below the collapsed section), this kind of thing...

**Comment by darthoctopus** [comment]
Here's a minimum working example: <http://hyad.es/sendfile/payloads/Untitled1.ipynb>

The first cell is collapsed, but doing anything downstream (adding a new cell, or changing the type of the last cell) will cause it to appear without changing the state of the collapsed/uncollapsed indicator. For more complicated configurations this happens at random with the innermost collapsed level.

**Comment by jcb91** [comment]
Thanks @darthoctopus. Sounds non-trivial, I'll see if I can track it down...

**Comment by jcb91** [comment]
> The first cell is collapsed, but doing anything downstream (adding a new cell, or changing the type of the last cell) will cause it to appear without changing the state of the collapsed/uncollapsed indicator. 

Hmm, for me (using Chrome 65.0.3325.18 on Ubuntu 16.04), this isn't reproducible, it seems to work as expected. What browser/OS combinations do you use/have you tried?

**Comment by darthoctopus** [comment]
I've spent the whole day investigating this and it's been driving me nuts. seems like it's not playing nice with one of my browser add-ons but I can't pinpoint which one. I'll mark this closed for now.
