### ISSUE TITLE
Documentation - Cell Init Readme doesn't mention how to enable cell toolbars

### ISSUE THREAD

**Issue by mfosker** [ipython-contrib/jupyter_contrib_nbextensions#1287]
No doubt an experienced notebook user would know that you have to go to the view menu to enable the cell toolbar before the initialization cell checkbox appears for the cell_init extension. But I didn't know that.
Happy to submit a pull request with a tiny documentation change that shows how to do this.

**Comment by jcb91** [comment]
> Happy to submit a pull request with a tiny documentation change that shows how to do this.

That'd be much appreciated, thanks @mfosker

**Comment by mfosker** [comment]
Have done that now, @jcb91

**Comment by PaulSzymanski** [comment]
#1291 checks failed for some reason
