### ISSUE TITLE
Variable Inspector -shape of variable field

### ISSUE THREAD

**Issue by homofortis** [ipython-contrib/jupyter_contrib_nbextensions#1303]
Presently, the really useful information about the variables in Variable Inspector are the name and the type fields. The size (in bytes) and value (not formatted and squashed into a narrow field space) don't give you much of insight for variables. 
Wouldn't it be more useful to have a field for the shape of variable instead of the size in bytes field, or in addition to it?

**Comment by jfbercher** [comment]
I think that this should be already present (added in #1237). Check if you have the last version. 

![capture du 2018-06-06 14-36-40](https://user-images.githubusercontent.com/7596356/41038712-6eded9e8-6997-11e8-854f-c26416fb31cd.png)

**Comment by homofortis** [comment]
I've installed the latest version as suggested but still no luck.
`pip3 install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master`
Can it be browser related?  I'm running Safari on OS X High Sierra.
![screen shot 2018-06-06 at 16 56 38](https://user-images.githubusercontent.com/3680999/41042614-c8e98664-69aa-11e8-848b-7dcf46c10763.png)

**Comment by jfbercher** [comment]
Check that your `var_list.py` in the varInspector directory (explore the data dir reported by `jupyter --paths`) contains the `_getshapeof(x)`  and `var_dic_list`functions as in [L28-L44](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/varInspector/var_list.py#L28-L44) and `main.js`contains references to `varShape` as in [this file](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/varInspector/main.js#L133-L136). 

Perhaps have you several installs of nbextensions?

**Comment by homofortis** [comment]
@jfbercher Thank you very much for your help. 
The problem was in the javascript and CSS files installed for the local user. Apparently they don't update automatically with the package update. I had to run `jupyter contrib nbextension install --user` to update them. Now everything works fine.
