### ISSUE TITLE
These extension for jupyter lab?

### ISSUE THREAD

**Issue by M-Younus** [ipython-contrib/jupyter_contrib_nbextensions#1310]
Is there any way to use these extensions for jupyter lab,or any alternative?
Thanx

**Comment by jfbercher** [comment]
I suggest to report such features requests in [jupyterlab](https://github.com/jupyterlab/jupyterlab/issues). There are lot of API changes and the present extensions can't run on jupyterlab. 

In the jupyterlab [roadmap](https://github.com/jupyter/roadmap/blob/master/jupyterlab.md), there are plans to port poular extensions and build bridge layers. 

I personnaly do not have sufficient available time slots to (try to) port any of the nbextensions.
