### ISSUE TITLE
Python Markdown Rendering works in Jupyter Notebook but not in Jupyterlab

### ISSUE THREAD

**Issue by kannesito** [ipython-contrib/jupyter_contrib_nbextensions#1360]
Hello!

I wanted to make use of the Python Markdown feature, to render variables with {{ var }} ... so I went through the installation of the nbextensions, following the instructions given in https://github.com/ipython-contrib/jupyter_contrib_nbextensions

I also enabled it successfully, and it works in the classical Jupyter Notebook, but not in a Jupyterlab Notebook!
Python Markdown is enabled in localhost:8888/nbextensions

What can I do to make it work or is it not yet supported?
I appreciate your help, thanks :)

Regards,
Hannes

**Comment by kannesito** [comment]
And maybe in this context I just realized, that when trying to File->Download as->PDF via LaTeX (.pdf) all the Python Markdown-rendered values displayed in the notebook get lost :(
Any hints concerning this?

Thank you very much!

Hannes

**Comment by kannesito** [comment]
> And maybe in this context, for the classical Jupyter Notebook, I just realized, that when trying to File->Download as->PDF via LaTeX (.pdf) all the Python Markdown-rendered values displayed in the notebook get lost :(
> Any hints concerning this?
> 
> Thank you very much!
> 
> Hannes

Never mind! With `jupyter nbconvert file.ipynb [--to pdf]` it worked.

**Comment by lordflaron** [comment]
Hi,

I'm having the same issue. Is python markdown not implemented yet in jupyterlab or will it not be considered?

Thank you

**Comment by francescolosterzo** [comment]
Hi,

same here, I would be very interested in having this feature available in jupyter lab too!

Thanks!

**Comment by jasongrout** [comment]
One way you can get markdown rendered with variable substitutions is to do the variable substitution in python, and display the markdown with the display mechanism. For example, in python 3.7:

```python
from IPython.display import Markdown
x=10
Markdown(f"**variable**: {x}")
```

**Comment by diallobakary4** [comment]
@jasongrout Is it possible to directly create a Markdown cell with the content of: `Markdown(f"**variable**: {x}")` ?

**Comment by gusbemacbe** [comment]
It is two years and it's not implemented!
