### ISSUE TITLE
maintenance status of jupyter_contrib_nbextensions?

### ISSUE THREAD

**Issue by SteliosStefanatos** [ipython-contrib/jupyter_contrib_nbextensions#1366]
I am raising this "issue" in the hope of getting some response from the maintainers of `nbextensions` regarding the status and future of this repository. It has been 7 months since the last release - far longer than the previously longest interval between two successive releases - and there are no signs of activity. What is particularly concerning is that the recent `notebook` update (ver. 5.7) has made nbextensions (appear) incompatible and there seems to be little activity towards addressing this. 

Of course, I understand that the maintenance task is very time consuming and performed on a pure volunteering basis. I am sure I speak for everyone using (and enjoying) the extensions that your work is highly appreciated. Please consider establishing a donation mechanism so that we (the every day users) can support your hard work!

**Comment by juhasch** [comment]
Thank you for the positive feedback and your understanding. As you noticed, the updates are kind of slow currently.  I will do another release in the next few days and try to keep up with changes in the notebook. 

If someone wants to help out keeping the extensions up-to-date: you are welcome
Donations don't help me, unless you can bend time :smile:

**Comment by SteliosStefanatos** [comment]
@juhasch 

Thanks for the reply and working on an upcoming release! Your efforts are very much appreciated! It is great to see that the repository is not abandoned; the frequency of the updates is not that important.
