### ISSUE TITLE
\cite does not function properly when converting to HTML

### ISSUE THREAD

**Issue by axiom-of-joy** [ipython-contrib/jupyter_contrib_nbextensions#1377]
Using the LaTeX_envs toolbar extension, I have successfully added a .bib file and created a reference section in my Jupyter notebook. I have also successfully cited works in the bibliography using \cite. My Jupyter notebook looks like:

![in_notebook](https://user-images.githubusercontent.com/15664869/50072293-8d0b8300-0189-11e9-9335-73c5cfa0156d.png)

However, when converting to an HTML file using
```shell
jupyter nbconvert --template=nbextensions --to=html file_name.ipynb
```
the citations no longer appear as links in the resulting HTML. It instead appears as:

![in_html](https://user-images.githubusercontent.com/15664869/50072326-ad3b4200-0189-11e9-8591-ed6c5ee6a1a4.png)

**Comment by jfbercher** [comment]
Conversion to pure html does not include the latex_envs capabilities. Please use 
```
jupyter nbconvert --to latex_with_lenvs FILE.ipynb
```
see this [documentation](https://rawgit.com/jfbercher/jupyter_latex_envs/master/src/latex_envs/static/doc/latex_env_doc.html). It should work; this essentially embeds the latex_envs script in the html file.

**Comment by axiom-of-joy** [comment]
Thank you for the help.
