### ISSUE TITLE
code_prettify: option to disable js alert for unsupported kernels

### ISSUE THREAD

**Issue by kafonek** [ipython-contrib/jupyter_contrib_nbextensions#1386]
In [code_prettify/kernel_exec_on_cell.js](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/code_prettify/kernel_exec_on_cell.js), there is an alert pop-up when the extension is loaded in a notebook that is not Python, R, or javascript; afterwards, the icon and keyboard shortcut is removed.  The alert shows up even when the option for "show alerts for errors in the kernel prettifying calls" is turned off.

Could a nbextension parameter please be included to handle that situation more "quietly", removing the icon and keyboard shortcut while not generating a js alert? 

Thank you.

**Comment by jfbercher** [comment]
Fixed (in principle) by #1409
