### ISSUE TITLE
Notebook extension for dyslexic and visual accessibility

### ISSUE THREAD

**Issue by joshuazeltser** [ipython-contrib/jupyter_contrib_nbextensions#1426]
We are a team of MSc students from UCL working on the accessibility of Jupyter Notebooks. We are looking at creating some extensions which focus on accessibility for people with dyslexia or colour blindness. We are thinking of working on the following five extensions:

1. Text format toolbar - A toolbar which allows users to change the text size, colour, spacing etc. to make the text as readable/accessible as possible for users
2. Code spell checker - Live syntax checking of code as the user types underlining when a syntax error has occurred
3. Voice control - Allow some commonly used functionality such as running a notebook, restarting the kernel etc. be carried out using voice control
4. Planner - a planner that is displayed down the side of a page allowing the user to plan out and write notes about their notebook
5. Accessible themes - various themes such as high contrast which will make the notebook more easily readable

It would be great if anyone could give us some feedback about these ideas and whether they are feasible.

**Comment by fperez** [comment]
This is great to start discussing, but I'd like to encourage you to re-post this to [our accessibility repo](https://github.com/jupyter/accessibility) so we can find all accessibility-related high-level discussions in one place.  

As you'll see there, we are trying to rally also more open-ended discussion on Discourse, so we'll post there if/when we create a Discourse category for this topic to help raise visibility across the community.

**Comment by joshuazeltser** [comment]
I have reposted this here: https://github.com/jupyter/accessibility/issues/5

**Comment by fperez** [comment]
Thanks much @joshuazeltser! @Carreau can we close this (I can't)? We'll continue on accessibility.
