### ISSUE TITLE
Problem in loading the "2.x/usability/init_cell" extension

### ISSUE THREAD

**Issue by Hack-The-Paradise** [ipython-contrib/jupyter_contrib_nbextensions#143]
Hello, has anyone tried to use the:

https://github.com/ipython-contrib/IPython-notebook-extensions/tree/2.x/usability/init_cell ?

Because it seems really nice but for me it doesn't work, i mean i can see the check box but as i understood another button should be created in the toolbar in order to run upon initialization but its not... and when i rerun/refresh/reopen the notebook/kernel/etc nothing happens.

I cannot find any documentation besides this:
http://nbviewer.ipython.org/github/Carreau/posts/blob/master/04-initialisation-cell.ipynb
Which is actually not very helpful,

P.S.: my env: Anaconda: 2.1.0 (x64) - Python 2.7.8 – IPython 2.3.1

Thank you in advance.

**Comment by jcb91** [comment]
closing as stale
