### ISSUE TITLE
nbextensions compatibility for notebook versions 6.x.x

### ISSUE THREAD

**Issue by mcsitter** [ipython-contrib/jupyter_contrib_nbextensions#1434]
Hello contributors,

Jupyter notebook version 6.0.0 came out and nbextensions are commonly used.
Are there plans for checking compatibiltiy? There is an option to block the configuration of nbextensions, but the extensions do not get turned off and of course do not entirely loose their functions. How will the explicit compatibility for extensions be managed?
Will some extensions at some point be discontinued?

There quite a few of Pull requests and Issues to be solved. I would be happy to contribute, but I do not know where how to start. There are also a few really old ones not solved so far.

**Comment by juhasch** [comment]
Hi,
thanks for offering your contribution, this is really welcome.
A good starting point is probably reading the `notebook extension structure` of the docs and trying out things in the browser.

Regarding compatibility, there is an entry in the YAML file for each extension:
`Compatibility: 3.x, 4.x, 5.x`
This is only for the nbextension configurator, and not used by the extensions, as they don't know about the YAML file.

I would be possible to add specific version checks into each extension, but we never did so.

**Comment by obarak** [comment]
@mcsitter - Why did you close the issue?
