### ISSUE TITLE
skip-traceback for lab

### ISSUE THREAD

**Issue by mlucool** [ipython-contrib/jupyter_contrib_nbextensions#1445]
Hi,

Is there any plan to port `skip-traceback` to lab?

**Comment by toolmaker-berlin** [comment]
> Hi,
> 
> 
> 
> Is there any plan to port `skip-traceback` to lab?

... please have a look to toolmaker-berlin jupyter lab skip traceback 😉

**Comment by mlucool** [comment]
We made https://github.com/deshaw/jupyterlab-skip-traceback. Closing.
