### ISSUE TITLE
Hinterland autocompletes code too fast

### ISSUE THREAD

**Issue by RasNath** [ipython-contrib/jupyter_contrib_nbextensions#1484]
When typing code quickly, hinterland always will complete my code for me while I'm typing. It forces me to slow down, weather I want the code suggested or not. An example would be something like:

my_variable = 3.4
print(my_variable)

When typing the print statement, if I am typing quickly, hinterland will autocomplete my code so I end up with something like:

print(my_variableariable)

Which I then have to backspace a bunch of times to undo. If I slowdown it will hint but not autocomplete my code. I am not sure how to turn off autocomplete since I would much rather prefer to hit enter if the suggestion matches. I do want hints but due to the unpredictability of when hinterland decides to autocomplete, I want to turn that function off but do not see an option.

**Comment by RasNath** [comment]
This issue has already been opened.

**Comment by ML-Chen** [comment]
(Duplicate of https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1475)

Yeah, this is really frustrating.

**Comment by abc1044** [comment]
Take a look at this solution #1381
