### ISSUE TITLE
Only 3 extensions available after installing

### ISSUE THREAD

**Issue by ricardojumia** [ipython-contrib/jupyter_contrib_nbextensions#1564]
I just installed **jupyter_contrib_nbextensions** in a new conda installation and there are only three extensions available.

![image](https://user-images.githubusercontent.com/41117008/114201143-caddd800-994d-11eb-95a3-e65a8bfb124c.png)

Steps I've taken to try to solve this issue:
- downgrade jupyter notebook to 6.1.5 
- downgrade jupyter notebook to 6.1.1 (suggested [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1550#issuecomment-768496425) though for a different problem)

Any help would be greatly appreciated.

**Comment by ObliviousMonkey** [comment]
Had the same problem and found [this SO post](https://stackoverflow.com/a/59514338/8876619) that solved it for me (except for the first line, as I installed through Conda):

>Follow 3 steps: In Terminal
>```
>pip install jupyter_contrib_nbextensions
>jupyter contrib nbextension install --user
>jupyter nbextension enable varInspector/main
>```
>after this you will see "Vaildating: ok" Now you can open jupyter notebook you will see the require changes

Before doing this, I also downgraded `notebook` to version 5.7.8 as most of the extensions are not compatible with 6.x (`conda install notebook==5.7.8`)

**Comment by ricardojumia** [comment]
Worked like a charm. Thank you!

**Comment by batprem** [comment]
Thanks @ObliviousMonkey !!! that helps me a lot
