### ISSUE TITLE
In Jupyterhub v3 the TOC2 vanishes behind the main navigation bar.

### ISSUE THREAD

**Issue by Paperone80** [ipython-contrib/jupyter_contrib_nbextensions#1608]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/26833332/196028565-96264038-2fd4-4b96-9b34-c42fe3c561bf.png">

Error see screenshot: 

Config:
jupyter-contrib-nbextensions      0.6.0
jupyter-nbextensions-configurator 0.5.0
jupyter                           1.0.0
jupyter_client                    7.4.2
jupyter-console                   6.4.2
jupyter-contrib-core              0.4.0
jupyter-contrib-nbextensions      0.6.0
jupyter-core                      4.11.1
jupyter-highlight-selected-word   0.2.0
jupyter-http-over-ws              0.0.8
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.5.0
jupyter-server                    1.21.0
jupyter-telemetry                 0.1.0
jupyterhub                        3.0.0
jupyterlab                        3.4.8
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.16.0
jupyterlab-widgets                1.1.0

**Comment by Paperone80** [comment]
Changing the width of the TOC2 bar adjusts it but now returns a JS errors:

Uncaught ReferenceError: _ is not defined 
    at setMd (toc2.js?v=20221016194143:110:43)
```
var setMd = function(key, value) {
        if (liveNotebook) {
            var md = IPython.notebook.metadata.toc;
            if (md === undefined) {
                md = IPython.notebook.metadata.toc = {};
            }
            var old_val = md[key];
            md[key] = value;
            >>>> if (typeof _ !== undefined ? !_.isEqual(value, old_val) : old_val != value) { <<<<
                IPython.notebook.set_dirty();
            }
        }
        return value;
    };
```
    at HTMLDivElement.saveTocPosition (toc2.js?v=20221016194143:284:9)
```
var saveTocPosition = function () {
        var toc_wrapper = $('#toc-wrapper');
        var new_values = toc_wrapper.hasClass('sidebar-wrapper') ? ['width'] : ['left', 'top', 'height', 'width'];
        $.extend(toc_position, toc_wrapper.css(new_values));
        setMd('toc_position', toc_position);
    };
```
    at V.<computed>.<computed>._trigger (jquery-ui.min.js:6:1)
    at V.<computed>.<computed>._propagate (jquery-ui.min.js:6:1)
    at a.<computed> [as _propagate] (jquery-ui.min.js:6:1)
    at V.<computed>.<computed>._mouseStop (jquery-ui.min.js:6:1)
    at a.<computed> [as _mouseStop] (jquery-ui.min.js:6:1)
    at V.<computed>.<computed>._mouseUp (jquery-ui.min.js:6:1)
    at a.<computed> [as _mouseUp] (jquery-ui.min.js:6:1)
    at s._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate (jquery-ui.min.js:6:1)

**Comment by ylzuimeng** [comment]
I have the same problem
- first find the files of the toc2.js which is in the package， copy the old version from github；
- then change main.css, change the code like below;
.sidebar-wrapper {
/*  top: 10;
  bottom:10; */
  height: 700px;
  /* width: 212px; */
    /* border-color: #eeeeee;  /* default - alterable via nbextension-configurator */ */
};
the reason of the bug is that the characters are not display; so set height: 700;
you get what you want

**Comment by juhasch** [comment]
Hi, can you try the change in PR #1618 ?

**Comment by glennneuber** [comment]
Hi @juhasch, 

thanks for looking into this. I updated with the latest tarball master but I am still getting this error. Still hiding in the top and appears with errors when I double click to drag. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/96860901/213889482-b8a04945-3caa-4bfe-805c-e3fbd3a71322.png">

<img width="606" alt="image" src="https://user-images.githubusercontent.com/96860901/213889510-018722b9-1059-4136-a1a0-9f87f7182959.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/96860901/213889521-5e8b5b73-df31-4a62-90a5-a34c4ca2caf7.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/96860901/213889561-7935ca8e-201c-4025-ad46-782bbd257730.png">
