### ISSUE TITLE
Collapsible Headings alters vertical position of tooltip for signature and docstring

### ISSUE THREAD

**Issue by stanwest** [ipython-contrib/jupyter_contrib_nbextensions#1611]
With the Collapsible Headings extension enabled in versions 6.5.1 and 6.5.2 of [*notebook*](https://github.com/jupyter/notebook), but not in v. 6.4.12, the tooltip that displays the current object's signature and docstring when one hits Shift + Tab appears at the wrong height within the browser window. As far as I've seen, the tooltip appears too low when the view is scrolled near the top of the notebook and too high when near the bottom. The screen-shots below illustrate the behavior.

![low](https://user-images.githubusercontent.com/38358698/199811029-703db72e-40d4-457f-90f7-1a94d6aa7133.png)

![high](https://user-images.githubusercontent.com/38358698/199811056-bcf0d86f-4291-4383-8711-44f9b755ee53.png)

For a long enough notebook scrolled down somewhat, the tooltip may have so high a position that it is outside the window, giving the impression that the notebook is ignoring Shift + Tab (at least until the fourth press raises the pager).

Prior related issues are  #509 and #949, and the possibility of breakage is [mentioned](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/2248f6e15753d0eb4339215313ae21ba09cbdf74/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/readme.md?plain=1#L85-L91) in the extension's *readme* file.

**Comment by venkate123** [comment]
It is caused by  "Jupyter.version()" in patch_Tooltip failed to return right notebook version in notebook 6.X. For I have no idea  how to get notebook version, I forked and simply removed it and only keep compatible for 5.X & 6.X. If you need, you can install from my repo by `pip install git+https://github.com/venkate123/jupyter_contrib_nbextensions.git`

**Comment by stanwest** [comment]
> It is caused by "Jupyter.version()" in patch_Tooltip failed to return right notebook version in notebook 6.X.

I see. For versions 6.5.x of *notebook*, `Jupyter.version` is the version not of *notebook* but rather of *nbclassic* (for example, "0.4.5"). The change occurred with jupyter/notebook#6474, which replaced the static assets of *notebook* with those of *nbclassic*.

I've found that `sys_info.notebook_version` correctly returns the version of *notebook* (e.g., "6.4.12" or "6.5.1") and appeared in *notebook* version 4.0.0 from jupyter/notebook@e7c2c369e028dbb5f88e4e66a5c5b63bdfaf4131.

**Comment by venkate123** [comment]
> I've found that `sys_info.notebook_version` correctly returns the version of _notebook_ (e.g., "6.4.12" or "6.5.1") and appeared in _notebook_ version 4.0.0 from [jupyter/notebook@e7c2c36](https://github.com/jupyter/notebook/commit/e7c2c369e028dbb5f88e4e66a5c5b63bdfaf4131).

Well Done!
