### ISSUE TITLE
failed building wheel for jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by rootsmusic** [ipython-contrib/jupyter_contrib_nbextensions#1631]
I installed Anaconda on a new PC, and I updated all packages in the base environment.  This is the first package that I'm adding to my base environment.  It returns the error:
```
error: could not create 'build\bdist.win-amd64\wheel\jupyter_nbextensions_configurator-0.6.1.data\data\etc\jupyter\nbconfig\notebook.d\jupyter_nbextensions_configurator.json': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jupyter_nbextensions_configurator
  Running setup.py clean for jupyter_nbextensions_configurator
Successfully built jupyter-contrib-nbextensions jupyter_contrib_core
Failed to build jupyter_nbextensions_configurator
Installing collected packages: jupyter_highlight_selected_word, jupyter_contrib_core, jupyter_nbextensions_configurator, jupyter-contrib-nbextensions
  Running setup.py install for jupyter_nbextensions_configurator ... done
  DEPRECATION: jupyter_nbextensions_configurator was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
Successfully installed jupyter-contrib-nbextensions-0.7.0 jupyter_contrib_core-0.4.2 jupyter_highlight_selected_word-0.2.0 jupyter_nbextensions_configurator-0.6.1
```
When Jupyter opens in Firefox, Juypter shows no additional tab.

**Comment by komaHAHA** [comment]
Hi, I'm faced the same issue and there is a solution. Im as you tryed to install nbextension to activate hints. But, always when I installed and activate all needs modules in terminal and open jupyter notebook, there wasn't a button 'Nbextension'. For fix this, you can try to reinstall older version on jupyter in anaconda navigator (next to all the utilities in the upper right corner there is a button where you can install past versions). Here you are.

**Comment by JMMarchant** [comment]
Also encountered this just now, any solution/reason why this was closed?

**Comment by rootsmusic** [comment]
@JMMarchant  I think that this error is related to [other issues](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues) about compatibility with other packages.

**Comment by chen-lin14** [comment]
Use the conda forge command
