### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by RNarayan73** [ipython-contrib/jupyter_contrib_nbextensions#1633]
Hello,

It appears that this package cannot be installed in a python 3.11 environment. 

Is this something you are building into your next release?

Thanks
Narayan

**Comment by RNarayan73** [comment]
Is anyone working on making this package compatible with python 3.11?

**Comment by bribroder** [comment]
This may be because of the dependency on jupyter_highlight_selected_word which has an open issue for py 3.11: https://github.com/jcb91/jupyter_highlight_selected_word/issues/45

**Comment by RNarayan73** [comment]
The above issue arose when I was creating python environments with conda.
I have since moved to creating environments using poetry and pip which doesn't cause the issue.
