### ISSUE TITLE
please add info on wiki about the slidemode extension

### ISSUE THREAD

**Issue by jason-s** [ipython-contrib/jupyter_contrib_nbextensions#167]
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki#slidemode just says:

> slidemode  Make slide creation for reveal.js easier

I tried installing it, and it doesn't seem to do anything, so I can't tell what it is I'm supposed to be able to do, now that I have the extension installed.

Could someone please elaborate?

**Comment by jason-s** [comment]
I did this step to install:

```
import IPython
IPython.html.nbextensions.install_nbextension('https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/slidemode')
```

**Comment by jason-s** [comment]
Is it built into IPython 2.3.1 already?

**Comment by juliohm** [comment]
@jason-s I'm also having some trouble with this extension, if you're cloning this repository, read the custom.example.js that comes with it. Replace your profile_default/static/custom/custom.js with it.

The other extensions are working for me, but this specific one is not.

**Comment by juliohm** [comment]
@juhasch , could you please explain why the extension isn't loading correctly on IPython 3 (Jupyter)? I uncommented the line on `custom.example.js` but no effect.

**Comment by juhasch** [comment]
Sorry, I have no idea about the slidemode extension.

@damianavila : should we remove the extension, as ist does not seem to be working in 3.x anymore ?

**Comment by damianavila** [comment]
I think @Carreau made some modifications lately to make it work, let's see if he wants to take a look here before removing it...

In any case, I would suggest to use [RISE](https://github.com/damianavila/RISE) instead because is more stable and documented right now...

**Comment by juliohm** [comment]
Hi Damián,

Thanks for pointing out RISE! I'll definitively give it a try.

2015-03-23 5:38 GMT-07:00 Damián Avila <notifications@github.com>:

**Comment by m1yag1** [comment]
I installed the slidemode extension however it does not work even with the custom.js file.

**Comment by jcb91** [comment]
closing as slidemode has been removed from 0.2.7. As mentioned above, check [RISE](https://github.com/damianavila/RISE) for similar functionality
