### ISSUE TITLE
Styling Not Rendering (Cache issues?) in Chrome 

### ISSUE THREAD

**Issue by psychemedia** [ipython-contrib/jupyter_contrib_nbextensions#191]
I've been experimenting with a couple of [styling customisations](https://gist.github.com/psychemedia/ab7bbc3aa731269bd3b4/) that allow users to colour "exercise" cells in a student notebook and have noticed that the styles are typically *not* rendered in Chrome (OS/X) unless I do a cmd-shift-r (forced refresh ignoring cache); the style seems to render okay in Safari.

I was wondering whether anyone had suffered similar issues/found workarounds with other extensions?

There could also be issues with my own code, of course:-(

**Comment by jcb91** [comment]
This is super old, so maybe not relevant any more, but in case you're still looking for suggestions...

The gist code would need updating to fit the 4.x `define(` model for building extensions. At least in 4.x, using the requirejs `require.toUrl` method for setting the URL of script nodes (see, e.g. the `add_CSS` function in `nbextensions/config/main.js`) seems not to cause caching issues for me (also on chrome, osx). Note that using relative paths with `require.toUrl` only works for code declared inside a `define` call (I'm not massively sure why, this is an empirical observation).

**Comment by jcb91** [comment]
closing as outdated, please reopen if you've further issues with this
