### ISSUE TITLE
cell tags not working

### ISSUE THREAD

**Issue by JohnGriffiths** [ipython-contrib/jupyter_contrib_nbextensions#197]
Hello. 

I'm having some trouble with the swc cell tags extension after upgrading to ipython 3.0. It isn't working (normally it adds an entry to the drop-down bar at the top, and gives clickable selection of cells for a number of different tags). 

Could someone please confirm that this extension works in ipython 3.0, and gives me some pointers on how to install it?

Thanks,

john

**Comment by jcb91** [comment]
Hi @JohnGriffiths, did you get this working in the end?

**Comment by jcb91** [comment]
closing, as swc was removed in #891. I think tagging is starting to move into core notebook though?
