### ISSUE TITLE
adding items to drop-down toolbar and installing without modifying custom.js 

### ISSUE THREAD

**Issue by JohnGriffiths** [ipython-contrib/jupyter_contrib_nbextensions#219]
I'd like to write a simple extension that includes adding an item to the drop-down cell toolbar (the one with 'edit metadata', 'slideshow', etc.). 

It would be very similar to the 'swc' and jdfreder's 'notebook cherry picker' tools; i.e. would have tick-boxes in the top-right corner of each cell when its cell toolbar item is selected. I then do some custom filtering with nbconvert based on cell metadata (again, very similar to jdf's cherry-picker); that stuff I believe I have sorted. But not still not quite sure about the js and installation stuff. 

I would like if possible to be able to install it using the install_nbextension tools, rather than modifying custom.js manually. 

Could anyone point me to examples of extensions doing this (i.e. adding items to the cell toolbar + install with install_nbextension...), or give an outline of what needs to be in it?

Ta.

**Comment by damianavila** [comment]
Check this PR: https://github.com/ipython-contrib/IPython-notebook-extensions/pull/218.
It works with some of the tools you want to play with...

**Comment by jcb91** [comment]
closing as stale/fixed
