### ISSUE TITLE
auto conda packages

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#395]
Added it with a version `0.0.0.20151105`: https://github.com/JanSchulz/package-builder/tree/master/recipes/jupyter-notebook-extensions

-> packages end up here: https://anaconda.org/janschulz/

-> fails on linux: https://circleci.com/gh/JanSchulz/package-builder/28
```
# On branch master
nothing to commit (working directory clean)


Package: nbextensions-0.0.0.20151105-py27_0
source tree in: /opt/conda/conda-bld/work
+ python setup.py install
Installing Jupyter notebook extensions
Configuration files directory: /root/.jupyter
Extensions and templates path: /root/.local/share/jupyter
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    os.mkdir(data_dir)
OSError: [Errno 2] No such file or directory: '/root/.local/share/jupyter'

Command failed: /bin/bash -x -e /opt/conda/conda-bld/work/conda_build.sh ./scripts/run_docker_build.sh returned exit code 1
```

**Comment by JanSchulz** [comment]
I think we should really change to a regular python package and using something like `python -c "import nbextensions; nbextensions.install()"`

**Comment by JanSchulz** [comment]
And it didn't work, at least the packages do not have any actuall content in it?

**Comment by JanSchulz** [comment]
I think the problem is that the package builder does not use the source dir as recipe but a different dir. The current conda package relies on the fact that the complete source is included in the package in the recipe dir in the package.

I still don't understand why the setup.py is run, i thought conda install doesn't run anything? See also https://github.com/ipython-contrib/IPython-notebook-extensions/issues/396

**Comment by juhasch** [comment]
Looking at it again, I think it does not work. Conda does not run anything when installing a package. So building the conda package actually installs it... Not what I intended.

**Comment by juhasch** [comment]
There is a `post-link` step for conda, see http://conda.pydata.org/docs/spec.html#package-metadata
That looks like the correct way.

**Comment by JanSchulz** [comment]
So we have a way to run the actual installer in conda and pip also has a way:

https://github.com/ipython/ipython/blob/master/setup.py#L262
```python
if 'setuptools' in sys.modules:
[...]
    # Script to be run by the windows binary installer after the default setup
    # routine, to add shortcuts and similar windows-only things.  Windows
    # post-install scripts MUST reside in the scripts/ dir, otherwise distutils
    # doesn't find them.
    if 'bdist_wininst' in sys.argv:
        if len(sys.argv) > 2 and \
               ('sdist' in sys.argv or 'bdist_rpm' in sys.argv):
            print("ERROR: bdist_wininst must be run alone. Exiting.", file=sys.stderr)
            sys.exit(1)
        setup_args['data_files'].append(
            ['Scripts', ('scripts/ipython.ico', 'scripts/ipython_nb.ico')])
        setup_args['scripts'] = [pjoin('scripts','ipython_win_post_install.py')]
        setup_args['options'] = {"bdist_wininst":
                                 {"install_script":
                                  "ipython_win_post_install.py"}}
```

**Comment by jfbercher** [comment]
Yes, that is possible. I encountered such problems in a different project.  A possibility is to only permit install from source (eg .tar.gz). This can be done by adding 
```
if 'bdist_wheel' in sys.argv:
    raise RuntimeError("This setup.py does not support wheels")
 ```
in the setup.py.
from the discussion here https://bitbucket.org/pypa/wheel/issues/92 (last commenter)
The point is that now pip7.0 automatically calls the system to build a wheel. So the only solution is to forbid it. Then the install continues after.

**Comment by damianavila** [comment]
As @juhasch said, the post script step is the path to follow for the conda package... for pip... well... you can install it and then ask the user to "activate/enable" the extension

**Comment by JanSchulz** [comment]
As there was another PR for the conda install instructions (#411), I removed the instruction from the readme for now, until this is fixed... See e6a2f81

**Comment by JanSchulz** [comment]
So IMO the way to go here is

* rebuild as a normal python package -> add the installer as a function in the package and all the rest as data 
* pip user are shown how to do the postinst by themselves (`python -c "import jupyter_nbext; jupyter_nbext.install_extensions()"`)
* conda recipe would call the install in a postinst
* setup.py should get another method which does the install step (`setup.py install_extensions`)

[Hah, that's basically the same bugreport as we have in pypandoc: https://github.com/bebraw/pypandoc/issues/83]

**Comment by jcb91** [comment]
Closing, as this is pretty much all done with the restructured pip package & conda-forge integration (aside from adding an additional method to setup.py).
