### ISSUE TITLE
What is the logical location to install to on OS X?

### ISSUE THREAD

**Issue by p-i-** [ipython-contrib/jupyter_contrib_nbextensions#418]
This is particularly frustrating. I have fallen at the first hurdle. I can't find the information anywhere.

I suppose it doesn't matter where it goes, but I'm sure there should be a best fit.

http://stackoverflow.com/questions/33725536/what-is-the-logical-location-to-install-ipython-notebook-extensions-to-in-osx

**Comment by juhasch** [comment]
This is a good question. There are several places extensions can go into:
```Python
from jupyter_core.paths import jupyter_data_dir, jupyter_path
jupyter_data_dir()
jupyter_path()
```

Currently, `setup.py` writes the extensions into the `jupyter_data_dir()` path, which is user specific.
The new conda receipe #417 will write the extensions into the local `/share/jupyter` path of the anaconda environment. 

Hopefully, we will have a pip and conda-installable package soon.

**Comment by jcb91** [comment]
FWIW, on my machine (MBP running Yosemite 10.10.5), the above outputs

```python
['/Users/josh/Library/Jupyter',
 '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/share/jupyter',
 '/usr/local/share/jupyter',
 '/usr/share/jupyter']
```

I have my extensions installed in the per-user directory, `~/Library/Jupyter`. But, as @juhasch says, they should work ok from any of the listed dirs.

**Comment by jcb91** [comment]
Also, just running the setup.py file and installing the `pyyaml` module (with pip, homebrew, macports, etc) should be enough for you to get everything working. It doesn't work for all cases, but I think it should for yours (touch wood).

**Comment by juhasch** [comment]
Thanks @jcb91

**Comment by p-i-** [comment]
So just to confirm, following https://github.com/ipython-contrib/IPython-notebook-extensions#installation I want:
    cd ~/Library/Jupyter
    conda install nbextensions

... And then next time I start up `jupyter notebook` I should see a `nbextensions/` page?

Would someone care to embellish the README.md, so that the next user gets a smoother ride?

**Comment by jcb91** [comment]
I'm not very sure about the Anaconda package, I've not used Anaconda before.
I use a vanilla python (shipped by macports, but any should work).
Following https://github.com/ipython-contrib/IPython-notebook-extensions#installation,

> simply run `setup.py install`

from wherever you downloaded the repository.
The script will figure out where to put stuff for you.
Specifically, it will install extension javascript files, templates, python extension files, etc. to
`jupyter_data_dir()`, which on OSX will be `~/Library/Jupyter`, and config files to `jupyter_config_dir()`, which on OSX is `~/.jupyter`.

**Comment by jcb91** [comment]
When you run `jupyter notebook` after installing, the `/nbextensions` page should be available, but it won't open automatically, you need to manually visit it.

**Comment by p-i-** [comment]
I just have to go with Anaconda. I think that installation page needs to say `first download and unzip the repository to e.g. `~/Downloads/`, now:

    cd ~/Downloads
    conda build IPython-notebook-extensions-master

ok, this works, and is appears to invoke `python setup.py install`  
However the next instruction,

    conda install nbextensions

... fails:

    Error: No packages found in current osx-64 channels matching: nbextensions

However, launching `jupyter notebook`, and setting the URL to `http://localhost:8888/nbextensions` correctly displays the extensions page.

Looking back, the main thing that threw me is that the installation section didn't say anything about downloading the repo. I assumed anaconda would take responsibility for downloading it. And the installation section made it sound like I needed to be in a certain directory, because anaconda would install into that directory.

Can you see what I mean here? Once you understand what's going on, the text makes sense. But if you don't have any idea what's going on, there is too much ambiguity.

Can I suggest the following instructions as replacement:

 1) download repository to say `~/Downloads` and unzip 
 2) `cd ~/Downloads`
 3) `conda build IPython-notebook-extensions-master` (assuming that is the name of the folder that just got created)
 4) (re)launch Jupyter notebook: `jupyter notebook`
 5) Change URL from `http://localhost:8888/tree` to `http://localhost:8888/nbextensions`
 6) `rmdir ~/Downloads/IPython-notebook-extensions-master/` if you like

With something like this, even someone as stupid as me will be able to instantly see what is going on, and adapt if necessary (maybe different download location, maybe different repository name, maybe different URL root)

**Comment by jcb91** [comment]
First off, glad you got it working! Apologies for the confusion.

Second, your confusion is natural, it's pretty confusing at the moment! It's being addressed, but is still in flux.

I think you're right, it makes sense to edit the readme. However, we can't specify any paths using `~`, since it doesn't work on Windows (I think Windows uses the environment variable `%HOMEPATH%`?). I'll knock something together, but equally, feel free to submit a PR yourself :)

**Comment by jcb91** [comment]
Also, a bit late, but just in case it's useful in future, I think it may be possible to get Anaconda to take responsibility for downloading the source, using instructions from https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/config/readme.md:
> you can install the package using the 
> ```bash
> conda install -c https://conda.binstar.org/juhasch nbextensions
> ```
> command

**Comment by jcb91** [comment]
closing as (hopefully!) fixed by the new pip-compatible package and/or conda-forge integration
