### ISSUE TITLE
Discussion about new extension mechanism

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#425]
It seems that this package may soon be obsolete:

https://github.com/jupyter/enhancement-proposals/pull/7#issuecomment-161145036

**Comment by damianavila** [comment]
Right now there is a lot of moving in the development of the new architecture... but that will not land until several months in the future... for sure the extension on this repo will need an update... or a re-factor... but I hope the transition would not be too painful...

**Comment by juhasch** [comment]
I guess things have moved on...
