### ISSUE TITLE
Save pasted images to file instead of base64 blob?

### ISSUE THREAD

**Issue by spex66** [ipython-contrib/jupyter_contrib_nbextensions#43]
I'm new to IPython Notebook, but stumbled over this extension because of the image copy/paste support.
So my question is, would it be an idea to save the images to disk, to overcome the big fat blob issue? I saw "writefile" magic, wouldn't this be an available technique?
Or is this a security thing, because of running in a browser?

Thank you very much for sharing this work!
regards
Peter
(=PA=)

**Comment by LukasDrude** [comment]
@spex66 seemed to fiddle around with a paste function from the clipboard. I tried to use the recent drag and drop extension. Adding images by drag and drop seems to work fine, but adding them from the clipboard seems to not work.

Is this problem somewhere addressed?
