### ISSUE TITLE
Table sorter option for table-beautifier

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#540]
A sorter and a little button which does filter cells in the table could be interesting... E.g. like the stats table here: https://jiffyclub.github.io/snakeviz/#interpreting-results

**Comment by janschulz** [comment]
Or this, which looks even better: https://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html

**Comment by jcb91** [comment]
fixed by #571
