### ISSUE TITLE
TOC2 table of content links & numberings don't work once pages are nbconverted to HTML

### ISSUE THREAD

**Issue by hhayama** [ipython-contrib/jupyter_contrib_nbextensions#551]
TOC2 is great at generating the table and auto updating the numbering but once I convert the notebook to HTML, the links all become broken & the numbering from each individual section disappears from the nbconverted file.  Is this the intended behavior?  It unfortunately makes this extension not as useful for HTML converted files which forces me to go back to (more or less) manually updating and creating the links.

**Comment by jfbercher** [comment]
Yes. I realized that too. This has been introduced recently when adding unique ids to cope with repeated headings. For the toc cell it works in the live notebook but not after conversion (where headings numeration is lost). I have made a small patch which returns to the previous behavior  for the toc cell, and I will upload it shortly.

**Comment by hhayama** [comment]
Awesome news, Thanks so much!

**Comment by jcb91** [comment]
@hhayama has #554 fixed this for you?

**Comment by brunobeltran** [comment]
Would a cleaner solution be to do what the Python-Markdown extension does and implement a preprocessor in python?

Then we could get rid of the duplicate code and confusion that the `saveid`/`id` stuff causes?

**Comment by jfbercher** [comment]
The original issue is solved by #554. 
I think that the last comment by @brunobeltran is solved, see the discussion in https://github.com/jcb91/jupyter_contrib_nbextensions/issues/3. Otherwise please reopen an issue.
