### ISSUE TITLE
make package more pip-friendly

### ISSUE THREAD

**Issue by jcb91** [ipython-contrib/jupyter_contrib_nbextensions#577]
I've been thinking about how everything is packaged for a while, and I think it might be worth making the repo into a more conventional pip package. Although the nbextensions are largely not python packages in the normal sense, we still ship python code like the `nbextensions.py` server extension, which would benefit from being part of a package. We can adopt a model similar to jupyter, whereby the javascript stuff is installed with the python package. Making the extensions, nbextensions and templates part of a pip-installable package carries several potential benefits:

1. Currently, we edit `.py` configuration files in order to add our server-side extensions to the server's python path, so that they can be loaded correctly. This is a bit magic (not the good kind). If we were to make them part of the pip-package, then after install, they'd be on the path already, so we could just used the fully-qualified module name in the json config, and not edit the `.py` files. The same applies to nbconvert pre- and post-processors. We can just use the `NotebookApp` config items [`extra_nbextensions_path`](https://github.com/jupyter/notebook/blob/792ff7d2d2372e87d32ed2633082c282a2f15aad/notebook/notebookapp.py#L701-L703), [`extra_template_paths`](https://github.com/jupyter/notebook/blob/792ff7d2d2372e87d32ed2633082c282a2f15aad/notebook/notebookapp.py#L690-L694), and the `Exporter`'s [`template_path`](https://github.com/jupyter/nbconvert/blob/54603db3a8d3fb91fc15b1ec634a34d2927dae0c/nbconvert/exporters/templateexporter.py#L106)
2. pip-installed modules can be inherited from - it would make sense to add the various extensions and exporters as separate modules, a la #421
3. there's less ambiguity about where to install things (see, e.g. #418) if they're part of a package - they're in the package!
4. This is the direction Jupyter seem to be taking for 4.x, having nbextensions installable from python packages (see https://github.com/jupyter/notebook/pull/879).

All of this would mean that the package would need a new pip name (currently it seems to be named `Python-contrib-nbextensions` - see [setup.py#L81](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/ddb58108e3eb2f95e946b23a947faf172cb22018/setup.py#L81)), which, based on the [commented out `packages` argument](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/ddb58108e3eb2f95e946b23a947faf172cb22018/setup.py#L93) is a typo, and given the pending repo rename #334, is not future-proof anyway). Perhaps `jupyter_contrib_nbextensions`, or, to avoid huge module names, the more compact `jupyter_contrib_nbext` or the super-terse `jcnbe`?

Any thoughts?

**Comment by jcb91** [comment]
I have an example implementation using the package name `themysto` in my [`pipper` branch](https://github.com/jcb91/IPython-notebook-extensions/tree/pipper).

**Comment by jfbercher** [comment]
@jcb91 
I agree that we should rework the global pip package in a more conventional way (and rename it of course, there is indeed a typo - probably from me). The nbextension server extension is by itself a very useful utility. It could also be interesting to have the backend extensions available as separate packages, with versions numbers, may be with the "root" nbextension as a dependency. Perhaps also that the nbextension utility could be used to check for new versions of the subpackages? 
I have begin to look at the way of turning extensions as separate packages and it does not seem so difficult. Your example implementation  (pipper branch) has disappeared :(

**Comment by jcb91** [comment]
Yes, apologies, it pretty much merged with my efforts at CI things, so now
look for the 'trav' branch. I keep rebasing it, so probably best not to
fork it without warning me to keep it stable!

**Comment by jcb91** [comment]
Also, the readme isn't properly updated yet, so it has quite a few errors in it.

On the [`trav` branch](https://github.com/jcb91/IPython-notebook-extensions/tree/trav), essentially the install process is 

```bash
# install the pip package:
pip install https://github.com/jcb91/IPython-notebook-extensions/archive/trav.zip
# edit config files to enable everything:
themysto install
```

**Comment by jcb91** [comment]
done and dusted!
