### ISSUE TITLE
Is it possible to have certain extensions activated by default on install?

### ISSUE THREAD

**Issue by GeorgeG94** [ipython-contrib/jupyter_contrib_nbextensions#578]
I'm using a VM and installing through docker installing through the pip command given in the readme . It would be nice to not have to be able to activate them every time I start.

I've tried taking an image and running through that after having turned the extensions on, but no luck.

Any help would be much appreciated!
Cheers,
George

**Comment by jcb91** [comment]
So, which extensions are active (enabled, in jupyter terminology, I should change the button text on the `/nbextensions` page) is stored in (up to) four jupyter config files: `notebook.json`, `tree.json`, `edit.json`, and `common.json`.

These config files are per-user files, so should usually exist in the `nbconfig` subdirectory of `jupyter --config-dir`. I'm not familiar with where this might be, or how it might be different for a docker setup. However, I would guess from the fact that you're having trouble with persistence, that somehow these config files aren't being included in your image.

You can use the following python snippet (from within the docker container perhaps?) to locate the existing config files:

```python
import os.path
from notebook.services.config import ConfigManager
cm = ConfigManager()
for section in ('edit', 'tree', 'notebook', 'common'):
    conf_path = cm.file_name(section)
    if os.path.exists(conf_path):
        print(conf_path)
```

Alternatively, if you want a quick-and-dirty fix to just get them enabled (not to alter extensions' config parameters), then you might get away with adding some `jupyter nbextension enable usability/collapsible_headings/main` type lines to your docker setup...

Hope some of that makes sense!

**Comment by jcb91** [comment]
@GeorgeG94 did you have any luck with this?

**Comment by GeorgeG94** [comment]
Yes I did, thanks very much for all the help, sorry for not responding was all a bit hectic!!

Only ended up needing the collapsible headings in the end so what you gave me in the bottom line worked for the quick and dirty fix!

Helped me get my masters degree :D

**Comment by jcb91** [comment]
Awesome, glad to hear you got it working, and that collapsible_headings was helpful :smile:
