### ISSUE TITLE
Using this extension with different kernals

### ISSUE THREAD

**Issue by Shaun1818** [ipython-contrib/jupyter_contrib_nbextensions#602]
Hi 

Can i use this extension with a different Kernal 
I like to use octave for my work

When is use Octave kernal 
![image](https://cloud.githubusercontent.com/assets/19259454/15104191/c5933688-1608-11e6-82f2-60e802843d95.png)

When i use python kernal 
![image](https://cloud.githubusercontent.com/assets/19259454/15104204/e86b3836-1608-11e6-9293-58449f1f57e2.png)

I am relatively new to using the notebook so any advice may have to be 'dumb-ed' down a bit

**Comment by Shaun1818** [comment]
Sorry pictures are the wrong way around

**Comment by jcb91** [comment]
So, to clarify,

1. You're talking about the pythonmarkdown nbextension, right?
2. It's the Octave kernel that you're having problems with? You can edit your posts after making them using the little pencil icon at the top right, if you make mistakes.

Although it's named python-markdown, I can't see in principle why it shouldn't support other languages. Essentially what happens is that the string inside the markdown curly brackets (presumably `{{ a }}` in your examples) is sent to the kernel for execution, then the return value is inserted into the markdown source. So, presumably, the octave kernel doesn't produce an appropriate output from the statement `a`. You could try using `{{ printf('%d', a) }}` instead?

**Comment by Shaun1818** [comment]
Thaks jvb91. 

Yes you are correct i am talking abiut the pythonmarkdow nbextension. Yes i am have problems with the octave kernal.

I tryed to use the printf function as you descried above and it still dosent wont work. I also tried, fprintf and display function the it still wont work. 

Based how you described it worked above; currently after i have run the code once, to re-run it i have to restart the kernal. So i am wondering if that is why it wont work as this problem doesn't happen with the python kernal

**Comment by juhasch** [comment]
There is nothing Python-specific going on in this extension, we should probably rename it.
You can try this code snippet in a code cell and try to see if you get a response in the Javascript console of your Browser:
```Javascript
%%javascript
var callbacks = { iopub : { output: function(out_data){ console.log(out_data) } } };
var code = 'printf("Hello World")'
Jupyter.notebook.kernel.execute(code, callbacks, {silent: false, store_history : false, stop_on_error: false });
```

**Comment by Shaun1818** [comment]
Thanks 

I ran your above code, below is a screen shot of what i got

**Comment by Shaun1818** [comment]
So does anyone have any hints on how to get this to work

**Comment by jcb91** [comment]
well, it looks from your console log like only a single callback is executed, and that the `msg_type` for the `out_data` which it receives is `stream`, rather than the expected `execute_result`. I'm not sure whether this is a fault of the kernel - I have no Octave kernel, and I seem to get the same behaviour using a python kernel (with appropriately modified code). Are you using the [Calysto octave kernel](https://github.com/Calysto/octave_kernel)?

**Comment by juhasch** [comment]
Thanks @jcb91 for looking into this. I am currently travelling and can't really test this. 
Making the extension work should be easy. From `outputarea.js`:
```Javascript
    OutputArea.prototype.handle_output = function (msg) {
        var json = {};
        var msg_type = json.output_type = msg.header.msg_type;
        var content = msg.content;
        if (msg_type === "stream") {
            json.text = content.text;
            json.name = content.name;
        } else if (msg_type === "display_data") {
            json.data = content.data;
            json.metadata = content.metadata;
        } else if (msg_type === "execute_result") {
            json.data = content.data;
            json.metadata = content.metadata;
            json.execution_count = content.execution_count;
        } else if (msg_type === "error") {
            json.ename = content.ename;
            json.evalue = content.evalue;
            json.traceback = content.traceback;
        } else {
            console.log("unhandled output message", msg);
            return;
        }
        this.append_output(json);
    };
```
@Shaun1818 : So if you want to test this, you can make a small change to the extension.
Change the lines:
```Javascript
                        } else if (out_data.msg_type === "execute_result") {
                            var ul = out_data.content.data;
```
to
```Javascript
                        } else if (out_data.msg_type === "stream") {
                            var ul = out_data.content.text;
```

**Comment by juhasch** [comment]
Should work now.
