### ISSUE TITLE
Set autoscroll threshold causes selector and button to disappear from the toolbar

### ISSUE THREAD

**Issue by cohilla** [ipython-contrib/jupyter_contrib_nbextensions#639]
It seems that when I attempt to set the autoscroll threshold on notebook load to true, it neither sets the threshold, and the selector and button disappear from the toolbar.

**Comment by jcb91** [comment]
hmm. Sounds like a javascript bug is preventing the extension from loading properly. Could you post any and all [javascript console](webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) output?

**Comment by jcb91** [comment]
Also notebook version

**Comment by jcb91** [comment]
@cohilla any news on this?

**Comment by cohilla** [comment]
Nope

**Comment by jcb91** [comment]
@cohilla not a problem. Ok, in that case I'll close this as cannot-reproduce until it shows up again one day
