### ISSUE TITLE
Centered title/menus when using toc2-sidebar view looks odd

### ISSUE THREAD

**Issue by Kevin-McIsaac** [ipython-contrib/jupyter_contrib_nbextensions#650]
Now that toc2-sidebar expands the sidebar + notebook to fit the windows having the title/menu bar centered looks odd and as the windows size is changed the menu moves. 

A more typical approach, like in Google Docs, is to have the menus set to the left.  I've set the following in .jupyter/custom/custom.css
div#menubar-container, div#header-container {
  width: auto;
}

which fixes the title/menu to the left

**Comment by jfbercher** [comment]
I finally understood, 5 months later, what you meant here! 
I have tested this (+ an extra padding-left) and agree that it will look much better. I propose to include this in the toc stylesheet in a next PR.

**Comment by jfbercher** [comment]
Closed by #803
