### ISSUE TITLE
Python Markdown for R kernel

### ISSUE THREAD

**Issue by clayms** [ipython-contrib/jupyter_contrib_nbextensions#661]
How can I get the Python Markdown notebook extension to work with the R kernel?

**Comment by juhasch** [comment]
The R kernel seems to reply with a different message compared to IPython. Probably not difficult to fix, however I have no R running to test this.

**Comment by juhasch** [comment]
See also #602

**Comment by janschulz** [comment]
Just a bit of background on the R kernel difference: it was deemed "traditional", that R returns the result of all lines which do not return their result as "invisible" (R has the concept of returning something invisible, which is then not printed) while the python kernel is based on IPython which prints only the return thing of the last line (if that is non-None) in a block. So the R kernel decided to use display data always and no execute reply at all.

So IMO the dynamic markdown extension should take whatever is returned in either execute reply or display data (the structure is basically the same if I remember correctly) and display it.

**Comment by juhasch** [comment]
PR #676 should make this work.
