### ISSUE TITLE
  ImportError: No module named 'nbextensions'

### ISSUE THREAD

**Issue by lll9p** [ipython-contrib/jupyter_contrib_nbextensions#667]
I got error below this morning:

`[W 09:06:34.744 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "C:\Users\myname\AppData\Local\Programs\Python\Python35\Lib\site-packages\notebook\notebookapp.py", line 1042, in init_server_extensions
        mod = importlib.import_module(modulename)
    File "/opt/python3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
  ImportError: No module named 'nbextensions'`

 and I download the file [IPython-notebook-extensions/extensions/nbextensions.py](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/f7ad9bd853e685ecb096053a5571ecf0e6fbe95a/extensions/nbextensions.py) and save to `C:\Users\myname\AppData\Roaming\jupyter\extensions` 

and then I restart jupyter notebook, no error at all.

seems extensions/nbextensions.py was deleted from the repository at [d076664a20f40b137a2b642d9ea8dd7bdcea2953](https://github.com/ipython-contrib/IPython-notebook-extensions/commit/d076664a20f40b137a2b642d9ea8dd7bdcea2953)

**Comment by jcb91** [comment]
The configurator server extension (which was provided by `nbextensions.py`) has been spun out into a standalone repository/package at [Jupyter-contrib/jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator), so it was indeed removed (intentionally) in d076664a20f40b137a2b642d9ea8dd7bdcea2953. The warning you see in your logs is presumably a result of a config file somewhere which still requests that the old serverextension path `nbextensions.py` be loaded. I would recommend you remove the `nbextensions.py` file, and set it not to load in the config, using something like

```python
from traitlets.config.manager import BaseJSONConfigManager, Config
from jupyter_core.paths import jupyter_config_dir

cm = BaseJSONConfigManager(config_dir=jupyter_config_dir())
config = Config(cm.get('jupyter_notebook_config'))
section = config.get('NotebookApp', Config())
to_remove = 'nbextensions'
section.get('nbserver_extensions', {}).pop(to_remove, None)  # notebook >= 4.2
conf_list = section.get('server_extensions', [])  # notebook < 4.2
while to_remove in conf_list:
    conf_list.remove(to_remove)
cm.set('jupyter_notebook_config', config)

```

**Comment by lll9p** [comment]
@jcb91 Thank you, your code worked.
after a while I figure it out, just deleted `"nbextensions": false` from `jupyter_notebook_config.json` , noneed to hack the config file.

Thanks again.

**Comment by juhasch** [comment]
I think we should add this to our documentation. Or maybe it would be better to extend this to a cleanup script. There are still the old html templates and the old nbextensions/config directory that is useless now.

**Comment by jcb91** [comment]
@juhasch yes, probably. The simplest way would be to add something like the above script to `configure_nbextensions.py`. 

>  There are still the old html templates and the old nbextensions/config directory that is useless now.

These should already be removed by a new install, by line https://github.com/ipython-contrib/IPython-notebook-extensions/blob/9192f86c7e0a390f381b7a3fe687820c2ebf7b2e/install.py#L127

@lll9p 

> noneed to hack the config file.

I'm pretty sure that's what you just did! 😜 Haha.

> after a while I figure it out, just deleted `"nbextensions": false` from `jupyter_notebook_config.json`

Wait, so the extension tried to load even though it was set to `false`? If true, that sounds like a notebook bug. Anyway, glad you got it fixed ok!

**Comment by jcb91** [comment]
should hopefully be handled by the new `migrate` command, but I'll leave open for a while so it's nice & visible...

**Comment by jcb91** [comment]
closing as `migrate` is hopefully visible enough in readme
