### ISSUE TITLE
nbviewer_theme: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by hainm** [ipython-contrib/jupyter_contrib_nbextensions#673]
FYI: https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/publishing/nbviewer_theme/main.js#L9-L10

below code does not work in my old Chrome 

``` javascript
            var val = $(this).val()
            if val == 'default'
```

**Comment by juhasch** [comment]
I don't know what this extension is supposed to do, actually. I guess it should be removed.
Feel free to submit a PR to fix and document it, if it is of any use to you.

**Comment by jcb91** [comment]
closing, as nbviewer_theme was removed in #906
