### ISSUE TITLE
Enabling extensions per-notebook

### ISSUE THREAD

**Issue by typograph** [ipython-contrib/jupyter_contrib_nbextensions#679]
I would like to enable e.g. `toc2` in one notebook without affecting the others, but I cannot find any info on that. Is it possible at all?

**Comment by jcb91** [comment]
Hi there! Sort of. You can add a codecell containing a javascript magic to the notebook, which will load the extension just for that notebook. However, you'll need to run that cell every time the notebook loads. In the codecell, for toc2,you'd use

```javascript
%%javascript
require('base/js/utils').load_extensions('usability/toc2/main');
```
