### ISSUE TITLE
Installation Part 2 yields: [JupyterContribApp] CRITICAL | Bad config encountered during initialization: [JupyterContribApp] CRITICAL | Unrecognized flag: '--user'

### ISSUE THREAD

**Issue by joshjacobson** [ipython-contrib/jupyter_contrib_nbextensions#686]
`jupyter contrib nbextensions install --user`
Returns:
```
[JupyterContribApp] CRITICAL | Bad config encountered during initialization:
[JupyterContribApp] CRITICAL | Unrecognized flag: '--user'
```
This also happens with --system.

```
ext_require_path = 'usability/codefolding/main'
try:  # notebook >= 4.2.0
    from notebook.nbextensions import enable_nbextension
    enable_nbextension('notebook', ext_require_path)
except ImportError:
    from notebook.nbextensions import EnableNBExtensionApp    
    EnableNBExtensionApp().enable_nbextension(ext_require_path)
```

```
from notebook.nbextensions import check_nbextension
check_nbextension('usability/codefolding')
check_nbextension('usability/codefolding/main.js')
```
Returns 'False'.

**Comment by juhasch** [comment]
Sorry, this is a typo in the documentation. There is a 's' too much:
```
jupyter contrib nbextension install --user
```
Will be fixed shortly.

**Comment by jcb91** [comment]
@juhasch good spot. Perhaps it would be worth making an alias with the `s` added as well...

**Comment by juhasch** [comment]
I guess this would be a good idea.

**Comment by ZhigangQi** [comment]
> Sorry, this is a typo in the documentation. There is a 's' too much:
> 
> ```
> jupyter contrib nbextension install --user
> ```
> Will be fixed shortly.

emm,Did the bug fix?I tried the command
`jupyter contrib nbextension install --user`and also tried`jupyter contrib nbextensions install --user`
They are not work at all.I  spent one day to feature it out ,but I still haven't solved it .Do you guys have any ideas ?
Thanks for your help .

**Comment by ZhigangQi** [comment]
I have figured it out .I read your documentation carefully .I found the problem .it was because I installed the jupyter_contrib_nbextensions ,but the nbextensions didn't exist in my `jupyter --data-dir`.
I copy the nbextensions folder to `jupyter --data-dir `,and then run the command `jupyter contrib nbextensions install --user `.It works .
Hope It will help the guys with same problem .

**Comment by philohistoria** [comment]
I encountered the exact same issue and my solution is:

`jupyter-contrib-nbextension install --sys-prefix`

**Comment by florianblume** [comment]
For me, I had to install `nbextensions` using `pip`. Installing it via `conda` did not put it in the `jupyter --data-dir` (thanks to @ZhigangQi I checked that folder).
