### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by jfbercher** [ipython-contrib/jupyter_contrib_nbextensions#698]
Hi @jcb91 
When migating, I had 2 issues

1.  the usuability directory survived and then nbextensions are duplicated in the dashboard
2.  the `notebook.json` was not migrated correctly. In `migrate.py`, line 89, old and new shouldn't be exchanched?  The mapping reads eg `('comment-uncomment/main', 'usability/comment-uncomment/main')` and is read as (old, new); Or do I miss something?

**Comment by jcb91** [comment]
1. Not sure why this happened, did you have multiple versions of the old install in different places? DId any of the other old directories survive, or just the `usability` one?
2. oh jeez, this is so stupid, you're absolutely right, I've mixed up old/new in the mappings

**Comment by jcb91** [comment]
2. hopefully fixed by #699
