### ISSUE TITLE
Download as HTML(.html)

### ISSUE THREAD

**Issue by bears34egc** [ipython-contrib/jupyter_contrib_nbextensions#700]
I've recently made some changes to my environment and now using Jupyter Notebook 4.2.1, I'm not able to download as HTML any longer. The message is:

> Could not import nbconvert: No module named shutil_get_terminal_size

When I try jupyter nbconvert --to html from a terminal I receive

> ImportError: No module named pre_codefolding

When I go to localhost:8888/nbextensions, pre_codefolding and usability appear but have "!" next to them not allowing me to check them? I assume this means I haven't properly installed these specific nbextensions? How could I do that manually, best?

**Comment by juhasch** [comment]
To disable an extension with a question mark, check the `disable configuration for extensions without explicit compatibility` box on the top of the page.

To remove the nbconvert preprocessor `pre_codefolding`, look for it in your `jupyter_nbconvert_config.py` or `jupyter_nbconvert_config.json` files in the Jupyter configuration directory.
You can find your Jupyter configuration directory using Python like this:
```Python
import jupyter_core.paths
 jupyter_core.paths.jupyter_config_dir()
```
About the `shutil_get_terminal_size`: See https://github.com/ipython/ipython/issues/9815
