### ISSUE TITLE
breakpoints extension not showing

### ISSUE THREAD

**Issue by peterswanson** [ipython-contrib/jupyter_contrib_nbextensions#718]
I have the nbextensions functionality working in jupyter notebook, but the breakpoints extension is not visible for selection.
![image](https://cloud.githubusercontent.com/assets/3860609/17534144/c27cc780-5e55-11e6-8691-643951fc4331.png)

**Comment by juhasch** [comment]
The breakpoint extension has not been updated for a while. You can try runtools, as it has a much more functions and is well maintained.

**Comment by jcb91** [comment]
@juhasch perhaps it might be a good idea to remove breakpoints, now that it's handled essentially by runtools?

**Comment by juhasch** [comment]
Yes, we should. It does not provide anything useful anymore.

**Comment by peterswanson** [comment]
does runtools have the ability to put a breakpoint in your code and debug?
That sounded like the biggest benefit of the breakpoint extension

**Comment by jcb91** [comment]
@peterswanson yes, runtools wraps the old breakpoints nbextension up with a bunch of other functionality like hiding inputs & outputs.

**Comment by peterswanson** [comment]
Maybe I have the old version of runtools then? I don't see any breakpoint
functionality in the version I am running:
[image: Inline image 1]

**Comment by juhasch** [comment]
PR #730 removes the breakpoints extension.

@peterswanson: runtools lets you select cells you want to run (green gutter marker). Deselect the cell you want to stop execution.
This is not a real breakpoint feature, however the old extension did not do much more than stopping at a given cell.

It might be worth investigating creating a real breakpoint extension, but this would be a different implementation.
