### ISSUE TITLE
Align Environment can't work with latex_envs extnesion

### ISSUE THREAD

**Issue by shanhaiying** [ipython-contrib/jupyter_contrib_nbextensions#719]
The latex environments such as align,align*, aligned, split etc. can't work well in theorem, lemma etc. latex environments.

Such as 

```
\begin{theorem}
$$
\begin{aligned}
f(x)&=\chi_{A_i}(x)\\
=&g(x)
\end{aligned}
$$
\end{theorem}

```

If we change code as the following:
`\begin{theorem}
$$
\begin{aligned}
f(x)&=\chi_{ A_i}(x)\\
=&g(x)
\end{aligned}
$$
\end{theorem}`

It works well.

**Comment by jcb91** [comment]
closing in favour of #720, which seems to be a slightly more detailed duplicate
