### ISSUE TITLE
Latex Enviroment - Figure Captions Not Numbering

### ISSUE THREAD

**Issue by MuriloHMoreira** [ipython-contrib/jupyter_contrib_nbextensions#732]
Hello guys,
Whenever I plot a figure and use the command :

`figcaption("Some Caption", label="fig:somelabel")`

It returns a Caption not showing the figure number but a bold text "Caption:"

![image](https://cloud.githubusercontent.com/assets/13623822/18128826/1b779414-6f5e-11e6-9a89-d40dadd7f8a4.png)

I also saw this in the html example.
Can anyone replicate this error?
If this is something that is not implemented yet, wouldn't it be a nice idea, as we already have the equation numbering working nicely?
Thanks for the attention.

**Comment by jfbercher** [comment]
The `figcaption` command included in `latex_envs` is a "bonus" (and Python specific) command that is not intended to number figures in the live notebook, but it is used for numbering these figures and put the appropriate caption when converting to latex. 

So automatic numbering of figures is not implemented and would be certainly interesting, but I do not see yet an easy/robust solution. 

There is also a new major version of latex_envs available  [here](https://github.com/jfbercher/jupyter_latex_envs).

**Comment by MuriloHMoreira** [comment]
Thanks for the quick response!
I'm working on your function and see if I can gamble to number nicely on the live notebook.
I already have added a new parameter on the figcaption function, this enabled to manually add the number of the figure.
I'm pretty sure that it will mess up the latex converter, and it will probably be not that much intelligent, but I'll see a more automatic way to do this.
I'll let you know any progress.
Best regards, Murilo.

**Comment by MuriloHMoreira** [comment]
Ok, my "final version".
I won't commit as this will probably cause more headaches then help, but I made some tweaks and this is my final version for the figcaption function:

`def figcaption(text, label=" "):

         figcaption.counter += 1
         disp = "<div class=caption><b> Fig." + str(figcaption.counter) + " : </b> %s</div>"
         display(HTML(disp
              % text.replace('\n', '<br>')))

figcaption.counter = 0`
 

This will add the counter atribute to the function, and "automatically" will count each time the figcaption function is called.
It takes the advantage of the notebook environment as you can easily restart the counting if you set manually the figcaption.counter to zero.

I'm sorry for this sluggish piece of code. This is my first try to contribute with a project and the fact that I only know basic python doesn't help.

Any comments and or suggestion please, just tell me.
Best regards, Murilo.

**Comment by jfbercher** [comment]
This is not really an issue but more a "feature request". 
The solution here is valuable but it would be better to find a way to number all figures and have something language independent. I do not know yet how to handle this but I keep it in mind. 
Anyway I think that this issue can be closed now.
