### ISSUE TITLE
code_prettify extension ijavascript on Windows

### ISSUE THREAD

**Issue by periscuelo** [ipython-contrib/jupyter_contrib_nbextensions#752]
First, congratulations and thanks for this extension.

Every time i try run the ijavascript kernel with code prettify enabled, i see this error:
```
CODE prettify extension
 Error: Error
Cannot find module 'js-beautify
```
I read the docs, said:
```
for ijavascript (in the root of your user tree = ~)
npm install js-beautify
```
But i try in `C:\Users\myUser\` with `npm install js-beautify` and `npm install -g js-beautify`
and still not working.

Can you help me? I use jupyter 4.2 in Windows 10 with node 6.5.0 and npm 3.10.6
Thanks.

**Comment by jfbercher** [comment]
@periscuelo Nodejs seems to not find the module. On Unix, it looks for a subdirectory `node_modules` on each directory in the current path. Is is possible that are you not executing from a descendant of your home directory? Can you look at [this answer on Stackoverflow](http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows) and perhaps try to set the  `NODE_PATH` environment variable? Thanks to report on your findings.

**Comment by periscuelo** [comment]
@jfbercher Thank you very much. Yes my problem is solved.
```
Add an environment variable called NODE_PATH and set it to %USERPROFILE%\Application Data\npm\node_modules (Windows XP), %AppData%\npm\node_modules (Windows 7/8/10), or wherever npm ends up installing the modules on your Windows flavor. To be done with it once and for all, add this as a System variable in the Advanced tab of the System Properties dialog (run control.exe sysdm.cpl,System,3). 
```
I set NODE_PATH in windows 10 and the error is gone.

Thanks again.
