### ISSUE TITLE
Drag and drop fails with jupyterhub

### ISSUE THREAD

**Issue by Chris7** [ipython-contrib/jupyter_contrib_nbextensions#756]
Drag and drop fails with jupyterhub because it constructs the url to send the data to:

`location.host + '/api/contents'...`

This does not send the request to the user's server (located at /user/xxx) and will cause a 405 error

**Comment by juhasch** [comment]
I don't know anything about Jupyterhub. 
Can you say how the correct url should look like exactly, and how to find that out inJavascript ?

**Comment by jcb91** [comment]
I think it should be possible to just use base.url as we do for config api.

**Comment by juhasch** [comment]
Can you try if it works now ?

**Comment by Chris7** [comment]
Thanks for getting around to this! I haven't tested it yet but I will let you know as soon as I do.

**Comment by jcb91** [comment]
I'm going to assume this worked. @Chris7 please reopen if not!
