### ISSUE TITLE
Limit output always printing warning

### ISSUE THREAD

**Issue by beangoben** [ipython-contrib/jupyter_contrib_nbextensions#763]
When using the  limit_output nbextension, any executed code cell prints out the warning message "limit_output extension: Maximum message size exceeded", independent of the char count for the output.

Below is a screenshot of the issue, where i configure a limit of 1000 chars and print "problem", still getting the warning when clearly it is less than 1k chars.

**Screenshot of issue:**
![screen shot 2016-10-13 at 2 48 53 pm](https://cloud.githubusercontent.com/assets/438135/19362355/7286fb4c-9154-11e6-8e2f-07ccb12bda8d.png)
**Setup:**
I am working off the jupyter/scipy-notebook docker image, installing the extensions and enabling them when building a new docker image.

**Comment by azjps** [comment]
I just independently stumbled across this and submitted PR #784.

**Comment by jcb91** [comment]
should hopefully be fixed by #784
