### ISSUE TITLE
Rendering of the code in the documentation 

### ISSUE THREAD

**Issue by fabianrost84** [ipython-contrib/jupyter_contrib_nbextensions#775]
I just went through https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html#install-javascript-and-css-files to install the extensions.
There, the command `jupyter contrib nbextension install --user` is wrongly rendered as `jupyter contrib nbextension install –user`. Please notice the difference in the dashes. Hence, copy-paste of the command does not work.

**Comment by jcb91** [comment]
Good spot. This is a result of syntax differences between md & rst which weren't taken into account when taking elements of the main README.md to create the docs sources, and which I missed when working on #773. I'll fix it there once I get time.

**Comment by jcb91** [comment]
should now be fixed by #773
