### ISSUE TITLE
Mentioning conda in jupyter_contrib_nbextensions/docs/source/install.rst

### ISSUE THREAD

**Issue by fabianrost84** [ipython-contrib/jupyter_contrib_nbextensions#776]
In `jupyter_contrib_nbextensions/docs/source/install.rst` the option to install the extensions via `conda install -c conda-forge jupyter_contrib_nbextensions` is missing. Is this on purpose?

**Comment by jcb91** [comment]
probably not, it's probably just that the readthedocs source was converted from an older version of the readme, before the conda channel was up & running. I'll add this correction to PR #773 when I get a chance

**Comment by jcb91** [comment]
Should now be fixed by #773, see [docs/source/install.md#conda](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/b6563a70041fef83423a5e5e11893c5548695e7f/docs/source/install.md#conda) for the updated text.
