### ISSUE TITLE
problem with python version

### ISSUE THREAD

**Issue by Chachni** [ipython-contrib/jupyter_contrib_nbextensions#782]
Hello, i've installed jupyter_contrib_nbextensions using:
pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master

It installed fine, however when i run "jupyter notebook", i get the error:
Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named jupyter_nbextensions_configurator

On the other hand, when i run "ipython3 notebook", there is no such error and i can see the Nbextensions tab.

In my jupyter notebook i can chose between python 2 and 3.

So as far as i understand, jupyter_contrib_nbextensions got installed into python3, but when i open jupyter, it reads from python2.7.

Could you please let me know what should i do so that calling "jupyter notebook" loads jupyter_contrib_nbextensions? Thank you very much for your help!

**Comment by Chachni** [comment]
I ended up just completely uninstalling and reinstalling jupyter and now everything works fine.

**Comment by jcb91** [comment]
> So as far as i understand, jupyter_contrib_nbextensions got installed into python3, but when i open jupyter, it reads from python2.

Yes, that seems likely. This would be down to the two python versions in use - it appears that the python version providing the `pip` you used for the install was not the same version which was providing your `jupyter notebook` command. By reinstalling, they both (base `jupyter` and the contrib nbextensions) get installed by the same `pip`, and hence into the same python version.
