### ISSUE TITLE
memoryleak:  endless spawning  of  conda-script.py

### ISSUE THREAD

**Issue by sniperlucian** [ipython-contrib/jupyter_contrib_nbextensions#799]
Symptoms:

After starting "jupyter notebook" notebook doesnt start, but here are endless creations of 
"c:\anaconda2\python.exe 'c:\anaconda2\Scripts\conda-script.py' 'info' '--json'"

Environment:

- win7 64 bit
- new install of anaconde python2.7 64bit
- conda update --all
- "jupyter notebook" works perfect

- install of nbextensions
- jupyter notebook broken (see symptoms)

![image](https://cloud.githubusercontent.com/assets/18550683/20634419/0c2483aa-b351-11e6-8c91-67d28ab9f4af.png)

Edit:

This happens now even with 

"conda update --all"    ;(

**Comment by jcb91** [comment]
Thanks for the report! I can't think of an obvious cause right now, but
conda recipe was recently updated, so that may be relevant. I assume you
installed notebook from conda; did you also install nbextensions from conda
(conda-forge channel), from pip, or from the repo?

**Comment by sniperlucian** [comment]
Wow - fast response ;)

First I installed with conda via conda-forge, than updated with pip. Still same behavior. 

Just about to reinstall anaconda and try sole with pip. Keep you updated.

**Comment by jcb91** [comment]
> After trying to install yapf via conda (forge) - conda is broken again.

Hmm. So the fact that this breaks when conda installing yapf makes me think this is perhaps a more general problem with conda or conda-forge, than necessarily specific to this repo. Does conda-installing yapf break things even without installing the nbextensions?

**Comment by sniperlucian** [comment]
I thought so - since both force conda to switch to conda-forge. But thinking about your question, it might be a valid point too. So I am just reinstalling again (like 5 time today ;).

**Comment by jcb91** [comment]
> since both force conda to switch to conda-forge

yeah, this is something I haven't really explored, but it seems that there should be a way to make a channel lower priority than defaults, to avoid exactly this kind of potential pitfall...

> So I am just reinstalling again (like 5 time today ;)

haha good luck!

**Comment by sniperlucian** [comment]
Just installed yapf again

conda install -c conda-forge yapf

and its broken again. Nothing to do with nbextensions. Guess issue can be closed. I allready posted the issue in anaconda - still didnt figure out yet how to make crosslinks. They are not nealy as fast in responding than here. ;)

Up for the next clean install .....

**Comment by jcb91** [comment]
weird! Ok, thanks for looking into it :)
