### ISSUE TITLE
Toc2 numbers elements in html export, contrary to parameters

### ISSUE THREAD

**Issue by NicolasWoloszko** [ipython-contrib/jupyter_contrib_nbextensions#808]
In the html export, toc2 automatically numbers the elements of the toc, even though this parameter is desactivated in the settings.

**Comment by NicolasWoloszko** [comment]
It also losses indentation

**Comment by jfbercher** [comment]
Yes, that is the default behavior when exporting to html. Note that you just have to press the "n" link in toc to turn off the numbering. That is not too bad. 

Anyway, it is easy to read the parameter and use it in the export step.

**Comment by jfbercher** [comment]
As far as the second comment is concerned, are sure that this is due to toc and not to standard html export?

**Comment by NicolasWoloszko** [comment]
> As far as the second comment is concerned, are sure that this is due to toc and not to standard html export?
I am no expert...

**Comment by jfbercher** [comment]
Hopefully fixed by #810
