### ISSUE TITLE
can I limit the output for just one cell?

### ISSUE THREAD

**Issue by foice** [ipython-contrib/jupyter_contrib_nbextensions#811]
let's say I want output to be limited in all cells, as a general rule for the notebook. I set a limit at 1000 chars. 

now I am in a cell in which I want to see more than the limit, say I want all or 2000 chars. is there  a way to "relax" the bound for that one cell I want to see more?

**Comment by jcb91** [comment]
In the current implementation, there's no way to do that. However, it would be pretty simple to implement, say by adding a value to the cell's metadata which would override the regular limit. I'll post back here once I get around to knocking something together.

**Comment by foice** [comment]
Thanks a lot for picking it up!

**Comment by jcb91** [comment]
OK, I've knocked together what I think should work as a a solution in PR #813. Let me know whether or not it works as you'd like

**Comment by jcb91** [comment]
should be fixed by #813
