### ISSUE TITLE
can I avoid initialization cells to be run on notebook load?

### ISSUE THREAD

**Issue by foice** [ipython-contrib/jupyter_contrib_nbextensions#812]
I think init cells are a great thing, however the frontend sometimes needs to be reloaded for stupid reasons, which might have to do with javascript or anything else, but do not require to reload data from disk (for instance).

with the current extension, every time I re-load the page all the initialization cells are reloaded. is there a way to avoid this reload?

**Comment by jcb91** [comment]
currently, this isn't implemented, but it seems like a reasonable use-case for a configurable option. I think it's plausible to want this to be different in different notebooks, so worth storing in notebook metadata as well as in server's nbconfig.

**Comment by jcb91** [comment]
so, on closer inspection, this seems to stem from the fact that the initialization cells are simply run on the event `kernel_ready.Kernel`, which fires both when a new kernel becomes ready, but also when the frontend fires up & determines that a pre-existing kernel is ready. This also makes for some race conditions involving notebook & kernel load times, which could be better handled. I can't think offhand of a better way of determining whether it's appropriate to run initialization cells once the frontend boots, so I think I'll just implement my previous suggestion, of having a configurable parameter determining this behaviour, overrideable on a per-notebook basis in metadata.

**Comment by juhasch** [comment]
I think it will be difficult to get consistent behavior of executing initialization cells only when a new kernel is started from the notebook frontend itself due to race conditions and the other things you mentioned. 

You could check however for the kernel ID, which is unique for each restart. So the logic would be only execute the cell if the kernel ID has changed.

**Comment by jcb91** [comment]
> You could check however for the kernel ID, which is unique for each restart. So the logic would be only execute the cell if the kernel ID has changed.

Neat, but we'd have no memory of whether the page has been loaded previously, so I think it'd still look like a 'new' kernel id. Unless we store it in local storage or something, perhaps. But, as you say, I think there are too many edge cases to expect that to work reliably.

**Comment by juhasch** [comment]
There is no memory in Javascript that persists reloading as far as I understand, so you have to store it in notebook or cell metadata.
Another solution would be simply to do the initialization cells like:
```Python
if '_is_initialized'  is not in locals():
  _is_initialized = True
  # do my intialization
```

**Comment by jcb91** [comment]
> There is no memory in Javascript that persists reloading as far as I understand

Well, there's [window.localStorage](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage) as in [select_keymap/main.js#L153](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/6c79a430e66ae92dc6746398189adfb5e48c3e2d/src/jupyter_contrib_nbextensions/nbextensions/select_keymap/main.js#L153), but even that's per-browser, so not really sufficient. I think your kernel-code is probably the neatest reasonably robust solution beyond only manually running them. Anyway, I've thrown together a PR to make the autorunning configurable on the basis that its default behaviour is just the same as what we have now anyway...
