### ISSUE TITLE
Zenmode parameter broken

### ISSUE THREAD

**Issue by akaufman10** [ipython-contrib/jupyter_contrib_nbextensions#821]
Hey, noob here, please let me know if I need to provide more info.

Jupyter Version : 4.2.3
Browser: Chromium 53.0.2785.143
OS: Ubuntu 14.04 lte

The "set zenmode on when notebook opens" parameter for zenmode does not work for me.  You can see the box checked in the picture below.

![zenmode](https://cloud.githubusercontent.com/assets/11140585/21430547/4e2550b0-c86c-11e6-874e-a203b0d05bf5.png)

The "Use builtin backgrounds in addition to any specified by URL" parameter does work, as do other extension parameters.

**Comment by jcb91** [comment]
hmm, strange, it works for me, and I can't yet think of an obvious reason it might break, given that the other parameters seem to work ok. If you load the notebook with the [javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) open, do you seen a log like

    zenmode -> false

or 

    zenmode -> true

? Similarly, when setting the parameter from the configurator with the console open, you should see a log like

    notebook.zenmode_set_zenmode_on_load -> false

if the configurator is doing its job properly...

**Comment by akaufman10** [comment]
Did a full reinstall of Jupyter and nbextensions, the parameter is working correctly now.
