### ISSUE TITLE
Unhandled error in API request

### ISSUE THREAD

**Issue by yunyundong** [ipython-contrib/jupyter_contrib_nbextensions#829]
Thanks in advance！
After I use pip comand the nbextensions, there is a tab 'nbextensions' in the dashboard of jupyter notebook, but it is empty. the error messages are as following:

```
 Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=02b0fa9f15d467766b623b8481484ab5c107ff7888963532
[I 15:02:19.526 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[E 15:02:22.572 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Users\yydong\AppData\Roaming\Python\Python27\site-packages\notebook\base\handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Program Files (x86)\Anaconda2\lib\site-packages\tornado\web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "C:\Users\yydong\AppData\Roaming\Python\Python27\site-packages\notebook\services\config\handlers.py", line 20, in get
        self.finish(json.dumps(self.config_manager.get(section_name)))
      File "C:\Users\yydong\AppData\Roaming\Python\Python27\site-packages\notebook\services\config\manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))
      File "C:\Program Files (x86)\Anaconda2\lib\site-packages\traitlets\config\manager.py", line 63, in get
        return json.load(f)
      File "C:\Program Files (x86)\Anaconda2\lib\json\__init__.py", line 291, in load
        **kw)
      File "C:\Program Files (x86)\Anaconda2\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\Program Files (x86)\Anaconda2\lib\json\decoder.py", line 367, in decode
        raise ValueError(errmsg("Extra data", s, end, len(s)))
    ValueError: Extra data: line 8 column 1 - line 19 column 2 (char 134 - 286)
[E 15:02:22.575 NotebookApp] {
      "Accept-Language": "zh-CN,zh;q=0.8",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "X-Xsrftoken": "2|68d92b93|67edac949f32f8cf9edcf6eca873fe0c|1483513049",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/tree?token=82931690aa189399b09e234352926f9d1d6695b82be8de34",
      "Cookie": "_xsrf=2|68d92b93|67edac949f32f8cf9edcf6eca873fe0c|1483513049; username-localhost-8888=\"2|1:0|10:1483513339|23:username-localhost-8888|44:ZjEzOGZlNjcyNDEyNDk2NjlmN2ZmMjBjNGY3ZjVjYTE=|2ff705e8da980f32af682f0922a2587ca9618b2ba5473f48484a7f114080ce94\""
    }
[E 15:02:22.578 NotebookApp] 500 GET /api/config/notebook?_=1483513339701 (::1) 5.00ms referer=http://localhost:8888/tree?token=82931690aa189399b09e234352926f9d1d6695b82be8de34
                                                                [I 15:11:31.240 NotebookApp] 302 GET /?token=02b0fa9f15d467766b623b8481484ab5c107ff7888963532 (::1) 1.00ms
```

**Comment by jcb91** [comment]
From the line in the traceback

    ValueError: Extra data: line 8 column 1 - line 19 column 2 (char 134 - 286)

this looks not like an error with any of the extensions, but a broken json config file which was being requested by something. From the error log line

    [E 15:02:22.578 NotebookApp] 500 GET /api/config/notebook?_=1483513339701 [...]

we find that it's the notebook config section which is failing to load. This config file is requested by  jupyter_nbextensions_configurator, which provides the nbextensions tab, but it's also loaded by the basic notebook page, so you'll need to fix it somehow. The error message indicates a syntax error:

The file in question will be one of the ones printed by the following python snippet:

```python
import os
from notebook.services.config import ConfigManager

for p in ConfigManager().read_config_path:
    conf_path = os.path.join(p, 'notebook.json')
    if os.path.exists(conf_path):
        print(conf_path)
```

Does that make any sense?

**Comment by yunyundong** [comment]
Thank you for your reply.


after running the python snippet:

> import

 os
from notebook.services.config import ConfigManager

for p in ConfigManager().read_config_path:
    conf_path = os.path.join(p, 'notebook.json')
    if os.path.exists(conf_path):
        print(conf_path)

there are three paths:
 >C:\Users\yydong\.jupyter\nbconfig\notebook.json
C:\Program Files (x86)\Anaconda2\etc\jupyter\nbconfig\notebook.json
C:\ProgramData\jupyter\nbconfig\notebook.json
>the contents of  "C:\Users\yydong\.jupyter\nbconfig\notebook.json":
{
  "load_extensions": {
    "codefolding/.": true, 
    "nbextensions_configurator/config_menu/main": true, 
    "codefolding/main": true, 
    "contrib_nbextensions_help_item/main": true
  }
}
>the contents of "C:\Program Files (x86)\Anaconda2\etc\jupyter\nbconfig\notebook.json":
{
  "load_extensions": {
    "nb_anacondacloud/main": true, 
    "nb_conda/main": true, 
    "nbpresent/js/nbpresent.min": true
  }
}
{
  "MarkdownCell": {
    "cm_config": {
      "lineWrapping": true
    }
  },
  "CodeCell": {
    "cm_config": {
      "lineWrapping": true
    }
  }
}

>the contents of "C:\ProgramData\jupyter\nbconfig\notebook.json"
{
  "load_extensions": {
    "nbextensions_configurator/config_menu/main": true, 
    "contrib_nbextensions_help_item/main": true
  }
}

I opened the each notebook.json and found there is a little contents, and I don't know how modify and fix them.

**Comment by jcb91** [comment]
So, your error is in `C:\Program Files (x86)\Anaconda2\etc\jupyter\nbconfig\notebook.json`, lines 8/9:

    }
    {

These aren't valid json, as the whole file should represent a single object. The contents should read

```json
{
  "load_extensions": {
    "nb_anacondacloud/main": true, 
    "nb_conda/main": true, 
    "nbpresent/js/nbpresent.min": true
  },
  "MarkdownCell": {
    "cm_config": {
      "lineWrapping": true
    }
  },
  "CodeCell": {
    "cm_config": {
      "lineWrapping": true
    }
  }
}
```

I have no idea how that happened, but most likely you attempted to edit by hand, I guess, unless two process somehow wrote to the same file simultaneously (I didn't that shouldn't be possible? Not sure). Anyway, there we are.

**Comment by jcb91** [comment]
Right, the conda tab is nothing to do with this repo, but is provided, I think, as a dependency of the conda notebook package. It sounds, in combination with #828, as though something has gone pretty fundamentally wrong somewhere, and I think your best bet might be a complete uninstall/reinstall of conda. Given #828 though, I'm lead to wonder whether you've installed conda somewhere that requires elevated (admin) privileges to write to? Not sure. Anyway, probably best to try starting from scratch...

**Comment by jcb91** [comment]
I'm going to close this now, as it seems not to have recurred, but please reopen if it's still causing problems!
