### ISSUE TITLE
Add yapf as a dependency?

### ISSUE THREAD

**Issue by jcb91** [ipython-contrib/jupyter_contrib_nbextensions#832]
Migrated from https://github.com/conda-forge/jupyter_nbextensions_configurator-feedstock/issues/10#issue-198835802, @michaelaye commented:

> I'm always met with the "yapf not installed" error when using the code prettyfier. Should it maybe made a dependency for this package?

**Comment by jcb91** [comment]
@jcb91 replied:

> mm, I suppose it could be. I'd hesitate to add it explicitly, but I guess the notebook runs on python anyway. Also, @jfbercher & I have recently been adapting code_prettify to be more configurable, so yapf isn't necessarily a dependency at all anymore for someone using a different formatter. Not sure, thoughts @juhasch, @jfbercher?

**Comment by juhasch** [comment]
I think if `yapf` is the default formatter, we should add it as dependency. If not, I think it will be sufficient to describe the dependencies in the configuration options.

We already have a growing list of dependencies, so I guess it would be good to find a way to have a way to limit this growth. This is also true e.g. for the latex_envs and highlighter extensions, that are listed as dependency.

**Comment by jcb91** [comment]
> I think if `yapf` is the default formatter, we should add it as dependency.

It remains the default, even after the refactor, so I guess we'll add it.

> it would be good to find a way to have a way to limit this growth

True, though  can't think of an obvious way to do that given that essentially we're attempting to provide a whole collection at once. Attempting to provide a selection, we'd end up building something of a package manager, which sounds a bit complicated for my taste 😟 

Anyway, for now, we add `yapf`, it's pretty lightweight anyway.

**Comment by jfbercher** [comment]
I am inclined to agree with @juhasch  that we should not add it to the list of dependencies, because (a) it is only used by `code_prettifier`and we should not install a dependency for every user that is only used by one extension, that some/many users may not select in the collection (b) the dependency is clearly stated in the documentation. I will try to look if it is possible to more clearly alert the user of the missing dependency in case he uses the extension without reading the doc.

**Comment by juhasch** [comment]
We definitely don't want to build a package manager.

The reason I came up with this is that I wanted to build conda packages locally. I failed because of the dependency on the highlighter extension, which failed due to a Windows vs. Linux path issue.

**Comment by jfbercher** [comment]
Perhaps `jupyter_highlight_selected_word` instead of highlighter`?

**Comment by jcb91** [comment]
>  I will try to look if it is possible to more clearly alert the user of the missing dependency in case he uses the extension without reading the doc.

Good idea @jfbercher, we could arrange the import such that it throws a more informative error message on failing to import, something like

```python
try:
    import yapf
except ImportError:
    raise Exception('better error message here')
```

> The reason I came up with this is that I wanted to build conda packages locally. I failed because of the dependency on the highlighter extension, which failed due to a Windows vs. Linux path issue.

Not quite sure what you mean here @juhasch ? 

> Perhaps `jupyter_highlight_selected_word` instead of `highlighter`?

So the `jupyter_highlight_selected_word` conda package failed to build? It should build ok on windows or linux, as it does on both via conda-forge. If not, I've clearly done something wrong - let me know! 😉

**Comment by jfbercher** [comment]
For the missing dependency, it will give something like that (for any kernel) : 

![prettify_unknown_js_lib](https://cloud.githubusercontent.com/assets/7596356/21728196/450e442a-d445-11e6-82e1-33502bc9b37d.png)
![code_prettify_unknown_python_lib](https://cloud.githubusercontent.com/assets/7596356/21728203/4c39bb44-d445-11e6-853f-083e562ea0e7.png)
I push the modifications for now to the WIP [here](https://github.com/jfbercher/code_prettify).

**Comment by jcb91** [comment]
Looks good to me @jfbercher

**Comment by jcb91** [comment]
also, with reference to the jupyter_highlight_selected_word conda build, I'm [having issues](https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock/pull/11#issuecomment-270968393) with getting the latest build version to upload to anaconda-cloud

**Comment by juhasch** [comment]
I get this error when building `jupyter_highlight_selected_word`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\juhasch\.conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 239, in install_nbextension_python
    destination=dest, logger=logger
  File "C:\Users\juhasch\.conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 213, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "C:\Users\juhasch\.conda\envs\_test\lib\site-packages\notebook\nbextensions.py", line 1027, in _maybe_copy
    shutil.copy2(src, dest)
  File "C:\Users\juhasch\.conda\envs\_test\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Users\juhasch\.conda\envs\_test\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\juhasch\\.conda\\envs\\_test\\lib\\site-packages\\jupyter_highlight_selected_word-0.0.6-py2.7.egg\\jupyter_highlight_selected_word\\static/highlight_selected_word'
```

**Comment by jcb91** [comment]
Thanks @juhasch for that. Right, I should have used `os.path`, it seems. I've hopefully fixed this in https://github.com/jcb91/jupyter_highlight_selected_word/issues/5, I'm [updating the conda-forge recipe now](https://github.com/conda-forge/jupyter_highlight_selected_word-feedstock/pull/3)

**Comment by jfbercher** [comment]
Perhaps this can be also closed, since the message for code_prettify and the highlight_selected_word path were updated?

**Comment by jcb91** [comment]
yep, closing this as we decided not to add another dependency, given that yapf may not actually be used, depending on the user's preferences.
