### ISSUE TITLE
where can i find the snapshots?

### ISSUE THREAD

**Issue by xxlatgh** [ipython-contrib/jupyter_contrib_nbextensions#840]
I'm trying to use snapshot function under tab widgets->save notebook with snapshots
where can I find these snapshots after I save the notebook? thanks!

**Comment by jcb91** [comment]
I'm afraid I don't really know what you mean here, but I suspect it's related to [ipywidgets](https://github.com/ipython/ipywidgets), which we don;t provide. You'd probably get better help by asking about this at https://github.com/ipython/ipywidgets/issues instead...
