### ISSUE TITLE
jupyter subcommand 'contrib' not availible if jupyter_contrib_nbextensions installed as user

### ISSUE THREAD

**Issue by JGobeil** [ipython-contrib/jupyter_contrib_nbextensions#848]
If jupyter_contrib_nbextensions is installed as user with
```
pip install --user jupyter_contrib_nbextensions
```
The second step failed when calling 
```
$ jupyter contrib nbextension install --user                                                      
jupyter: 'contrib' is not a Jupyter command
```
You can workaround this by directly calling the application 
```
python .local/lib/python3.6/site-packages/jupyter_contrib_core/application.py nbextension install --user
```
I don't know if this can be easily fix, but adding a note to the docs could be nice.

I'm under Arch Linux and I didn't test on other distributions.

**Comment by jcb91** [comment]
So, this presumably occurs because wherever scripts for per-user installs go, they're not on the path that the main `jupyter` command searches through. As a result, I think fixing it would require patching `jupyter_core` rather than here. Good idea to add it to docs though, they can always use additions! Feel free to PR something :)

**Comment by jcb91** [comment]
Also, to clarify, `pip install --user` is not directly analogous to the various `nbextension install --user` commands (which is annoyingly subtle, but I'm afraid I think here to stay. It's perfectly possible to use an `nbextension install --user` from a non-user pip package

**Comment by jcb91** [comment]
In your case @JGobeil it looks like the script should end up being installed into `~/.local/bin`, so if that's on your (shell) path, it should all work ok...

**Comment by JGobeil** [comment]
You're right. The script is in `~/.local/bin`. I will add this to my `$PATH`.
