### ISSUE TITLE
TOC not well rendered after html export

### ISSUE THREAD

**Issue by ggrrll** [ipython-contrib/jupyter_contrib_nbextensions#851]
Hi,

I am using 

`Name: jupyter-contrib-nbextensions` ,`Version: 0.2.3`
and 
`Name: nbconvert`,`Version: 5.1.1`

When I export my notebook to html (and open in safari ) the 'tab spacing' is missing, compared to the visualisation with usual notebook, as shown in the screenshots.

(also the sections number are automatically shown, even if I prefer not)

Thanks. 

<img width="382" alt="good_toc" src="https://cloud.githubusercontent.com/assets/15370425/22240925/766df3c2-e21d-11e6-8db1-5e740c4e14cf.png">
<img width="324" alt="html_toc" src="https://cloud.githubusercontent.com/assets/15370425/22240926/768a1a48-e21d-11e6-810f-9b05290d200d.png">

**Comment by jfbercher** [comment]
See if the discussion in #810 has not addressed these two points. 
What command do you use to export your notebook ?

**Comment by ggrrll** [comment]
I used ` jupyter  nbconvert --to html`

**Comment by jfbercher** [comment]
Can you try `jupyter nbconvert --to html_toc FILE.ipynb`?
(docs [here](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html))

**Comment by ggrrll** [comment]
It works on my browser thanks! —  so, I guess now it's just a problem of 
 [nbviewer](https://nbviewer.jupyter.org)  to render html correctly ? — still doesn't work well on nbviewer

**Comment by jfbercher** [comment]
Unfortunately, nbviewer actually fires the `--to html` conversion. 
You can embed the css for the static toc using eg 
```
from IPython.display import HTML

HTML("""<style>
.lev1 {margin-left: 80px}
.lev2 {margin-left: 100px}
.lev3 {margin-left: 120px}
.lev4 {margin-left: 140px}
.lev5 {margin-left: 160px}
.lev6 {margin-left: 180px}
</style>""")
```
I do know how to/ if it is possible to go further for now because nbviewer sanitizes embedded javascript (It did at least) for security reasons. For my part I rely on the static pages I generate and am happy with them :-)

**Comment by ggrrll** [comment]
yes, it works also on nbviewer! thanks again :)
