### ISSUE TITLE
2_to_3

### ISSUE THREAD

**Issue by jpiabrantes** [ipython-contrib/jupyter_contrib_nbextensions#856]
I have just installed jupyter_contrib_nbextensions but I can't find the 2to3 extension you talk about here: http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/code_prettify/README_2to3.html#

**Comment by jfbercher** [comment]
Perhaps that you have installed via conda? In such case, the `2to3` is not yet in the package and you 'll have to wait sometimes, or install directly the master branch of the repo via pip (see the general README for instructions).

**Comment by jcb91** [comment]
as jfbercher says, 2to3 hasn't been included in a numbered release either on pip or conda, yet

**Comment by jpiabrantes** [comment]
Ok yes I had installed it through conda.

**Comment by jcb91** [comment]
I'm putting together another release now, otherwise, you could build and install from the conda recipe in the repo if you're up for building recipes...

**Comment by jcb91** [comment]
New pypi release is up, conda-forge is waiting on `pypi.io`, which lags behind `pypi.python.org` by varying amounts of time.
