### ISSUE TITLE
[python 3.6] anaconda notebook extensions not working

### ISSUE THREAD

**Issue by nick-youngblut** [ipython-contrib/jupyter_contrib_nbextensions#858]
I'm trying to get jupyter_contrib_nbextensions working with the anaconda notebook extensions (https://docs.continuum.io/anaconda/jupyter-notebook-extensions). When I install the jupyter_contrib_nbextensions, the anaconda notebook extensions are no longer available (the 'conda' tab in Jupyter home is replaced with "Nbextensions". Here's my install process:

```bash
# Sever: Ubuntu 14.04 x86_64. 
# Anaconda (python3.5) install
wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
bash Anaconda3-4.2.0-Linux-x86_64.sh -b -p `pwd`"/anaconda3"
conda update conda

# jupyter extensions install
conda create -y -n test_py3 python=3
conda install -y -n test_py3  -c conda-forge jupyter_contrib_nbextensions
```

When I start up jupyter, the jupyter_contrib_nbextensions are working. However, the anaconda extensions (i.e., the 'conda' tab, and the ability to switch kernels) are gone. I've tried deleting my ~/.jupyter and ~/.ipython directories prior to the install, but that didn't help.

Any ideas on how I can get both Jupyter extensions working (contrib extensions and anaconda notebook extensions)? Thanks!

**Comment by jcb91** [comment]
Just to double check, if you create a new environment *without* the contrib nbextensions, do you still have the conda tabs working? E.g. using your above install script, but omitting the last line?

**Comment by nick-youngblut** [comment]
I tried the quick fix `conda install -y -n test_py3 nb_conda`, but got the following: 

~~~
UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package
~~~

Is Python 3.6 the issue? By default Python 3.6 is installed with anaconda (the version for python '3.5').

**Comment by jcb91** [comment]
wow, that's odd. I'm not really sure, but it looks from that as though the nb_conda package is not available for py36...

**Comment by jcb91** [comment]
But yeah, that potential incompatibility is something to ask the anaconda folks about, as I'm far from fully au fait with how they're packaging all their stuff...

**Comment by nick-youngblut** [comment]
I just created a conda environment with python v3.5.3, and your quick fix idea worked. It appears that python 3.6 isn't supported yet for nb_conda. Thanks for the help!

**Comment by jcb91** [comment]
Aha! Ok, I guess that makes sense, though tbh I can't imagine nb_conda isn't compatible with 3.6, it's probably just not been packaged yet. Might be worth dropping them a line to remind them at [Anaconda-Platform/nb_conda](https://github.com/Anaconda-Platform/nb_conda)

**Comment by jcb91** [comment]
Closing this as fixed, nb_conda is now available for py36
