### ISSUE TITLE
[large notebooks] toc2 fails when a notebook is too big?

### ISSUE THREAD

**Issue by simplygood** [ipython-contrib/jupyter_contrib_nbextensions#861]
I often find that some big notebooks cannot load toc2. Anyone has the same issue?

I use several nbextensions, but only toc2 is not loaded with big notebooks. Is there any way that I can track down? Java Script console does not reveal any error.

**Comment by jfbercher** [comment]
This should not happen (but may of course!). Can you make sure that you are not with a too old version (ie try to update to the last `jupyter_contrib_nbextension` -- @jcb91  released version 0.24 this afternoon) and try to provide an example notebook (eg publish it on a git) so that we can try to reproduce and investigate.

**Comment by jcb91** [comment]
This is almost certainly not specific to toc2 - see also #822, and https://github.com/jupyter/notebook/issues/2075

**Comment by simplygood** [comment]
I am using the latest anaconda version. Is there a quick fix for this?

**Comment by jcb91** [comment]
Ah, apologies, I've just re-read your report, and the fact that you don't see a javascript console error may mean that this is in fact a slightly different problem (the issues I referenced previously are down to a problem with the notebook proper, whereby the loading of large notebooks causes the requirejs calls for loading nbextensions to timeout, which _does_ show up in the console). Could you try loading the nbextension from a javascript cell magic, e.g.

```javascript
%%javascript
try {
  require(['base/js/utils'], function (utils) {
    utils.load_extension('toc2/tocc2');
  });
}
catch (err) {
  console.log('toc2 load error:', err);
}
```

and see if anything happens?

**Comment by simplygood** [comment]
Sorry for the confusion, but I do have an error in the console:
`Exception in event handler for notebook_loaded.Notebook ReferenceError: initAutosScroll is not defined`

@jcb91 If I try your code, I get "`Uncaught (in promise) Error: Script error for "nbextensions/toc2/tocc2"`" It must be an obvious error because there is no tocc2.js.

**Comment by jcb91** [comment]
Interesting, does the initAutoScroll actually have the double `s`? Only that looks like it's a typo. Could also be a problem with strict mode if it's missing a `var` declaration. 

Haha, yes, I clearly didn't test what I'd posted at all, apologies! That require statement should have been for `toc2/main`, I think...

**Comment by simplygood** [comment]
I disabled AutoScroll and toc2 now works! As @jcb91 pointed out, initAutosScroll should be initAutoScroll, I guess.

**Comment by simplygood** [comment]
It's still mysterious why that typo does not affect when a notebook is small.

**Comment by jcb91** [comment]
I would guess it's because in small notebooks, the event is triggered before the callback is bound, so the function with the typo never actually gets executed...

**Comment by jcb91** [comment]
I also guess that toc2 gets affected because an unhandled exception in one callback prevents execution of any other callbacks bound to the same event afterwards.

**Comment by simplygood** [comment]
I created a pull request for fixing AutoScroll: #864
