### ISSUE TITLE
installation with pip not working

### ISSUE THREAD

**Issue by yogabonito** [ipython-contrib/jupyter_contrib_nbextensions#865]
I tried to do
    `pip3 install jupyter_contrib_nbextensions`
as suggested [here](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html#pip) but it failed, printing 
    `ImportError: No module named 'packaging'`.

I noticed that the command is creating a directory called `python3.4` in `/home/USERNAME/.local/lib/` which renders pip3 unusable. Trying to use pip3 (even without options and arguments) then leads again to the `ImportError`:
```
$ pip3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/USERNAME/.local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named 'packaging'
```

When I delete the newly created `python3.4`-directory, pip3 is working again.
Any solutions how I can install the notebook extensions? Any help is highly appreciated! :)

**Comment by jfbercher** [comment]
Seems to be a problem with pip, not with these nbextensions. 
From [this issue](https://github.com/pypa/setuptools/issues/937), it seems that upgrading pip fixes the issue. You can reinstall pip using get-pip.py or reinstall with `python -m pip install -U pip`.

**Comment by yogabonito** [comment]
Thanks a lot for your feedback @jfbercher!
I won't, however, try this out yet because of [this warning](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py). My first approach will be an OS-upgrade.
Thank you for clarifying that pip seems to cause the problem!
