### ISSUE TITLE
ToC2: not able to turn section numbering off

### ISSUE THREAD

**Issue by RinaldoB** [ipython-contrib/jupyter_contrib_nbextensions#870]
Hi,

there is an option to turn automatic section numbering off in Table of Contents (2) extension. This option has no effect for me and section numbers still appear.

|  |  |  | 
| --- | --- | --- |
| python | 2.7.12 |  |
| conda | 4.3.8 |  |
| jupyter_client | 4.3.0   |  |
| jupyter_console | 4.1.1  | |
| jupyter_contrib_core | 0.3.0 | conda-forge |
| jupyter_contrib_nbextensions | 0.2.3 | conda-forge |
| jupyter_core | 4.1.0  | |

**Comment by jfbercher** [comment]
The option in the `nbextension_configurator` is global and applied when the notebook is *created*. For each notebook, numbering can be toggled by clicking the "n" link in the toc2 window (and this state stored in the notebook metadata). Does this make sense or is there something else?

**Comment by RinaldoB** [comment]
Thanks, disabling the section numer in the ToC window worked.

I opened an existing notebook, after turning the ToC2 extension on, and as you say, it must have stored the default state (section numbering on). I suggest to turn the "Automatically number notebook's sections" option off at default.

**Comment by jfbercher** [comment]
You can easily change the option globallly using the `nbextension_configurator` available typically at `http://localhost:8888/nbextensions`. 
For the default value, I prefer to use numbering by default, and since I am the author... :-)

**Comment by jcb91** [comment]
does this need an update to docs, or should we close?

**Comment by jfbercher** [comment]
I think that the docs clearly indicate that the default option can be set with the configurator and that one can toggle this per notebook, so we can close.
