### ISSUE TITLE
Floating TOC not working on rotated screen 

### ISSUE THREAD

**Issue by ggrrll** [ipython-contrib/jupyter_contrib_nbextensions#893]
Hi,

the TOC extension doesn't show the floating window when I rotate my screen by 90 degrees.

(find attached the details of my screens)

Thanks for your support.

![screen shot 2017-02-16 at 14 57 00](https://cloud.githubusercontent.com/assets/15370425/23024221/81b22192-f459-11e6-9e8f-819398cd2c76.png)

**Comment by ggrrll** [comment]
yeah...thanks - didn't think that simply un-docking/docking would solve the issue

**Comment by jfbercher** [comment]
This is due to the fact that toc position is stored in pixel units and do not follow changes of screen size or changes of resolution. It might be possible to rewrite this as relative dimensions (someday).
