### ISSUE TITLE
[init_cell] cell toolbar doesn't persist on notebook save / reload

### ISSUE THREAD

**Issue by radekosmulski** [ipython-contrib/jupyter_contrib_nbextensions#910]
I have initialization cells enabled in configurator. On a notebook, I go to view > cell toolbar > initialization cell to enable the cell toolbar.

I save the notebook. I reload. The toolbar is no longer visible. 

If I follow the above steps, but with the metadata toolbar, once enabled on a notebook it is persisted through saving / reloading.

**Comment by jcb91** [comment]
I assume this is down to the notebook code which initializes the cell toolbar running before the nbextension registers its new toolbar. I'll have a look.

**Comment by jcb91** [comment]
I've had a go at implementing this in #912 - let me know if you get a chance to try it :)
