### ISSUE TITLE
Drag and Drop doesn't work in Firefox

### ISSUE THREAD

**Issue by kaz4ikeda** [ipython-contrib/jupyter_contrib_nbextensions#914]
Drag and Drop works in IE and Edge but not in Firefox52 on Windows10 64bit latest.  The checkbox in configurator tab is checked and javascript console shows "Loading extension: dragdrop/main", but drag-and-drop of an image file responds nothing.

**Comment by juhasch** [comment]
Seems the Firefox API changed slightly. Can you try the fix in #915 ?

**Comment by kaz4ikeda** [comment]
#915 successfully got arround the issue. Thank you, juhasch.
