### ISSUE TITLE
Tab-complete window appears under scratchpad.

### ISSUE THREAD

**Issue by Jessime** [ipython-contrib/jupyter_contrib_nbextensions#916]
If I open the scratchpad window and try to use the tab complete, it only becomes visible after I close the scratchpad. For example if I do:

```
inspect.<tab>
```

it seems like it doesn't do anything. But if I close the scratchpad, my notebook looks like:

![screenshot from 2017-03-15 13-53-26](https://cloud.githubusercontent.com/assets/8493770/23963405/8cc176c6-0987-11e7-8f55-c0fd1dbfc4f9.png)

Is it possible to change the window ordering so that the tab-complete window is visible and usable?

**Comment by jcb91** [comment]
Aha! Nice spot. This is just a [z-index](https://developer.mozilla.org/en/docs/Web/CSS/z-index) issue, so should be fixable fairly easily I think. I'll open a PR at the original scratchpad repo...

**Comment by jcb91** [comment]
actually, this appears to have been raised there already: https://github.com/minrk/nbextension-scratchpad/issues/5

**Comment by jcb91** [comment]
ok, I've submitted a PR https://github.com/minrk/nbextension-scratchpad/pull/12. You could give that a try, if you fancy (essentially just two numbers changed in the scratchpad.css file). If it works & is merged there, I'll pull it in here also.

**Comment by Jessime** [comment]
Oh, I didn't realize that the extensions (some/all?) had their own separate repos! Thanks for taking care of this so quickly. :)

**Comment by jcb91** [comment]
> Oh, I didn't realize that the extensions (some/all?) had their own separate repos!

Most don't, but a few got included in the collection after starting life separately, and in those cases it helps (for me at least!) in keeping track of whats going on if we keep the two in step by adding commits to the individual repos first. Not a massive deal though.

> Thanks for taking care of this so quickly. :)

de nada :smile:
