### ISSUE TITLE
codefolding - when enabled Ctrl+X does not wrk

### ISSUE THREAD

**Issue by carbolymer** [ipython-contrib/jupyter_contrib_nbextensions#926]
When `codefolding` extension is enabled, cutting of text by Ctrl+X does not work in Google Chrome.

**Comment by juhasch** [comment]
Thanks for reporting. It should be `Alt-f` by default.
You can either apply the fix in PR #927 or change the hotkey in the nbextensions configurator, in case you have installed it.

**Comment by carbolymer** [comment]
Thanks for the response. That's weird. I have `Alt-f` there by default, but when I've set the hotkey to the `Alt-f` again, it started working properly.

**Comment by jcb91** [comment]
@carbolymer it's a result of a limitation of the configurator - the default values in the yaml declaration are only used to show the user what the JavaScript would use by default, they don't actually do anything. As a result, if they disagree, the javascript will win unless an explicit config value is set...

**Comment by juhasch** [comment]
Fixed by #927.
