### ISSUE TITLE
Code folding disables ctrl-x

### ISSUE THREAD

**Issue by rosenfeldamir** [ipython-contrib/jupyter_contrib_nbextensions#932]
After enabling the code folding extension I found out that I can no longer use the ctrl-x shorcut to cut a piece of text. The mouse context menu works, as does ctrl-x in any other application or chrome text field.

**Comment by jcb91** [comment]
duplicate of #926, fixed in repo master. If you don't want to install from repo master, you can also fix this by changing the shortcut in the configurator (see #926 for details)
