### ISSUE TITLE
[feature request] collapsible traceback

### ISSUE THREAD

**Issue by andreas-h** [ipython-contrib/jupyter_contrib_nbextensions#935]
I like the look of the skip_traceback extension.  However, it would be useful if the traceback information would not be lost altogether.  I think it would be great if there were a small `+` next to the traceback, with which one could (un)collapse the traceback information.  The default behaviour should be the condensed display of skip_traceback.

**Comment by jcb91** [comment]
Sounds like a good idea, and not too difficult to implement. Thanks for the suggestion :+1:

**Comment by andreas-h** [comment]
While we're at it:  How about adding a button which, when clicked, copies the full traceback into the clipboard, so that I don't have to select the traceback (which can involve scrolling) for copy-pasting it?

**Comment by jcb91** [comment]
this would presumably be visible in the collapsed version?

**Comment by andreas-h** [comment]
Optimally, in both collapsed and 'original' view.  I personally find it
cumbersome to select potentially more than one screenful of traceback
with the mouse.

**Comment by juhasch** [comment]
I think a Browser will only let you access the system clipboard if you use the "official" hotkeys (e.g. Ctrl+C).
The only thing a custom button could do is to select the complete traceback, and then you can copy it using the standard clipboard copy operation.

**Comment by jcb91** [comment]
Sort of. You can also call `document.execCommand('copy')` to copy selected text, as long as it's run in response to a user action. You can couple this with an off-screen text area created for the purpose to emulate copying text. I've a working solution in place, which I'll post shortly...
