### ISSUE TITLE
Enable codefolding on regular python files

### ISSUE THREAD

**Issue by cipri-tom** [ipython-contrib/jupyter_contrib_nbextensions#938]
I guess the name pretty much says it all.
Instead of just the notebooks, allow regular python (or other languages) to support code folding.

Thank you!

**Comment by jfbercher** [comment]
I think that @juhasch has already implemented this. 
Isn't it what does codefolding extension?

**Comment by jcb91** [comment]
I think @cipri-tom means in the notebok's file editor view, rather than just in the notebook view? Makes sense, I guess!

**Comment by cipri-tom** [comment]
> Instead of just the notebooks, ...

Indeed, I meant the file editor view! Surely it's just a matter of config, but I can't find out where :(.

**Comment by jcb91** [comment]
> Surely it's just a matter of config, but I can't find out where :(

Ok, that makes sense, I think. It'll require a bit of js too, and in fact it may be easier to just make another separate extension. Not much work though, so I'll try to push an update in the next day or so...

**Comment by juhasch** [comment]
You can try putting this in your `custom.js`:
```Javascript

if (IPython.editor !== undefined) {

    define([
        'base/js/namespace',
        'jquery',
        'codemirror/lib/codemirror'
    ], function (IPython, $, CodeMirror) {

    var load_css = function (name) {
        var link = document.createElement("link");
        link.type = "text/css";
        link.rel = "stylesheet";
        link.href = require.toUrl(name, 'css');
        document.getElementsByTagName("head")[0].appendChild(link);
    };

    var initGutter = function() {
    IPython.editor.codemirror.setOption('foldGutter',{rangeFinder: CodeMirror.fold.indent });
    IPython.editor.codemirror.setOption('gutters', [  "CodeMirror-foldgutter"]);
    }

    load_css('codemirror/addon/fold/foldgutter.css');
    load_css('nbextensions/codefolding/foldgutter.css');
    require([        'codemirror/addon/fold/foldcode',
        'codemirror/addon/fold/foldgutter',
        'codemirror/addon/fold/brace-fold',
        'codemirror/addon/fold/indent-fold'], initGutter);
    });
}
```

@jcb91 : Feel free to put this into an extension, I won't have time for it anytime soon.

**Comment by cipri-tom** [comment]
Wow, that was fast ! Thank you @juhasch and  @jcb91 !!

I'm still noob: I have installed my extensions via `pip install` or via `conda install` (not sure which). Can I just update to get it, or I need to have them installed from the git repo ?

**Comment by jcb91** [comment]
The PR has been merged into the repo master, but isn't part of any release made to pypi or conda-forge yet, so you'll need to install from the repo for now, I'm afraid
