### ISSUE TITLE
Notebook v5

### ISSUE THREAD

**Issue by rgbkrk** [ipython-contrib/jupyter_contrib_nbextensions#939]
Is there a plan for Notebook v5? I'm trying out the release candidate for Notebook v5 and getting an error with the configurator.

<img width="1440" alt="screen shot 2017-04-03 at 9 29 34 am" src="https://cloud.githubusercontent.com/assets/836375/24619787/16711bac-1850-11e7-8257-d71042e6320c.png">

**Comment by juhasch** [comment]
I have been running notebook 5.0.0dev for a while and did not experience any problems.
Do you see the the extension at http://localhost:8888/nbextensions/nbextensions_configurator/config_menu/main.js ?

**Comment by rgbkrk** [comment]
I just noticed that I installed this extension for Python2 and not Python3 (my notebook is running with 3).

**Comment by rgbkrk** [comment]
Thanks @juhasch
