### ISSUE TITLE
Error executing Jupyter command 'contrib'

### ISSUE THREAD

**Issue by Time1ess** [ipython-contrib/jupyter_contrib_nbextensions#941]
I'm trying to install `jupyter_contrib_nbextensions`First I install the python package with command `pip3 install jupyter_contrib_nbextensions --user`, it works fine.
But when I install javascript and css files with command `jupyter contrib nbextension install --user`, I get this error`Error executing Jupyter command 'contrib': [Errno 2] No such file or directory`.
I've tried to reinstall jupyter and this extension, it's still not ok.
System: macOS Sierra 10.12.4
Python: Python 3.6.1
IPython: IPython 5.3.0
Jupyter: Jupyter 4.3.0

**Comment by jcb91** [comment]
Hmm, that's a little odd. Could you post the entire traceback of the command?

**Comment by jcb91** [comment]
PS, I take it that this isn't a conda installation, given your pip usage?

**Comment by Time1ess** [comment]
The entire traceback of the command:
> $ jupyter contrib
    Error executing Jupyter command 'contrib': [Errno 2] No such file or directory

pip usage:
> $ pip3 --version
   pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

> $ pip3 show ipython
    Name: ipython
    Version: 5.3.0
    Summary: IPython: Productive Interactive Computing
    Home-page: http://ipython.org
    Author: The IPython Development Team
    Author-email: ipython-dev@scipy.org
    License: BSD
    Location: /Users/youchen/Library/Python/3.6/lib/python/site-packages
    Requires: pexpect, pygments, prompt-toolkit, pickleshare, setuptools, simplegeneric, appnope, decorator, traitlets

> $ pip3 show jupyter
    Name: jupyter
    Version: 1.0.0
    Summary: Jupyter metapackage. Install all the Jupyter components in one go.
    Home-page: http://jupyter.org
    Author: Jupyter Development Team
    Author-email: jupyter@googlegroups.org
    License: BSD
    Location: /Users/youchen/Library/Python/3.6/lib/python/site-packages
    Requires: qtconsole, ipykernel, nbconvert, jupyter-console, ipywidgets, notebook

> $ pip3 show jupyter_contrib_nbextensions
    Name: jupyter-contrib-nbextensions
    Version: 0.2.6
    Summary: A collection of Jupyter nbextensions.
    Home-page: https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
    Author: ipython-contrib and jupyter-contrib developers
    Author-email: jupytercontrib@gmail.com
    License: BSD
    Location: /Users/youchen/Library/Python/3.6/lib/python/site-packages
    Requires: ipython-genutils, nbconvert, psutil, pyyaml, jupyter-core, jupyter-latex-envs, notebook,     jupyter-highlight-selected-word, jupyter-nbextensions-configurator, tornado, traitlets, jupyter-    contrib-core

**Comment by jcb91** [comment]
Hmm, seems like the contrib command isn't on the path for some reason. Could you try a `sudo updatedb`, and then post the output of

    sudo locate jupyter-nbextension

and then 

    sudo locate jupyter-contrib


it seems this may be related to issues mentioned in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/713#issuecomment-261663024

**Comment by Time1ess** [comment]
Yeah #713 solved my issues.

It turns out that I firstly install jupyter with `sudo pip3 install jupyter`, it's installed to a system path, but later I install jupyter_contrib_nbextensions with `pip3 install --user jupyter_contrib_nbextensions`, it's installed to `~/Library/Python/3.6/bin`, but this is not included in my `PATH`, so this error occurs.

What I've done is uninstall all related packages about `jupyter` and reinstall with `pip3 install --user *` and update my `PATH`, now it works fine.

@jcb91 , Thanks.

**Comment by jcb91** [comment]
no problem, glad you got it sorted :smile:

**Comment by christienatashiaarchie** [comment]
Hi may I know the precise step by step how to uninstall the related Jupiter and then reinstall and update the path, i am quite lost

**Comment by paulrougieux** [comment]
Another solution if you get this issue on windows is to cd to the location of the jupyter nbextension folder as explained here https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1416

```
open cmd to install manually
cd .\Python\Python35\Lib\site-packages\jupyter_contrib_nbextensions
python application.py install
jupyter notebook
```

**Comment by segsell** [comment]
**Update: August, 2023**

Here's what solved the problem for me:

```python
conda update --all
conda install -c anaconda notebook 
conda install -c conda-forge jupyter_contrib_nbextensions 
```
Then, ```jupyter contrib nbextension install --user``` executes without error.

Now you can install and enable jupyter extensions (e.g. black) like this:
```python
jupyter nbextension install https://github.com/drillan/jupyter-black/archive/master.zip --user
jupyter nbextension enable jupyter-black-master/jupyter-black
```
