### ISSUE TITLE
[notebook 5.0] tree-filter does not work

### ISSUE THREAD

**Issue by iteratorlee** [ipython-contrib/jupyter_contrib_nbextensions#945]
The tree-filter extension does not work. I think the function 'load_ipython_extension' is loaded when a ipynb file is opened rather than when the notebook home page is loaded. What should I do if I still wanna implement a tree filter?

**Comment by juhasch** [comment]
For me the tree filter works as expected at the home page.
Can you give some more background on this ?
Especially OS, notebook and nbextensions version.

**Comment by iteratorlee** [comment]
Ubuntu 16.04, notebook 4.4.1, widgetsnbextension 2.0.0.
Thanks

**Comment by iteratorlee** [comment]
terminal log as follow:
```
[W 00:32:49.924 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v
=20170406003218 (127.0.0.1) 72.61ms referer=http://localhost:8888/notebooks/Untitled4.ipynb
```
browser(Firefox) console as follow:
```
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
```
I don't konw if I install wrong versions of some packages

**Comment by jcb91** [comment]
@iteratorlee the widgetsnbextension package is separate to this repo, and provides `Interactive HTML widgets for Jupyter notebooks`. To get your version of this repo, try

```bash
python -c "import jupyter_contrib_nbextensions; print(jupyter_contrib_nbextensions.__version__)"
```

in the terminal.

> I think the function 'load_ipython_extension' is loaded when a ipynb file is opened rather than when the notebook home page is loaded.

The `load_ipython_extension` function can be called from each of the views:
 * `notebook` view (regular notebook interface)
 * `edit` view (file editor)
 * `tree` view (file browser, homepage, also called 'dashboard')

Could you run us through the sequence of steps you took to try to use the nbextension, starting from installing this repo? Could you also let us know the output of

```bash
jupyter nbextension list
```

please?

**Comment by iteratorlee** [comment]
I try to install the tree-filter extension as bellow:
First I install notebook using pip.
Then I cloned this repo. But I did not install all the extensions. I enter the directory /tree-filter/ and run command as bellow:
```
pip install notebook
sudo ~/.local/bin/jupyter-nbextension install /path/to/tree-filter
jupyter nbextension enable tree-filter/index
```
Then I start notebook:
`jupyter notebook`
The output of 'jupyter nbextension list' is as bellow:
```
Known nbextensions:
  config dir: /home/iterator/.jupyter/nbconfig
    notebook section
      tree-filter/index  enabled 
      - Validating: OK

```

**Comment by jcb91** [comment]
Hmm, ok, well that sounds like it should have worked ok. the most obvious difference is that you're using notebook 5.0, and not all nbextensions have been tested with 5.0 yet, so it's possible an API change  in notebook will need adjusting to in the nbextension code. Could you check the browser's 
[javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) to see whether there are any error or warning messages there, please?

**Comment by iteratorlee** [comment]
![default](https://cloud.githubusercontent.com/assets/17424423/24988596/9088c2e6-2039-11e7-9e9d-aad1883d15e4.PNG)
The js console is as above.
By the way, I have tried notebook 4.x, but the extension still did not work...

**Comment by juhasch** [comment]
@iteratorlee: Do you feel comfortable modifying Javascript files ?
You could add a `console.log('message')` type message in the extension to see if it is called at all, or when it fails. Starting with the line before the last `});` at the end of the file.
The extension should be accessible at http://127.0.0.1:8888/nbextensions/tree-filter/index.js

**Comment by iteratorlee** [comment]
I added a `console.log("sbsbsbsbsbsb")` at the begin of the function `load_ipython_extension`. And then I found that:
- The tree page is still as below:
![image](https://cloud.githubusercontent.com/assets/17424423/25028900/bc2f1c86-20ea-11e7-95a1-c0fa27793147.png)
- But when I open a python3 notebook (untiltled.ipynb), the console message is as below:
![image](https://cloud.githubusercontent.com/assets/17424423/25028917/e4a83eae-20ea-11e7-9d26-0c4e9a12d4f9.png)
Obviously the extension is called when the ipynb file is opened, so confusing...

**Comment by juhasch** [comment]
Thanks, this makes it clear. The command
`jupyter nbextension enable tree-filter/index` falsely enables the extension for the notebook instead of the tree. This can also be seen in your output from `jupyter nbextension list` above:
```
Known nbextensions:
  config dir: /home/iterator/.jupyter/nbconfig
    notebook section
      tree-filter/index  enabled 
      - Validating: OK
```
It should list:
```
   tree section
      tree-filter/index  enabled 
      - Validating: OK
```

You can file an issue at https://github.com/jupyter/notebook or use the nbextensions_configurator which detects the extension type from the supporting yaml file.

Closing as Jupyter notebook deficiency.

**Comment by jcb91** [comment]
Ah, it's so obvious once it's pointed out! :smile:

**Comment by jcb91** [comment]
Also, for notebook master at least, you can specify the section from client as in

    jupyter nbextension enable --section=tree tree-filter/index

**Comment by juhasch** [comment]
Good to know, thanks. I had not seen this before. Maybe we should add a warning message when the extension is loaded in the wrong place.

**Comment by jcb91** [comment]
> Maybe we should add a warning message when the extension is loaded in the wrong place.

So check in tree-filter that we are actually in the tree view, otherwise warn, that kind of thing?
