### ISSUE TITLE
The third step doesn't work

### ISSUE THREAD

**Issue by Mulf** [ipython-contrib/jupyter_contrib_nbextensions#956]
I follow the instructions(to install it on windows,) but when I move to the command in the step 3:
`jupyter nbextension enable <nbextension require path>`

it shows:

> C:\Users\Linfeng>jupyter nbextension enable C:\Users\Linfeng\Desktop\tensor\Jupyter
Enabling notebook extension C:\Users\Linfeng\Desktop\tensor\Jupyter...
      - Validating: problems found:
        - require?  X C:\Users\Linfeng\Desktop\tensor\Jupyter

What is wrong here ?

**Comment by jfbercher** [comment]
The `<nbextension require path>` is the name of the extension directory + the javascript filename (without the .js extension). Look again at the example [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions#3-enablingdisabling-extensions). Alternantively, you can use the  jupyter_nbextensions_configurator as indicated in the link above.
