### ISSUE TITLE
Add infos about new features to the juypter newsletter?

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#959]
It seems you can add snippets to the juypter newsletter and I think releases of this this project would be a nice fit: https://github.com/jupyter/newsletter/issues

**Comment by jcb91** [comment]
You mean something like the change summary for each release, we wrap into some text to go into the newsletter? Sounds reasonable to me. Would you like to give it a go?

**Comment by janschulz** [comment]
Re 0.2.7:

# New release of jupyter_contrib_nbextensions (0.2.7)

jupyter_contrib_nbextensions is a collection of Jupyter notebook extensions which add functionality like a a table of content, code formatter for R and Python, a scratchpad, and much more to the jupyter noptebook.

The latest release (0.2.7) adds a variable inspector for Python and R and include various enchancements and bugfixes. 

Picture: http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/varInspector/README.html
Link: http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/

**Comment by jcb91** [comment]
Typo noptebook->notebook, but looks good to me :+1:

**Comment by jfbercher** [comment]
Very nice.  :+1:
@janschulz you push that as a proposal to https://github.com/jupyter/newsletter/issues?

**Comment by janschulz** [comment]
Added it upstream: https://github.com/jupyter/newsletter/issues/65

**Comment by juhasch** [comment]
Very nice, thank you. 👍
