### ISSUE TITLE
Linux user reporting codefolding affecting cut

### ISSUE THREAD

**Issue by rgbkrk** [ipython-contrib/jupyter_contrib_nbextensions#961]
With the codefolding extension enabled, cut text doesn't work (ctrl-x). This is on Jupyter Notebook v5.

/cc @rdblue

**Comment by rdblue** [comment]
Thanks @rgbkrk! I'm on ubuntu and running chrome, which is why cut is CTRL+X. The default hotkey to fold/unfold is ALT+F, which opens chrome's menu for me. When I set this to something that doesn't conflict, like CTRL+SHIFT+F, cut text works again.

**Comment by jcb91** [comment]
this is/was a bug which has a fix in the repo master, but hasn't been pushed to a pypi/conda release yet - see #927 for the fix, and #926 for the original issue. This is a pretty annoying and subtle bug (difficult for most people to identify where it comes from), so I think it might be worth adding a pypi/conda release to include the fix soon...

**Comment by rgbkrk** [comment]
Is there a hotfix way to get around this?

**Comment by jcb91** [comment]
Yeah, if you are indeed running into #926 as it sounds, what's going on is that the default hotkey in the nbextension js is actually `ctrl-x`, breaking native cut support, but the default is declared in the yaml as `alt-f`, which is what the configurator will show. As a hotfix, you should be able to just set the hotkey to something else, then set it back to `alt-f` explicitly using the configurator. Of course, this would override your native open-file-menu shortcut, so you may wish to try something other than `alt-f`, as it seems @rdblue already tried. I'm putting together a 0.2.7 release for this evening, hopefully.

**Comment by jcb91** [comment]
ok, the fix is included in release 0.2.7, which should now be live on pypi & conda-forge, so I'm going to close this, but (of course), please reopen if it turns out I've misdiagnosed!

**Comment by juhasch** [comment]
Thanks a lot for pushing a new release. :+1:
