### ISSUE TITLE
Freeze: cell color should be customizable

### ISSUE THREAD

**Issue by shingo78** [ipython-contrib/jupyter_contrib_nbextensions#963]
I'd like to customize color of frozen cell and read-only cell with `custom.css`.

Currently Freeze uses `style` attribute to change cell color, and color values are hardcoded in `main.js`. 
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/freeze/main.js#L77

I'd like to change to use `class` attribute and CSS instead. Can I send PR?

**Comment by jcb91** [comment]
Sure, sounds like a good plan to me!

**Comment by jcb91** [comment]
alternatively, you could make the colours configurable with the configurator - see the ExecuteTime nbextension for an example of a colour property, used for highlights.

**Comment by shingo78** [comment]
Thanks! @jcb91
