### ISSUE TITLE
Freeze: freeze cells automatically after execution

### ISSUE THREAD

**Issue by yacchin1205** [ipython-contrib/jupyter_contrib_nbextensions#965]
Hi,
We are developing *run-through* extension to apply the notebook to cloud infrastructure operation, and implements function to freeze cells when they are executed.
https://github.com/NII-cloud-operation/Jupyter-LC_run_through

Currently we have implemented these functions in *run-through* (like https://github.com/NII-cloud-operation/Jupyter-LC_run_through/blob/master/lc_run_through/nbextension/main.js#L315), but we assume that it should be one of these:
- Make freeze extension export `set_state(cell, state)` function and *run-through* uses it
- Implement *freeze executed cells* function in freeze extension

Though we'd like to make PR... Which is better?

**Comment by jcb91** [comment]
Given the change to how set_state will work in #958 (and any potential future changes), I'd be inclined to just export more functions from Freeze. However, in principal, I think we could _also_ have an optional _freeze cells on execution_ setting?

**Comment by yacchin1205** [comment]
@jcb91 Thank you for your comment(and fixing title)!
I think... it's not strange that Freeze has *freeze cells after executing* setting, but also think we should keep it simple... either will do.

Now... I will send a PR to export set_state function from Freeze when #958 is closed.

**Comment by jcb91** [comment]
You're welcome :)

On second thoughts, perhaps it makes sense to keep the freeze-after-executing code in your nbextension, as I can't think of an immediate use for it in regular usage. But, as you say, either will do :stuck_out_tongue_winking_eye: 

#958 is now closed, in favour of the rebased version #968, which is now merged. PR away :)

**Comment by yacchin1205** [comment]
Thanks @jcb91, I will send the PR 😄

**Comment by yacchin1205** [comment]
@jcb91 Thank you for accepting the PR! I'd like to keep the freeze-after-executing code in my extension, and close this issue. Thanks.

**Comment by jcb91** [comment]
No problem, thanks for submitting it 😊
