### ISSUE TITLE
Freeze: frozen cells are always unlocked when notebook is loaded

### ISSUE THREAD

**Issue by yacchin1205** [ipython-contrib/jupyter_contrib_nbextensions#975]
`migrate_state` function always unlocks an editable attribute, because the code below is executed even if there are no `cell.metadata.run_control.read_only`.

```
cell.metadata.editable = !cell.metadata.run_control.read_only;
```
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/freeze/main.js#L59

As a result, the editable metadata is set to true, and the get_state function returns `normal` for the cell after reloaded.

I assume that it is executed only when the metadata has `run_control.read_only` (with old metadata format).

**Comment by jcb91** [comment]
Yes, you're absolutely right, it should have read something more like

```javascript
if (cell.metadata.run_control.read_only === true) {
    cell.metadata.editable = false;
}
```

**Comment by yacchin1205** [comment]
@jcb91 Thank you for reviewing! I've sent the PR.

I also found the error below, it seems that there are no checking whether the attribute is defined... the PR includes its fix also.

```
[Freeze] Error: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at set_state (main.js?v=20170424120221:115)
    at initialize_states (main.js?v=20170424120221:154)
    at do_stuff_with_config (main.js?v=20170424120221:191)
```

**Comment by jcb91** [comment]
Thanks!
