### ISSUE TITLE
[request functionality] collapse/expanse all for codefolding

### ISSUE THREAD

**Issue by vinniec** [ipython-contrib/jupyter_contrib_nbextensions#982]
Would it be possible to add a shortcut to collapse/expand all collapsible blocks of code?

Thanks :)

**Comment by jcb91** [comment]
In every cell, or just currently-selected cells? (Could be configurable, or separate keys for both, I guess)

**Comment by vinniec** [comment]
In every cell.
The real reason I ask this is that whenever I open a notebook the column that contains the folding symbol is overlapped on the code.
This forces me to turn the cell into a markdown cell and then return it to a code cell.
In this way the column that contains the folding symbols goes away from the code again and I can finally collapse the code to my liking.
But in this process all code blocks are expanded and I have to close them all by hand.
It would be convenient for me to be able to recompress them all with a single click.
Thanks for support

**Comment by jcb91** [comment]
> The real reason I ask this is that whenever I open a notebook the column that contains the folding symbol is overlapped on the code.

Ok, so I guess maybe it would be better to just get this to initialise correctly, rather than introduce a workaround?

**Comment by jcb91** [comment]
so this issue (codefolding symbols overlapping code in reopened notebooks) was fixed in #977, which is included in release 0.2.8 as detailed in #988. Does that cover this, or would you still want a collapse-all button?

**Comment by vinniec** [comment]
Ok, I've updated the extensions just now and the problem does not seem to appear anymore.
I tried with a single ipynb document but I do not think the problem will be repeated, thanks for supporting!

**Comment by juhasch** [comment]
Thanks for reporting. Please keep us updated, if the problem appears again.

**Comment by juhasch** [comment]
Closing as hopefully finally fixed.
