### ISSUE TITLE
Cannot get 'chrome-clipboard' extension to work

### ISSUE THREAD

**Issue by chriad** [ipython-contrib/jupyter_contrib_nbextensions#984]
I try to paste images from the system clipboard into the notebook and it doesn't work. I belief it has to do with the jupyter-js-widget extension not having a valid yaml configuation file:

![widget](https://cloud.githubusercontent.com/assets/4353001/25860524/1bb20258-34e2-11e7-9b69-11c3a44c03ea.png)

Do I have to install another version of ipywidgets or another version of the widgetsnbextension or downgrade to a previous version of ipython or do is there a yaml file somwhere to be found?

I would appreciate any advice!

```
$ conda list | grep widgets
ipywidgets                5.2.2                    py36_1  
widgetsnbextension        1.2.6                    py36_0
```
I activate the extensions with the "nbextension configurator":

![nbgui](https://cloud.githubusercontent.com/assets/4353001/25860592/410bf5ea-34e2-11e7-8b8c-af49d3c7832e.png)

```
$ jupyter notebook -V
4.3.1
```

To install the extensions I use conda as described in the instructions:

`$ conda install -c conda-forge jupyter_contrib_nbextensions`

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/chriad/.jupyter/nbconfig
    notebook section
      chrome-clipboard/main  enabled 
      - Validating: OK
      contrib_nbextensions_help_item/main disabled
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /home/chriad/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

The output of the developer console in chrome does not show any errors, just a warning: (probably not relevant?)

    actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
    MenuBar.bind_events @ main.min.js:29204

This is some output I captured form the `jupyter notebook --debug` command:
```
$ cat dbgfile | grep "chrome-clipboard\|jupyter-js-widgets"
[D 18:11:07.037 NotebookApp] [jupyter_nbextensions_configurator] Found nbextension 'Chrome Clipboard' in chrome-clipboard/chrome-clipboard.yaml
[D 18:11:11.880 NotebookApp] Path jupyter-js-widgets/extension.js served from /home/chriad/anaconda3/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
[D 18:11:11.886 NotebookApp] 200 GET /nbextensions/jupyter-js-widgets/extension.js?v=20170509181105 (127.0.0.1) 6.30ms
[D 18:11:11.888 NotebookApp] Path chrome-clipboard/main.js served from /home/chriad/anaconda3/share/jupyter/nbextensions/chrome-clipboard/main.js
[D 18:11:11.889 NotebookApp] 200 GET /nbextensions/chrome-clipboard/main.js?v=20170509181105 (127.0.0.1) 1.92ms
```

**Comment by jcb91** [comment]
Hmm, I can't think of an obvious reason why this shouldn't be working, from what you describe. however, I don't really use chrome-clipboard, so am not very familiar with it. Perhaps @juhasch might have better ideas...

> I belief it has to do with the jupyter-js-widget extension not having a valid yaml configuation file

This is unlikely, the two are almost certainly unrelated. As far as I know, chrome-clipboard makes no use of jupyter-js-widgets, which isn't provided by this repo.

> The output of the developer console in chrome does not show any errors, just a warning: (probably not relevant?)

You're correct, this warning isn't relevant, and is just a result of the core notebook's registering the action *after* something has already used the action name. It doesn't cause any problems, and can be safely ignored. You see no log messages at all when attempting to paste images? Another check you can make is whether you see the nbextension getting loaded in the javascript dev console? There should be something like 

    Loading extension: chrome-clipboard/main                                                             utils.js:37

**Comment by juhasch** [comment]
Well there is now native copy/paste support in the notebook. Can you try this first (assuming you have notebook 5.0 installed) ?

The only useful function the extension has in notebook 5.0 is to allow pasting images. I will update the extension and docs accordingly.

**Comment by leemengtaiwan** [comment]
Thanks for making the extension!
Although I'm able to paste images from system clipboard, I can't make the images downloaded into the subdirectory I specified.

I have added

`
{
  "dragdrop": {
    "subdirectory": "images"
  }
` 

in my notebook.json but the pasted image's link is still look like this:

`![image.png](attachment:image.png)`

My jupyter notebook version is `5.1.0`, is it normal to have not images downloaded in subdirectory or am I missing something? Thanks in advance!

**Comment by juhasch** [comment]
This means you are using the built-in copy&paste functionality of notebook 5.1.0. Images are now stored as attachment inside the .ipynb notebook file.

The drag&drop extension is not working anymore.

**Comment by juhasch** [comment]
Deprecate extension: PR #1104

**Comment by leemengtaiwan** [comment]
@juhasch Thanks for the reply, so I guess it's recommended to just copy the images to the subdirectory and make link to it now?

**Comment by juhasch** [comment]
Oops, I accidently mentioned the drag&drop extension. However, it is the same for the chrome-clipboard extension: The functionality is now implemented in the notebook itself.

So as you say, you now need to copy the image to the subdirectory and manually link to it.

**Comment by leemengtaiwan** [comment]
@juhasch Thank you for your help!
