### ISSUE TITLE
Install error? post-link failed for: conda-forge::jupyter_contrib_nbextensions-0.2.7-py36_0 

### ISSUE THREAD

**Issue by dartdog** [ipython-contrib/jupyter_contrib_nbextensions#985]
on a refreshed Conda install to root get the following: any ideas?

```
 conda install -c conda-forge jupyter_contrib_nbextensions
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/tom/anaconda3:

The following NEW packages will be INSTALLED:

    jupyter_contrib_nbextensions: 0.2.7-py36_0 conda-forge

Proceed ([y]/n)? y

Linking packages ...
[jupyter_contrib_nbextensions]|                                                                           |   0%

LinkError: Link error: Error: post-link failed for: conda-forge::jupyter_contrib_nbextensions-0.2.7-py36_0 
```

**Comment by jcb91** [comment]
Nothing immediately springs to mind, but for the post-link (which basically just calls `jupyter contrib nbextension install --sys-prefix`) to fail, my first guess would be a permissions error, a filename being too long, or something existing/not existing in the right place.

The reason(s) for the specific failure should be logged in conda's `.messages.txt` file, which should be in `<conda_root>/envs/<env_name>/.messages.txt`, where `<conda_root>` is the root conda installation directory (normally `~/miniconda`, `~/miniconda3`, `~/anaconda`, `~/anaconda3` or similar), and `<env_name>` is the name of the conda env in which you attempted the install. If you could post the contents of that log file immediately after the failed installation attempt, we might get some helpful details :)

**Comment by dartdog** [comment]
Hmm now with jupyter_contrib_nbextensions: 0.2.8-py36_0 conda-forge vs 2.7.. no error so close it out I guess!

**Comment by megamindbrian** [comment]
I am getting this error on Windows and found my evns directory but there is no .messages.txt.

**Comment by juhasch** [comment]
Jupyterlab is a different package. You will get more help asking over there: https://github.com/jupyterlab/jupyterlab
