### ISSUE TITLE
Code folding triangle overlaps code for cells in reloaded notebooks

### ISSUE THREAD

**Issue by abprice** [ipython-contrib/jupyter_contrib_nbextensions#988]
The code folding triangle overlaps the code text it corresponds with and there is no vertical line separating the gutter from the rest of the code cell when a notebook is reloaded.

New cells render the code folding triangle and vertical gutter line as expected.  The issue is resolved in preexisting cells if the toggle line numbers extension is activated.

Could this be due to a conflicting extension?

![codefolding_issue](https://cloud.githubusercontent.com/assets/24905913/26069757/ef6aa230-3956-11e7-8927-a743cee1520a.PNG)

**Comment by jcb91** [comment]
This is (I think) also what's behind #982. I've seen it in the past, but it seems to be working ok for me at the moment in notebook 5.x. This may be a result of the notebook version, or (as you mention) it may be a result of interactions with other nbextensions.

What versions of notebook and the nbextensions repo are you using? What other nbextensions do you have enabled? Does disabling any of them fix this for you?

**Comment by abprice** [comment]
I get the issue for both notebook versions 4.3.1 and 5.0.0 (different conda environments). 

I have tried disabling all extensions other than codefolding (in notebook 5.0.0), but the issue persists. 
I generally have the  extensions shown in the attached image enabled.

![nbextensions_5](https://cloud.githubusercontent.com/assets/24905913/26073836/cae41d70-3964-11e7-8fc3-7514c7b9018c.PNG)

**Comment by jcb91** [comment]
Ok. I guess you're using the latest conda release (0.2.7?) rather than the repo master? There's a fix in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/977 which is likely to fix this for you. You can try applying it yourself if you're comfortable with trying that, otherwise, since you're at least the second person to have run into this, I'll roll another release tonight...

**Comment by abprice** [comment]
Ya, I am on 0.2.7. I will wait for the release tonight. Thanks.

**Comment by jcb91** [comment]
Ok, 0.2.8 is live as a [GitHub tag](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/releases/tag/0.2.8) and [on pypi](https://pypi.org/project/jupyter_contrib_nbextensions/0.2.8), conda-forge release to follow once https://github.com/conda-forge/jupyter_contrib_nbextensions-feedstock/pull/17 is merged & the resultant CI builds complete...

**Comment by jcb91** [comment]
and, now [on conda-forge](https://anaconda.org/conda-forge/jupyter_contrib_nbextensions/files?version=0.2.8) also. Closing this as fixed, but obviously please reopen if you find 0.2.8 doesn't fix it for you.

**Comment by jetheurer** [comment]
I have the same problem running on `Linux 4.4.0-77-generic#98-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux` 

```
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.1.0)
jupyter-contrib-core (0.3.1)
jupyter-contrib-nbextensions (0.2.8)
jupyter-core (4.3.0)
jupyter-highlight-selected-word (0.0.11)
jupyter-latex-envs (1.3.8.4)
jupyter-nbextensions-configurator (0.2.5)
```

**Comment by juhasch** [comment]
Sorry to hear that. Unfortunately, there are some subtle race conditions when loading extensions.
Does this happen with a specific notebook (e.g. a large one) ?

**Comment by juhasch** [comment]
If you checkout PR #1028, you can try setting a delay parameter to see if things improve.
