### ISSUE TITLE
not clear how to export the collapseable headings to html

### ISSUE THREAD

**Issue by doolingdavid** [ipython-contrib/jupyter_contrib_nbextensions#991]
Hi,
I love the collapseable headings functionality, but am am needing to have it be present in a html version of notebook for a report. When I do run this command:

    jupyter nbconvert --to html_ch MYFILE.ipynb

I get this error: 

```
Bad config encountered during initialization: The 'export format' trait of a NBConvertApp instance must be any of ['custom','html','latex', ....], but a value of 'html_ch' <class 'str'> was specified.
```

What am I missing?

**Comment by jcb91** [comment]
Hmm, I must admit that nothing obvious springs immediately to mind. What versions of python, nbconvert, juputer_nbextensions_configurator do you have installed? I'm away from a computer for a while, but will attempt to reproduce this once I get back to one...

**Comment by jcb91** [comment]
So it seems like the root of this may be that the `jupyter_contrib_nbextensions` package probably isn't installed in whichever python environment your `jupyter nbconvert` call ultimately ends up running from, and so nbconvert won't find the setuptools entry point which would normally be registered to declare the exporter's availability. This can happen if, for example, you have notebook installed in several conda environments (or virtualenvs), but `jupyter_contrib_nbextensions` is not installed in all of them. In such a case, if you run the notebook server from an environment with the install, you'll see all the nbextensions ok, but if you run the shell command

    jupyter nbconvert --to html_ch MYFILE.ipynb

from a _different_ environment (e.g. by not calling activate in a new shell), then `jupyter_contrib_nbextensions` is not found.

Could you check which nbconvert is being called (e.g. by reading the file locations from your error traceback)?

**Comment by jcb91** [comment]
Also, it seems that the ability to add in custom exporters was added in nbconvert 4.2.0, and from the traceback message you're getting, it looks like maybe you have an older version, so you may need to upgrade nbconvert...

**Comment by doolingdavid** [comment]
Dear jcb91,

Perfect! Your diagnosis was spot on; I had previously installed jupyter_contrib_nbextensions with pip, and that put it somewhere. Updating nbconvert with conda, and then trying to update jupyter_contrib_nbextensions with conda showed that your take on the problem was correct. After using conda to install everything. the export to html worked preserving the collapsable headers.

Thank you very much!

**Comment by jcb91** [comment]
No problem, glad it's working for you now :smile:
