### ISSUE TITLE
[toc2] changes width of notebook cells

### ISSUE THREAD

**Issue by ostrokach** [ipython-contrib/jupyter_contrib_nbextensions#993]
Enabling "Table of Contents (2)", even with all options unchecked, still changes the witdth of my notebook cells.

With "Table of Contents (2)" disabled:

![selection_014](https://cloud.githubusercontent.com/assets/5614375/26227088/38bec304-3bfe-11e7-94d1-ed73f2c2cbfc.png)

With "Table of Contents (2)" enabled (all options unchecked):

![selection_015](https://cloud.githubusercontent.com/assets/5614375/26227089/3cf103e2-3bfe-11e7-89a9-656c94f5eb51.png)

I'm trying to get a floating table of contents without changing the default witdth of my notebook cells.

Thank you!

---

```
jupyter_contrib_nbextensions 0.2.8-py36_0 conda-forge
```

**Comment by ostrokach** [comment]
Adding the following line to `~/.jupyter/custom/custom.css` and restarting seems to produce the desired result:

```
#notebook-container {
  width:1140px !important;
}
```

**Comment by jcb91** [comment]
> Adding the following line to ~/.jupyter/custom/custom.css and restarting seems to produce the desired result:

Unfortunately this will only be true for your screen width and other in the same range. For substantially different widths, this will cause a similar problem to what you're encountering. Toc2 *should* simply not alter the width *at all* with the option unchecked, but it appears that that is not happening, so this is a bug.

**Comment by jfbercher** [comment]
ok. I can reproduce and will have a look this we.

**Comment by jfbercher** [comment]
Closed by #994

**Comment by ostrokach** [comment]
I tried installing the latest master tarball:

```
pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
jupyter contrib nbextension install --sys-prefix
jupyter contrib nbextension install --user
```
restarted the jupyter notebook and refreshed all the windows, but I am still getting the same problem. Am I doing something wrong?

**Comment by jfbercher** [comment]
Can you try to open 
http://localhost:8888/nbextensions/toc2/toc2.js
(assuming that your server runs on port 8888)
and check if function setNotebookWidth(cfg, st) contains 
`$("#notebook-container").css({'width':''}) `?
This is just to check that you execute the last version.

**Comment by ostrokach** [comment]
Sorry, false alarm. I should have uninstalled the conda version before installing the master branch tarball using pip:

```
conda uninstall jupyter_contrib_nbextensions
pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
jupyter contrib nbextension install --sys-prefix
```

Now it works perfect.

Thanks a lot!!
